공통설정

In [2]:
import os
from dotenv import load_dotenv, find_dotenv
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.callbacks import UsageMetadataCallbackHandler

load_dotenv(find_dotenv(".env", usecwd=True), override=True)
MODEL = os.environ["OPENAI_DEFAULT_MODEL"]
LOWER = os.environ["OPENAI_LOWER_MODEL"]
JUDGE = os.environ["OPENAI_JUDGE_MODEL"]
EMBEDDING = os.environ["OPENAI_EMBEDDING_MODEL"]

PRICES = {MODEL: (2.50, 15.00), LOWER: (0.75, 4.50), EMBEDDING: (0.02, 0.0)}  # 1M 토큰당 (입력, 출력) USD
usage = UsageMetadataCallbackHandler()

llm = ChatOpenAI(model=MODEL)
embeddings = OpenAIEmbeddings(model=EMBEDDING)
PDF_DIR = "./manual"
GOLDEN = "./golden/manual.jsonl"

## ingestion (pdf 로더)

In [8]:
import re

# 마크다운 개수
def count_markdown_tables(text):
    pattern = r'\|.*\|\s*\n\|(?:\s*:?-+:?\s*\|)+'
    return len(re.findall(pattern, text))

In [ ]:
# 로더 비교
import time
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader, PDFPlumberLoader, PyMuPDFLoader

t0 = time.perf_counter()

# 파일 1 : 텍스트 + 사진 8페이지, 표 13페이지, 사진 15페이지
ven_total_manual = PDF_LIST[0]

for name, Loader in [("PyPDFLoader", PyPDFLoader),
                     ("PDFPlumberLoader", PDFPlumberLoader),
                     ("PyMuPDFLoader", PyMuPDFLoader)
                     ]:
    docs = Loader(ven_total_manual).load()
    print(f"{name:18} {len(docs):3d}쪽  {time.perf_counter() - t0:5.2f}s")
    print(f"텍스트+사진 : {len(docs[7].page_content):3d}자 메타데이터 {len(docs[7].metadata)}개\n", repr(docs[7].page_content))
    print(f"표 : {len(docs[12].page_content):3d}자 메타데이터 {len(docs[12].metadata)}개\n", repr(docs[12].page_content))
    print(f"사진 : {len(docs[14].page_content):3d}자 메타데이터 {len(docs[14].metadata)}개\n", repr(docs[14].page_content))
    print("\n")

markdown_PyMuPDFLoader = PyMuPDFLoader(
    ven_total_manual,
    mode="page",
    extract_tables="markdown"
)    
docs = markdown_PyMuPDFLoader.load()
name = "markdown_PyMuPDFLoader"
print(f"{name:18} {len(docs):3d}쪽  {time.perf_counter() - t0:5.2f}s")
print(f"텍스트+사진 : {len(docs[7].page_content):3d}자 메타데이터 {len(docs[7].metadata)}개\n", repr(docs[7].page_content))
print(f"표 : {len(docs[12].page_content):3d}자 메타데이터 {len(docs[12].metadata)}개\n", repr(docs[12].page_content))
display(Markdown(docs[12].page_content))
print(f"사진 : {len(docs[14].page_content):3d}자 메타데이터 {len(docs[14].metadata)}개\n", repr(docs[14].page_content))
print("\n")
print(
    "표가 있는 페이지:",
    sum(count_markdown_tables(doc.page_content) > 0 for doc in docs),
    "/",
    len(docs)
)
print(
    "전체 표 개수:",
    sum(count_markdown_tables(doc.page_content) for doc in docs)
)

In [9]:
import re
import time
import pandas as pd
import pymupdf

from pathlib import Path
from IPython.display import display, Markdown
from langchain_community.document_loaders import (
    PyPDFLoader,
    PDFPlumberLoader,
    PyMuPDFLoader,
)


def benchmark_pdf_loaders(
    pdf_path,
    text_page=None,
    table_page=None,
    image_page=None,
):
    """
    여러 PDF Loader의 추출 결과를 비교한다.

    페이지 번호는 1부터 시작한다.

    text_page / table_page / image_page가
    - None이거나
    - 1보다 작거나
    - 전체 페이지 수보다 크면

    해당 항목은 비교하지 않고 건너뛴다.
    """

    pdf_path = Path(pdf_path)

    # 실제 PDF 페이지 수
    with pymupdf.open(pdf_path) as pdf:
        actual_pages = pdf.page_count


    # -------------------------------------------
    # 유효한 페이지인지 확인
    # -------------------------------------------
    def is_valid_page(page_num):
        return (
            isinstance(page_num, int)
            and 1 <= page_num <= actual_pages
        )


    loaders = {
        "PyPDFLoader": {
            "loader": lambda: PyPDFLoader(
                str(pdf_path)
            ).load(),
            "markdown": False,
        },

        "PDFPlumberLoader": {
            "loader": lambda: PDFPlumberLoader(
                str(pdf_path)
            ).load(),
            "markdown": False,
        },

        "PyMuPDFLoader": {
            "loader": lambda: PyMuPDFLoader(
                str(pdf_path),
                mode="page",
            ).load(),
            "markdown": False,
        },

        "PyMuPDF + Markdown": {
            "loader": lambda: PyMuPDFLoader(
                str(pdf_path),
                mode="page",
                extract_tables="markdown",
            ).load(),
            "markdown": True,
        },
    }


    results = []


    for loader_name, config in loaders.items():

        try:

            # -------------------------------------------
            # Loader 실행 시간 측정
            # -------------------------------------------
            start = time.perf_counter()

            docs = config["loader"]()

            elapsed = time.perf_counter() - start


            # -------------------------------------------
            # 선택 페이지
            # 유효하지 않으면 None
            # -------------------------------------------
            text_doc = (
                docs[text_page - 1]
                if is_valid_page(text_page)
                else None
            )

            table_doc = (
                docs[table_page - 1]
                if is_valid_page(table_page)
                else None
            )

            image_doc = (
                docs[image_page - 1]
                if is_valid_page(image_page)
                else None
            )


            # -------------------------------------------
            # 전체 문자 수
            # -------------------------------------------
            total_chars = sum(
                len(doc.page_content)
                for doc in docs
            )


            # -------------------------------------------
            # Markdown 표 통계
            # -------------------------------------------
            if config["markdown"]:

                table_counts = [
                    count_markdown_tables(doc.page_content)
                    for doc in docs
                ]

                table_page_count = sum(
                    count > 0
                    for count in table_counts
                )

                total_table_count = sum(table_counts)

                table_page_ratio = (
                    table_page_count / len(docs)
                    if docs
                    else 0
                )

            else:

                table_page_count = None
                total_table_count = None
                table_page_ratio = None


            # -------------------------------------------
            # 결과 저장
            # -------------------------------------------
            results.append({
                "Loader": loader_name,

                "실행시간(sec)": round(elapsed, 3),

                "전체페이지": len(docs),

                "전체문자수": total_chars,

                "텍스트페이지":
                    text_page if text_doc else None,

                "텍스트페이지_문자수":
                    len(text_doc.page_content)
                    if text_doc else None,

                "표페이지":
                    table_page if table_doc else None,

                "표페이지_문자수":
                    len(table_doc.page_content)
                    if table_doc else None,

                "이미지페이지":
                    image_page if image_doc else None,

                "이미지페이지_문자수":
                    len(image_doc.page_content)
                    if image_doc else None,

                "메타데이터수":
                    len(docs[0].metadata)
                    if docs else 0,

                "Markdown표_페이지수":
                    table_page_count,

                "Markdown표_페이지비율":
                    table_page_ratio,

                "Markdown표_전체개수":
                    total_table_count,

                "상태": "OK",
            })


        except Exception as e:

            results.append({
                "Loader": loader_name,

                "실행시간(sec)": None,

                "전체페이지": None,

                "전체문자수": None,

                "텍스트페이지": None,
                "텍스트페이지_문자수": None,

                "표페이지": None,
                "표페이지_문자수": None,

                "이미지페이지": None,
                "이미지페이지_문자수": None,

                "메타데이터수": None,

                "Markdown표_페이지수": None,
                "Markdown표_페이지비율": None,
                "Markdown표_전체개수": None,

                "상태": f"ERROR: {e}",
            })


    result_df = pd.DataFrame(results)


    # -------------------------------------------
    # Markdown 표 비율 %
    # -------------------------------------------
    result_df["Markdown표_페이지비율"] = (
        result_df["Markdown표_페이지비율"]
        .apply(
            lambda x:
                f"{x:.1%}"
                if pd.notna(x)
                else "-"
        )
    )


    return result_df

In [10]:
# 특정 페이지 컨텐트 내용 보기
def show_page_content(
    pdf_path,
    page_num,
    loader_names=None,
    render_markdown=True
):
    """
    특정 PDF의 특정 페이지를 Loader별로 비교 출력한다.

    page_num은 1부터 시작.
    """

    loaders = {
        "PyPDFLoader": lambda: PyPDFLoader(
            str(pdf_path)
        ).load(),

        "PDFPlumberLoader": lambda: PDFPlumberLoader(
            str(pdf_path)
        ).load(),

        "PyMuPDFLoader": lambda: PyMuPDFLoader(
            str(pdf_path),
            mode="page"
        ).load(),

        "PyMuPDF + Markdown": lambda: PyMuPDFLoader(
            str(pdf_path),
            mode="page",
            extract_tables="markdown"
        ).load(),
    }

    # 지정하지 않으면 전체 Loader 출력
    if loader_names is None:
        loader_names = list(loaders.keys())

    for loader_name in loader_names:

        docs = loaders[loader_name]()

        # 잘못된 페이지면 건너뜀
        if page_num < 1 or page_num > len(docs):
            print(
                f"{loader_name}: "
                f"{page_num}페이지 없음 "
                f"(전체 {len(docs)}페이지)"
            )
            continue

        doc = docs[page_num - 1]

        display(
            Markdown(
                f"{loader_name} "
                f"- {page_num}페이지"
            )
        )

        print(f"문자수: {len(doc.page_content)}")
        print(f"metadata: {doc.metadata}")
        print(f"page_content: {doc.page_content}")

        if render_markdown:
            display(Markdown(doc.page_content))

        print("-" * 100)

In [4]:
# 마크다운 표 확인
def extract_markdown_tables(text: str):
    """
    Markdown 표만 추출해서 리스트로 반환
    """

    pattern = re.compile(
        r"""
        (
            ^\s*\|.*\|\s*$\n
            ^\s*\|?\s*:?-{3,}:?\s*
            (?:\|\s*:?-{3,}:?\s*)+
            \|?\s*$\n
            (?:^\s*\|.*\|\s*$\n?)*
        )
        """,
        re.MULTILINE | re.VERBOSE
    )

    return [
        match.group(1).strip()
        for match in pattern.finditer(text)
    ]

def extract_all_markdown_tables(pdf_path):

    results = []
    docs = PyMuPDFLoader(
    pdf_path,
    mode="page",
    extract_tables="markdown"
    ).load()

    for page_idx, doc in enumerate(docs):

        tables = extract_markdown_tables(
            doc.page_content
        )

        for table_idx, table in enumerate(
            tables,
            start=1
        ):

            results.append({
                "page": page_idx + 1,
                "table_no": table_idx,
                "markdown": table,
            })
            display(Markdown(table))

    return results

In [11]:
PDF_LIST = sorted(Path(PDF_DIR).glob("*.pdf"))
page_configs = [
    [8, 13, 15],     # 1번 PDF
    [4, 27, 25],    # 2번 PDF
    [8, None, 16],   # 3번 PDF
    [None, 23, 9],     # 4번 PDF
    [8, None, 10],
    [6, 13, 17],
    [6, 5, 4],
    [37, 10, 4]
]

for pdf_path, pages in zip(PDF_LIST, page_configs):
    text_page, table_page, image_page = pages

    result_df = benchmark_pdf_loaders(
        pdf_path=pdf_path,
        text_page=text_page,
        table_page=table_page,
        image_page=image_page,
    )

    print(pdf_path)
    display(result_df)

manual/1. 협력사 운영 통합 안내서 (p.23).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,1.193,23,8366,8,371,13,517,15,408,11,NaN,-,NaN,OK
1,PDFPlumberLoader,1.679,23,8335,8,364,13,518,15,408,11,NaN,-,NaN,OK
2,PyMuPDFLoader,0.070,23,8224,8,357,13,517,15,405,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,0.706,23,14294,8,357,13,1145,15,405,16,14.0,60.9%,21.0,OK

manual/2. Hmall 소개서 (p.30).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,2.435,30,7237,4,312,27,22,25,193,11,NaN,-,NaN,OK
1,PDFPlumberLoader,4.334,30,6783,4,312,27,23,25,170,11,NaN,-,NaN,OK
2,PyMuPDFLoader,0.097,30,6206,4,271,27,20,25,165,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,2.272,30,8652,4,271,27,1040,25,165,16,6.0,20.0%,11.0,OK

manual/3. 쇼라 소개서 (p.22).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,0.045,22,0,8,0,None,None,16,0,11,NaN,-,NaN,OK
1,PDFPlumberLoader,0.039,22,22,8,1,None,None,16,1,11,NaN,-,NaN,OK
2,PyMuPDFLoader,0.012,22,0,8,0,None,None,16,0,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,0.021,22,0,8,0,None,None,16,0,16,0.0,0.0%,0.0,OK

manual/4. 광고 상품 소개서 (p.24).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,13.294,24,9588,None,None,23,1049,9,260,10,NaN,-,NaN,OK
1,PDFPlumberLoader,26.336,24,8995,None,None,23,938,9,239,10,NaN,-,NaN,OK
2,PyMuPDFLoader,0.353,24,8625,None,None,23,923,9,221,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,7.231,24,39849,None,None,23,2495,9,1450,16,22.0,91.7%,24.0,OK

manual/5. 협력사시스템 사용법 (p.10).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,0.547,10,6,8,0,None,None,10,6,11,NaN,-,NaN,OK
1,PDFPlumberLoader,1.640,10,16,8,1,None,None,10,7,11,NaN,-,NaN,OK
2,PyMuPDFLoader,0.028,10,6,8,0,None,None,10,6,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,0.711,10,6,8,0,None,None,10,6,16,0.0,0.0%,0.0,OK

manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,7.473,21,6578,6,556,13,361,17,372,11,NaN,-,NaN,OK
1,PDFPlumberLoader,16.041,21,6578,6,558,13,363,17,376,11,NaN,-,NaN,OK
2,PyMuPDFLoader,0.181,21,6473,6,553,13,359,17,370,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,3.980,21,6986,6,553,13,642,17,370,16,2.0,9.5%,2.0,OK

manual/7. 데이터 영역 광고 제안서 (p.8).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,0.097,8,1089,6,353,5,110,4,49,11,NaN,-,NaN,OK
1,PDFPlumberLoader,0.227,8,1108,6,354,5,113,4,50,11,NaN,-,NaN,OK
2,PyMuPDFLoader,0.017,8,994,6,325,5,103,4,46,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,0.125,8,1748,6,601,5,253,4,46,16,4.0,50.0%,4.0,OK

manual/8. QA가이드 (p.21).pdf

,Loader,실행시간(sec),전체페이지,전체문자수,텍스트페이지,텍스트페이지_문자수,표페이지,표페이지_문자수,이미지페이지,이미지페이지_문자수,메타데이터수,Markdown표_페이지수,Markdown표_페이지비율,Markdown표_전체개수,상태
0,PyPDFLoader,0.996,38,23965,37,304,10,1071,4,199,10,NaN,-,NaN,OK
1,PDFPlumberLoader,2.232,38,23886,37,318,10,1112,4,206,9,NaN,-,NaN,OK
2,PyMuPDFLoader,0.057,38,22239,37,263,10,946,4,179,16,NaN,-,NaN,OK
3,PyMuPDF + Markdown,2.787,38,46743,37,263,10,1883,4,179,16,24.0,63.2%,30.0,OK

PDF별 결과 정리

In [6]:
#1. 협력사 운영 통합 안내서 (p.23).pdf : PyMu + Markdown / 3~22페이지
show_page_content(pdf_path=PDF_LIST[0], page_num=13)

NameError: name 'show_page_content' is not defined

In [11]:
extract_all_markdown_tables(PDF_LIST[0])

|방송<br>LIVE / DATA|· 100여개의방송채널을통해전국으로송출<br>· LIVE: 실시간영상/ DATA: 녹화영상<br>· 경쟁력있는고정PGM 운영<br>· 생활, 패션, 트렌드, 렌탈, 금융등<br>· 주문방식: 상담원, ARS, WEB, 모바일|
|---|---|


|Hmall<br>온라인몰|· 온라인전용판매매체<br>(방송상품동시판매가능)<br>· 다양한상품군을<br>구성제한없이판매<br>· 광고/마케팅/제휴지원<br>· 주문방식: WEB, 모바일|
|---|---|


|쇼라<br>모바일라이브|· 쌍방향소통이가능한<br>모바일전용라이브커머스<br>· MZ 고객층과의가교역할<br>· 대표브랜딩‘믿고사쇼라’<br>· 주문방식: 모바일|
|---|---|

|단계|내용|
|---|---|
|**협력사제안**|**협력사가파트너시스템을통해신상품제안**|
|**상품평가및입점**|**MD가상품검토후, 최종입점결정**|
|**상품등록**|**상품정보입력**|
|**QA**|**현장및사전QA**|
|**방송편성**|**상품군, 목표등을고려하여방송시간편성**|
|**심의**|**영상및자막에대한심의검토**|
|**사전전략회의**|**상품특장점및소구포인트등방송진행방향논의**|
|**방송판매**|**Live 방송진행**|
|**사후전략회의**|**방송실적분석, 개선점공유및차후운영방향협의**|
|**배송**|**출고및배송체크**|
|**CS**|**고객불만접수및처리**|
|**정산**|**대금지급**|


|단계|내용|
|---|---|
|**협력사제안**|**협력사가파트너시스템을통해신상품제안**|
|**상품평가및입점**|**MD가상품검토후, 최종입점결정**|
|**상품등록**|**상품정보입력**|
|**QA/심의**|**웹기술서심의**|
|**(프로모션)**|**상품및행사에맞는쿠폰/적립/무이자등판촉협의**|
|**(광고)**|**상품및행사에맞는배너/탭/팝업등광고협의**|
|**(링크/DB 제휴)**|**가격비교사이트및타쇼핑몰노출협의**|
|**판매**|**Hmall노출**|
|**사후관리**|**실적분석, 행사/기획전리뷰**|
|**배송**|**출고및배송체크**|
|**CS**|**고객불만접수및처리**|
|**정산**|**대금지급**|

|Col1|Col2|Col3|
|---|---|---|
||||
||||

|Col1|Col2|
|---|---|
|**필독으**||
|||

|① QA 의뢰|② QA 자료 업로드|③ QA 검토|
|---|---|---|


|⑥ 사후 관리|⑦ 검사|
|---|---|

|구분|내용|Col3|
|---|---|---|
|**사전QA**|**상품별서류및샘플점검을통한상품전반의품질관리업무를총괄**|**상품별서류및샘플점검을통한상품전반의품질관리업무를총괄**|
|**사전QA**|**기준일**|**의뢰: 방송일기준최소14일전의뢰/ 완료: 방송일기준최소4일전완료**|
|**사전QA**|**업무**|**법적준수사항이행여부확인, 품질서류검토,**<br>**원산지검증, 방송품질소구관련증빙자료검토등**|
|**현장QA**|**제조사, 물류센터방문을통한완제품의진정성을확인**|**제조사, 물류센터방문을통한완제품의진정성을확인**|
|**현장QA**|**기준일**|**의뢰: 방송일기준최소10일전의뢰/ 완료: 방송일기준최소4일전완료**|
|**현장QA**|**업무**|**제조사위생점검및원료및자재관리점검, 품질표시정보확인,**<br>**완제품규격및포장상태점검, 외관불량및구성품혼입점검등**|
|**입고QA**|**현대물류센터입고상품대상, 샘플링점검을통한입고가능여부최종검사**|**현대물류센터입고상품대상, 샘플링점검을통한입고가능여부최종검사**|
|**입고QA**|**기준일**|**의뢰: 방송일기준최소3일전의뢰**|
|**입고QA**|**업무**|**구성품혼입, 상품오염, 내외관불량표시, 정보오류점검등**|

|구분|출고<br>기준일|방송<br>시간|방송<br>당일|방송<br>+1일|방송<br>+2일|방송<br>+3일|
|---|---|---|---|---|---|---|
|**일반상품/**<br>**일반식품**|**1일**|**주간**|**60%**|**40%**|**-**|**-**|
|**일반상품/**<br>**일반식품**|**1일**|**야간**|**-**|**100%**|**-**|**-**|
|**일반상품/**<br>**일반식품**|**2일**|**주간**|**60%**|**30%**|**10%**|**-**|
|**일반상품/**<br>**일반식품**|**2일**|**야간**|**-**|**90%**|**10%**|**-**|
|**일반상품/**<br>**일반식품**|**3일**|**주간**|**60%**|**20%**|**10%**|**10%**|
|**일반상품/**<br>**일반식품**|**3일**|**야간**|**-**|**80%**|**10%**|**10%**|
|**냉동/냉장**<br>**식품**|**3일**|**주간**|**50%**|**20%**|**20%**|**10%**|
|**냉동/냉장**<br>**식품**|**3일**|**야간**|**-**|**50%**|**30%**|**20%**|


|주문일|출고기준일|출고마감일|내용|
|---|---|---|---|
|**05.27(월)**|**1일**|**05.28(화)**|**05.27~28출고가능**|
|**05.27(월)**|**2일**|**05.29(수)**|**05.27~29출고가능**|
|**05.27(월)**|**3일**|**05.30(목)**|**05.27~30출고가능**|
|**05.24(금)**|**1일**|**05.25(토)**|**05.24~25출고가능**|
|**05.24(금)**|**2일**|**05.27(월)**|**05.24~27출고가능**|
|**05.24(금)**|**3일**|**05.28(화)**|**05.24~28출고가능**|

|화면명(번호)|Col2|내용|
|---|---|---|
|**입고요청등록/현황**|**(VD310)**|**입고요청및내역조회-입고요청수량입력및발주, 조건별내역조회, 입고요청서출력등**|
|**출고/회수리스트**|**(VD301)**|**출고/회수및내역조회-배송형태별/출고진행상태별/회수진행상태별내역조회, 주문서수정등**|

|화면명(번호)|Col2|내용|
|---|---|---|
|**협력사Ref접수**|**(VD401)**|**협력사에서당사로확인요청**|
|**협력사Ref처리**|**(VD402)**|**당사에서요청된건에대한답변입력**|
|**택배사Ref접수**|**(VD923)**|**택배사에서당사로확인요청**|
|**택배사Ref처리**|**(VD924)**|**당사에서요청된건에대한답변입력**|
|**AS처리**|**(VD404)**|**당사에서요청된건에대한답변입력**|
|**드림CS**|**(VD403)**|**소비자의의견을경영자(임원)가직접처리및내부공유**|
|**품질이상처리**|**(VD913)**|**품질관련불만이판매량대비2% 이상접수되는상품확인**|
|**불만접수현황(사유별)**|**(VD703)**|**협력사에서진행하는상품들의불만현황파악**|
|**Ref미처리현황(실시간)**|**(VD704)**|**실시간미처리현황**|

|구분|내용|
|---|---|
|**사업자**<br>**등록증**|**발행일자구분없음**<br>**※ 개인사업자의경우주민등록등본(원본), 신분증사본**|
|**통장**<br>**사본**|**당사협력사현황표에기재된사업자명표시필수(★인감날인본)**<br>**※ 개인사업자의경우대표자명과회사명함께기재가능**|
|**이행(지급)**<br>**보증보험**|**· 일반상품군: 방송/데이터방송1천만원~, 인터넷5백만원~**<br>**· A/S상품군: 방송/데이터방송5천만원~, 인터넷1천만원~**|
|**이행(지급)**<br>**보증보험**|**최초2년가입1년단위추가갱신/ 1년이상보증보험기간상시유지**|


|구분|내용|
|---|---|
|**정산**<br>**주기**|**· 1주기: 01일~ 10일**<br>**· 2주기: 11일~ 20일**<br>**· 3주기: 21일~ 31일(말일)**|
|**대금**<br>**정산**|**· 공급가정산:주기별마감후영업일기준+5일**<br>**※ 대기업의경우정산주기마감+25 영업일뒤지급**<br>**· 부가세정산: 익월10일세금계산서승인마감후+5영업일**<br>**※ 대기업의경우매월1주기대금지급일**|
|**정산**<br>**기준**|**· 특약: 주문출고확정일기준매출발생**<br>**· 직매입: 입고확정일기준매출발생**|

|구분|내용|Col3|Col4|
|---|---|---|---|
|**발행방식**|**정발행**|**상품을공급하는자→ 상품을공급받는자**|**상품을공급하는자→ 상품을공급받는자**|
|**발행방식**|**역발행**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|
|**마감**|**당사**|**매월1일마감세금계산서발행**|**매월1일마감세금계산서발행**|
|**마감**|**협력사**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|
|**부가세**<br>**지급**|**부가세금액은월1회(매월10일)인증값을기준으로마감,**<br>**익월중순경해당월1주기상품대금과합산하여지급**|**부가세금액은월1회(매월10일)인증값을기준으로마감,**<br>**익월중순경해당월1주기상품대금과합산하여지급**|**부가세금액은월1회(매월10일)인증값을기준으로마감,**<br>**익월중순경해당월1주기상품대금과합산하여지급**|
|**발행금액**<br>**(배송형태별)**|**물류센터입고**|**물류센터입고**|**물류센터입고분(당사매입분)**|
|**발행금액**<br>**(배송형태별)**|**직접배송**|**직접배송**|**출고분(상품대금지급대상금액)**|


|화면명(번호)|내용|
|---|---|
|**매입매출현황**<br>**(VD603)**|**협력사의기간별매입/매출내역파악**|
|**대금지불내역**<br>**(VD606)**|**협력사의주기별정산내역확인**|
|**공제상세현황**<br>**(VD607)**|**협력사의주기별공제항목별상세내역확인**|
|**전자세금계산서**<br>**(DP502)**|**세금계산서종류별발행내역확인및**<br>**세금계산서승인화면접속**|
|**전자채권채무조회**<br>**(AF341)**|**협력사의채권채무조회서전자발급신청**|

|Hmall제휴|홍보 / 브랜드마케팅|Col3|
|---|---|---|
|**○신규매체/플랫폼전략제휴**<br>**○판매수수료기반CPS(Cost per sale) 제휴**|**○언론홍보/보도자료**<br>**○온라인바이럴/디지털광고**|**○방송행사및대외이벤트**<br>**○친환경캠페인**|
|**▷담당자연락처yunsh_@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|
|**퍼포먼스마케팅**|**Hmall내부광고**|**Hmall내부광고**|
|**○방송/Hmall신규광고및플랫폼제안**<br>**○검색광고-키워드/쇼핑검색등**<br>**○퍼포먼스광고-DA/APP/SNS**|**○HmallPC/모바일광고**<br>**○Hmall배너광고**<br>**광고상품소개서바로가기**|**○HmallPC/모바일광고**<br>**○Hmall배너광고**<br>**광고상품소개서바로가기**|
|**▷담당자연락처chasy@hyundaihmall.com**|**▷담당자연락처kmsong1523377@hyundaihmall.com**|**▷담당자연락처kmsong1523377@hyundaihmall.com**|

[{'page': 3,
  'table_no': 1,
  'markdown': '|방송<br>LIVE / DATA|· 100여개의방송채널을통해전국으로송출<br>· LIVE: 실시간영상/ DATA: 녹화영상<br>· 경쟁력있는고정PGM 운영<br>· 생활, 패션, 트렌드, 렌탈, 금융등<br>· 주문방식: 상담원, ARS, WEB, 모바일|\n|---|---|\n\n\n|Hmall<br>온라인몰|· 온라인전용판매매체<br>(방송상품동시판매가능)<br>· 다양한상품군을<br>구성제한없이판매<br>· 광고/마케팅/제휴지원<br>· 주문방식: WEB, 모바일|\n|---|---|\n\n\n|쇼라<br>모바일라이브|· 쌍방향소통이가능한<br>모바일전용라이브커머스<br>· MZ 고객층과의가교역할<br>· 대표브랜딩‘믿고사쇼라’<br>· 주문방식: 모바일|\n|---|---|'},
 {'page': 4,
  'table_no': 1,
  'markdown': '|단계|내용|\n|---|---|\n|**협력사제안**|**협력사가파트너시스템을통해신상품제안**|\n|**상품평가및입점**|**MD가상품검토후, 최종입점결정**|\n|**상품등록**|**상품정보입력**|\n|**QA**|**현장및사전QA**|\n|**방송편성**|**상품군, 목표등을고려하여방송시간편성**|\n|**심의**|**영상및자막에대한심의검토**|\n|**사전전략회의**|**상품특장점및소구포인트등방송진행방향논의**|\n|**방송판매**|**Live 방송진행**|\n|**사후전략회의**|**방송실적분석, 개선점공유및차후운영방향협의**|\n|**배송**|**출고및배송체크**|\n|**CS**|**고객불만접수및처리**|\n|**정산**|**대금지급**|\n\n\n|단계|내용|\n|---|---|\n|**협력사제안**|**협력사가파트너시스템을통해신상품제안**|\n|**상품평가및입점**|**MD가상품검토후, 최종입점결정**|\n|**상품등록**|**상품정보입력**|\n|**QA/심의**|**웹기술서심의**|\n|**(프로모션)**|**상품및행사에맞는쿠폰/적립/무이자등판촉협의**|\n|**(광고)**|**상품및행사에맞는배너/탭/팝업등광고협의**|\n|**(링크/DB 제휴)**|**가격비교사이트및타쇼핑몰노출협의**|\n|**판매**|**Hmall노출**|\n|**사후관리**|**실적분석, 행사/기획전리뷰**|\n|**배송**|**출고및배송체크**|\n|**CS**|**고객불만접수및처리**|\n|**정산**|**대금지급**|'},
 {'page': 6,
  'table_no': 1,
  'markdown': '|Col1|Col2|Col3|\n|---|---|---|\n||||\n||||'},
 {'page': 7,
  'table_no': 1,
  'markdown': '|Col1|Col2|\n|---|---|\n|**필독으**||\n|||'},
 {'page': 12,
  'table_no': 1,
  'markdown': '|① QA 의뢰|② QA 자료 업로드|③ QA 검토|\n|---|---|---|\n\n\n|⑥ 사후 관리|⑦ 검사|\n|---|---|'},
 {'page': 13,
  'table_no': 1,
  'markdown': '|구분|내용|Col3|\n|---|---|---|\n|**사전QA**|**상품별서류및샘플점검을통한상품전반의품질관리업무를총괄**|**상품별서류및샘플점검을통한상품전반의품질관리업무를총괄**|\n|**사전QA**|**기준일**|**의뢰: 방송일기준최소14일전의뢰/ 완료: 방송일기준최소4일전완료**|\n|**사전QA**|**업무**|**법적준수사항이행여부확인, 품질서류검토,**<br>**원산지검증, 방송품질소구관련증빙자료검토등**|\n|**현장QA**|**제조사, 물류센터방문을통한완제품의진정성을확인**|**제조사, 물류센터방문을통한완제품의진정성을확인**|\n|**현장QA**|**기준일**|**의뢰: 방송일기준최소10일전의뢰/ 완료: 방송일기준최소4일전완료**|\n|**현장QA**|**업무**|**제조사위생점검및원료및자재관리점검, 품질표시정보확인,**<br>**완제품규격및포장상태점검, 외관불량및구성품혼입점검등**|\n|**입고QA**|**현대물류센터입고상품대상, 샘플링점검을통한입고가능여부최종검사**|**현대물류센터입고상품대상, 샘플링점검을통한입고가능여부최종검사**|\n|**입고QA**|**기준일**|**의뢰: 방송일기준최소3일전의뢰**|\n|**입고QA**|**업무**|**구성품혼입, 상품오염, 내외관불량표시, 정보오류점검등**|'},
 {'page': 16,
  'table_no': 1,
  'markdown': '|구분|출고<br>기준일|방송<br>시간|방송<br>당일|방송<br>+1일|방송<br>+2일|방송<br>+3일|\n|---|---|---|---|---|---|---|\n|**일반상품/**<br>**일반식품**|**1일**|**주간**|**60%**|**40%**|**-**|**-**|\n|**일반상품/**<br>**일반식품**|**1일**|**야간**|**-**|**100%**|**-**|**-**|\n|**일반상품/**<br>**일반식품**|**2일**|**주간**|**60%**|**30%**|**10%**|**-**|\n|**일반상품/**<br>**일반식품**|**2일**|**야간**|**-**|**90%**|**10%**|**-**|\n|**일반상품/**<br>**일반식품**|**3일**|**주간**|**60%**|**20%**|**10%**|**10%**|\n|**일반상품/**<br>**일반식품**|**3일**|**야간**|**-**|**80%**|**10%**|**10%**|\n|**냉동/냉장**<br>**식품**|**3일**|**주간**|**50%**|**20%**|**20%**|**10%**|\n|**냉동/냉장**<br>**식품**|**3일**|**야간**|**-**|**50%**|**30%**|**20%**|\n\n\n|주문일|출고기준일|출고마감일|내용|\n|---|---|---|---|\n|**05.27(월)**|**1일**|**05.28(화)**|**05.27~28출고가능**|\n|**05.27(월)**|**2일**|**05.29(수)**|**05.27~29출고가능**|\n|**05.27(월)**|**3일**|**05.30(목)**|**05.27~30출고가능**|\n|**05.24(금)**|**1일**|**05.25(토)**|**05.24~25출고가능**|\n|**05.24(금)**|**2일**|**05.27(월)**|**05.24~27출고가능**|\n|**05.24(금)**|**3일**|**05.28(화)**|**05.24~28출고가능**|'},
 {'page': 17,
  'table_no': 1,
  'markdown': '|화면명(번호)|Col2|내용|\n|---|---|---|\n|**입고요청등록/현황**|**(VD310)**|**입고요청및내역조회-입고요청수량입력및발주, 조건별내역조회, 입고요청서출력등**|\n|**출고/회수리스트**|**(VD301)**|**출고/회수및내역조회-배송형태별/출고진행상태별/회수진행상태별내역조회, 주문서수정등**|'},
 {'page': 19,
  'table_no': 1,
  'markdown': '|화면명(번호)|Col2|내용|\n|---|---|---|\n|**협력사Ref접수**|**(VD401)**|**협력사에서당사로확인요청**|\n|**협력사Ref처리**|**(VD402)**|**당사에서요청된건에대한답변입력**|\n|**택배사Ref접수**|**(VD923)**|**택배사에서당사로확인요청**|\n|**택배사Ref처리**|**(VD924)**|**당사에서요청된건에대한답변입력**|\n|**AS처리**|**(VD404)**|**당사에서요청된건에대한답변입력**|\n|**드림CS**|**(VD403)**|**소비자의의견을경영자(임원)가직접처리및내부공유**|\n|**품질이상처리**|**(VD913)**|**품질관련불만이판매량대비2% 이상접수되는상품확인**|\n|**불만접수현황(사유별)**|**(VD703)**|**협력사에서진행하는상품들의불만현황파악**|\n|**Ref미처리현황(실시간)**|**(VD704)**|**실시간미처리현황**|'},
 {'page': 20,
  'table_no': 1,
  'markdown': '|구분|내용|\n|---|---|\n|**사업자**<br>**등록증**|**발행일자구분없음**<br>**※ 개인사업자의경우주민등록등본(원본), 신분증사본**|\n|**통장**<br>**사본**|**당사협력사현황표에기재된사업자명표시필수(★인감날인본)**<br>**※ 개인사업자의경우대표자명과회사명함께기재가능**|\n|**이행(지급)**<br>**보증보험**|**· 일반상품군: 방송/데이터방송1천만원~, 인터넷5백만원~**<br>**· A/S상품군: 방송/데이터방송5천만원~, 인터넷1천만원~**|\n|**이행(지급)**<br>**보증보험**|**최초2년가입1년단위추가갱신/ 1년이상보증보험기간상시유지**|\n\n\n|구분|내용|\n|---|---|\n|**정산**<br>**주기**|**· 1주기: 01일~ 10일**<br>**· 2주기: 11일~ 20일**<br>**· 3주기: 21일~ 31일(말일)**|\n|**대금**<br>**정산**|**· 공급가정산:주기별마감후영업일기준+5일**<br>**※ 대기업의경우정산주기마감+25 영업일뒤지급**<br>**· 부가세정산: 익월10일세금계산서승인마감후+5영업일**<br>**※ 대기업의경우매월1주기대금지급일**|\n|**정산**<br>**기준**|**· 특약: 주문출고확정일기준매출발생**<br>**· 직매입: 입고확정일기준매출발생**|'},
 {'page': 21,
  'table_no': 1,
  'markdown': '|구분|내용|Col3|Col4|\n|---|---|---|---|\n|**발행방식**|**정발행**|**상품을공급하는자→ 상품을공급받는자**|**상품을공급하는자→ 상품을공급받는자**|\n|**발행방식**|**역발행**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|\n|**마감**|**당사**|**매월1일마감세금계산서발행**|**매월1일마감세금계산서발행**|\n|**마감**|**협력사**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|\n|**부가세**<br>**지급**|**부가세금액은월1회(매월10일)인증값을기준으로마감,**<br>**익월중순경해당월1주기상품대금과합산하여지급**|**부가세금액은월1회(매월10일)인증값을기준으로마감,**<br>**익월중순경해당월1주기상품대금과합산하여지급**|**부가세금액은월1회(매월10일)인증값을기준으로마감,**<br>**익월중순경해당월1주기상품대금과합산하여지급**|\n|**발행금액**<br>**(배송형태별)**|**물류센터입고**|**물류센터입고**|**물류센터입고분(당사매입분)**|\n|**발행금액**<br>**(배송형태별)**|**직접배송**|**직접배송**|**출고분(상품대금지급대상금액)**|\n\n\n|화면명(번호)|내용|\n|---|---|\n|**매입매출현황**<br>**(VD603)**|**협력사의기간별매입/매출내역파악**|\n|**대금지불내역**<br>**(VD606)**|**협력사의주기별정산내역확인**|\n|**공제상세현황**<br>**(VD607)**|**협력사의주기별공제항목별상세내역확인**|\n|**전자세금계산서**<br>**(DP502)**|**세금계산서종류별발행내역확인및**<br>**세금계산서승인화면접속**|\n|**전자채권채무조회**<br>**(AF341)**|**협력사의채권채무조회서전자발급신청**|'},
 {'page': 22,
  'table_no': 1,
  'markdown': '|Hmall제휴|홍보 / 브랜드마케팅|Col3|\n|---|---|---|\n|**○신규매체/플랫폼전략제휴**<br>**○판매수수료기반CPS(Cost per sale) 제휴**|**○언론홍보/보도자료**<br>**○온라인바이럴/디지털광고**|**○방송행사및대외이벤트**<br>**○친환경캠페인**|\n|**▷담당자연락처yunsh_@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|\n|**퍼포먼스마케팅**|**Hmall내부광고**|**Hmall내부광고**|\n|**○방송/Hmall신규광고및플랫폼제안**<br>**○검색광고-키워드/쇼핑검색등**<br>**○퍼포먼스광고-DA/APP/SNS**|**○HmallPC/모바일광고**<br>**○Hmall배너광고**<br>**광고상품소개서바로가기**|**○HmallPC/모바일광고**<br>**○Hmall배너광고**<br>**광고상품소개서바로가기**|\n|**▷담당자연락처chasy@hyundaihmall.com**|**▷담당자연락처kmsong1523377@hyundaihmall.com**|**▷담당자연락처kmsong1523377@hyundaihmall.com**|'}]

In [ ]:
#2. hmall 소개서 : 표 헤더밖에 못가져옴_이미지로 처리 필요 / 3~26 => PDFPlumberLoader  (위치 그대로 가져옴)
show_page_content(pdf_path=PDF_LIST[1], page_num=27)

In [ ]:
extract_all_markdown_tables(PDF_LIST[1])

In [12]:
#3. 쇼라소개서 : 아무것도 못읽음 -> 일단 제외
show_page_content(pdf_path=PDF_LIST[2], page_num=3)

PyPDFLoader - 3페이지

문자수: 0
metadata: {'producer': 'Microsoft® PowerPoint® 2016', 'creator': 'Microsoft® PowerPoint® 2016', 'creationdate': '2024-04-03T16:14:08+09:00', 'title': 'PowerPoint 프레젠테이션', 'author': '하유림 선임', 'moddate': '2024-04-03T16:14:08+09:00', 'fasoo_trace_id': 'eyAibm9kZUNvdW50IjogOSwgIm5vZGUxIiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDAwOjQxOjQxWiIsInBJRCI6MSwidHJhY2VJZCI6IjFEOUNDQUQwRjlDMzREQzJCNDk1NEZBNzNGOTJGQTVFIiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGUyIiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDAxOjE1OjI1WiIsInBJRCI6MSwidHJhY2VJZCI6IjY5RUEyRjgyN0FEODRGMTNCNTA2QjRCRTAxMEVFMjZFIiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGUzIiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDA3OjAyOjUzWiIsInBJRCI6MSwidHJhY2VJZCI6IjM1Qzk1MTBEMzBERDQzQTI5OThEOThFN0MwMzE4RjM3IiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGU0IiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDA3OjA2OjE3WiIsInBJRCI6MSwidHJhY2VJZCI6IjM0MEE3MTA3RTY4RDRCNEI4RjQ2QTAyNzJFMjg5OTk1IiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGU1IiA6IHsgInVzZXJDb2RlIiA6ICIyMjExMzcxIiwgInRyYWNlSWQiIDogIkZDRDVGREQ5QkZBNTY5MEZFMDM0QjRBQkVBMkFFMDI0IiwgImRzZCIgOiAiMDAwMDAwMDAwMDAwMDAwMCIsICJwSUQiIDogIjIwNDgiLCAibG9nVGltZSIgOiAiMjAyNC0wNC0wM1QwNzoxNTo0OFoiIH19', 'source': 'manual/3. 쇼라 소개서 (p.22).pdf', 'total_pages': 22, 'page': 2, 'page_label': '3'}
page_content:

----------------------------------------------------------------------------------------------------

PDFPlumberLoader - 3페이지

문자수: 1
metadata: {'source': 'manual/3. 쇼라 소개서 (p.22).pdf', 'file_path': 'manual/3. 쇼라 소개서 (p.22).pdf', 'page': 2, 'total_pages': 22, 'Title': 'PowerPoint 프레젠테이션', 'Author': '하유림 선임', 'CreationDate': "D:20240403161408+09'00'", 'ModDate': "D:20240403161408+09'00'", 'Producer': 'Microsoft® PowerPoint® 2016', 'Creator': 'Microsoft® PowerPoint® 2016', 'Fasoo_Trace_ID': 'eyAibm9kZUNvdW50IjogOSwgIm5vZGUxIiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDAwOjQxOjQxWiIsInBJRCI6MSwidHJhY2VJZCI6IjFEOUNDQUQwRjlDMzREQzJCNDk1NEZBNzNGOTJGQTVFIiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGUyIiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDAxOjE1OjI1WiIsInBJRCI6MSwidHJhY2VJZCI6IjY5RUEyRjgyN0FEODRGMTNCNTA2QjRCRTAxMEVFMjZFIiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGUzIiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDA3OjAyOjUzWiIsInBJRCI6MSwidHJhY2VJZCI6IjM1Qzk1MTBEMzBERDQzQTI5OThEOThFN0MwMzE4RjM3IiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGU0IiA6IHsiZHNkIjoiMDEwMDAwMDAwMDAwMTg5NCIsImxvZ1RpbWUiOiIyMDI0LTA0LTAzVDA3OjA2OjE3WiIsInBJRCI6MSwidHJhY2VJZCI6IjM0MEE3MTA3RTY4RDRCNEI4RjQ2QTAyNzJFMjg5OTk1IiwidXNlckNvZGUiOiIyMjExMzcxIn0sIm5vZGU1IiA6IHsgInVzZXJDb2RlIiA6ICIyMjExMzcxIiwgInRyYWNlSWQiIDogIkZDRDVGREQ5QkZBNTY5MEZFMDM0QjRBQkVBMkFFMDI0IiwgImRzZCIgOiAiMDAwMDAwMDAwMDAwMDAwMCIsICJwSUQiIDogIjIwNDgiLCAibG9nVGltZSIgOiAiMjAyNC0wNC0wM1QwNzoxNTo0OFoiIH19'}
page_content:

----------------------------------------------------------------------------------------------------

PyMuPDFLoader - 3페이지

문자수: 0
metadata: {'producer': 'Microsoft® PowerPoint® 2016', 'creator': 'Microsoft® PowerPoint® 2016', 'creationdate': '2024-04-03T16:14:08+09:00', 'source': 'manual/3. 쇼라 소개서 (p.22).pdf', 'file_path': 'manual/3. 쇼라 소개서 (p.22).pdf', 'total_pages': 22, 'format': 'PDF 1.5', 'title': 'PowerPoint 프레젠테이션', 'author': '하유림 선임', 'subject': '', 'keywords': '', 'moddate': '2024-04-03T16:14:08+09:00', 'trapped': '', 'modDate': "D:20240403161408+09'00'", 'creationDate': "D:20240403161408+09'00'", 'page': 2}
page_content:

----------------------------------------------------------------------------------------------------

PyMuPDF + Markdown - 3페이지

문자수: 0
metadata: {'producer': 'Microsoft® PowerPoint® 2016', 'creator': 'Microsoft® PowerPoint® 2016', 'creationdate': '2024-04-03T16:14:08+09:00', 'source': 'manual/3. 쇼라 소개서 (p.22).pdf', 'file_path': 'manual/3. 쇼라 소개서 (p.22).pdf', 'total_pages': 22, 'format': 'PDF 1.5', 'title': 'PowerPoint 프레젠테이션', 'author': '하유림 선임', 'subject': '', 'keywords': '', 'moddate': '2024-04-03T16:14:08+09:00', 'trapped': '', 'modDate': "D:20240403161408+09'00'", 'creationDate': "D:20240403161408+09'00'", 'page': 2}
page_content:

----------------------------------------------------------------------------------------------------

In [13]:
#4. 광고상품소개서 : 표 생성이 제대로 안됨 / 2~23 -> PDFPlumberLoader 
show_page_content(pdf_path=PDF_LIST[3], page_num=5)

PyPDFLoader - 5페이지

문자수: 429
metadata: {'producer': 'Microsoft® PowerPoint® Microsoft 365용', 'creator': 'Microsoft® PowerPoint® Microsoft 365용', 'creationdate': '2026-08-27T16:53:20+09:00', 'title': 'PowerPoint 프레젠테이션', 'author': 'Hhome', 'moddate': '2026-08-27T16:53:20+09:00', 'source': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'total_pages': 24, 'page': 4, 'page_label': '5'}
page_content: D_월간신상
(추천브랜드)
C_타임딜
영역별 광고 단가 – 현대홈쇼핑탭
노출도가 높은 영역으로 브랜드 마케팅 메시지를 효과적으로 전달할 수 있습니다.
4
구분 상품명 단가 (만원) 노출기간 구좌수(日)
현대
홈쇼핑탭
A_탑배너 (상단) 300만원 1일 2개
A_탑배너 (중단) 150만원 1일 3개
A_탑배너 (하단) 100만원 1일 4개
B_오늘의 메인 행사 180만원 1일 1개
C_타임딜 150만원 1일 1개
D_월간 신상 70만원 1일 3개
E_MD 제안 20만원 1일 2개
F_오늘의 추천 상품 30만원 1일 1개
G_지금 주목할 기획전 (상단) 120만원 1일 1개
G_지금 주목할 기획전 (중단) 100만원 1일 2개
H_믿고 보는 혜택상품 (상단) 100만원 1일 2개
H_믿고 보는 혜택상품 (중단) 50만원 1일 4개
I_오늘특가 2만원 1일 무제한

D_월간신상
(추천브랜드)
C_타임딜
영역별 광고 단가 – 현대홈쇼핑탭
노출도가 높은 영역으로 브랜드 마케팅 메시지를 효과적으로 전달할 수 있습니다.
4
구분 상품명 단가 (만원) 노출기간 구좌수(日)
현대
홈쇼핑탭
A_탑배너 (상단) 300만원 1일 2개
A_탑배너 (중단) 150만원 1일 3개
A_탑배너 (하단) 100만원 1일 4개
B_오늘의 메인 행사 180만원 1일 1개
C_타임딜 150만원 1일 1개
D_월간 신상 70만원 1일 3개
E_MD 제안 20만원 1일 2개
F_오늘의 추천 상품 30만원 1일 1개
G_지금 주목할 기획전 (상단) 120만원 1일 1개
G_지금 주목할 기획전 (중단) 100만원 1일 2개
H_믿고 보는 혜택상품 (상단) 100만원 1일 2개
H_믿고 보는 혜택상품 (중단) 50만원 1일 4개
I_오늘특가 2만원 1일 무제한

----------------------------------------------------------------------------------------------------

PDFPlumberLoader - 5페이지

문자수: 408
metadata: {'source': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'file_path': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'page': 4, 'total_pages': 24, 'Title': 'PowerPoint 프레젠테이션', 'Author': 'Hhome', 'CreationDate': "D:20260827165320+09'00'", 'ModDate': "D:20260827165320+09'00'", 'Producer': 'Microsoft® PowerPoint® Microsoft 365용', 'Creator': 'Microsoft® PowerPoint® Microsoft 365용'}
page_content: 영역별 광고 단가 – 현대홈쇼핑탭
노출도가 높은 영역으로 브랜드 마케팅 메시지를 효과적으로 전달할 수 있습니다.
구분 상품명 단가(만원) 노출기간 구좌수(日)
A_탑배너(상단) 300만원 1일 2개
C_타임딜
A_탑배너(중단) 150만원 1일 3개
A_탑배너(하단) 100만원 1일 4개
B_오늘의메인행사 180만원 1일 1개
C_타임딜 150만원 1일 1개
D_월간신상 70만원 1일 3개
현대
E_MD제안 20만원 1일 2개
홈쇼핑탭
F_오늘의추천상품 30만원 1일 1개
G_지금주목할기획전(상단) 120만원 1일 1개
G_지금주목할기획전(중단) 100만원 1일 2개
D_월간신상
H_믿고보는혜택상품(상단) 100만원 1일 2개
(추천브랜드)
H_믿고보는혜택상품(중단) 50만원 1일 4개
I_오늘특가 2만원 1일 무제한
4

영역별 광고 단가 – 현대홈쇼핑탭
노출도가 높은 영역으로 브랜드 마케팅 메시지를 효과적으로 전달할 수 있습니다.
구분 상품명 단가(만원) 노출기간 구좌수(日)
A_탑배너(상단) 300만원 1일 2개
C_타임딜
A_탑배너(중단) 150만원 1일 3개
A_탑배너(하단) 100만원 1일 4개
B_오늘의메인행사 180만원 1일 1개
C_타임딜 150만원 1일 1개
D_월간신상 70만원 1일 3개
현대
E_MD제안 20만원 1일 2개
홈쇼핑탭
F_오늘의추천상품 30만원 1일 1개
G_지금주목할기획전(상단) 120만원 1일 1개
G_지금주목할기획전(중단) 100만원 1일 2개
D_월간신상
H_믿고보는혜택상품(상단) 100만원 1일 2개
(추천브랜드)
H_믿고보는혜택상품(중단) 50만원 1일 4개
I_오늘특가 2만원 1일 무제한
4

----------------------------------------------------------------------------------------------------

PyMuPDFLoader - 5페이지

문자수: 395
metadata: {'producer': 'Microsoft® PowerPoint® Microsoft 365용', 'creator': 'Microsoft® PowerPoint® Microsoft 365용', 'creationdate': '2026-08-27T16:53:20+09:00', 'source': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'file_path': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'total_pages': 24, 'format': 'PDF 1.7', 'title': 'PowerPoint 프레젠테이션', 'author': 'Hhome', 'subject': '', 'keywords': '', 'moddate': '2026-08-27T16:53:20+09:00', 'trapped': '', 'modDate': "D:20260827165320+09'00'", 'creationDate': "D:20260827165320+09'00'", 'page': 4}
page_content: D_월간신상
(추천브랜드)
C_타임딜
영역별광고단가– 현대홈쇼핑탭
노출도가높은영역으로브랜드마케팅메시지를효과적으로전달할수있습니다.
4
구분
상품명
단가(만원) 노출기간구좌수(日)
현대
홈쇼핑탭
A_탑배너(상단)
300만원
1일
2개
A_탑배너(중단)
150만원
1일
3개
A_탑배너(하단)
100만원
1일
4개
B_오늘의메인행사
180만원
1일
1개
C_타임딜
150만원
1일
1개
D_월간신상
70만원
1일
3개
E_MD 제안
20만원
1일
2개
F_오늘의추천상품
30만원
1일
1개
G_지금주목할기획전(상단)
120만원
1일
1개
G_지금주목할기획전(중단)
100만원
1일
2개
H_믿고보는혜택상품(상단)
100만원
1일
2개
H_믿고보는혜택상품(중단)
50만원
1일
4개
I_오늘특가
2만원
1일
무제한

D_월간신상
(추천브랜드)
C_타임딜
영역별광고단가– 현대홈쇼핑탭
노출도가높은영역으로브랜드마케팅메시지를효과적으로전달할수있습니다.
4
구분
상품명
단가(만원) 노출기간구좌수(日)
현대
홈쇼핑탭
A_탑배너(상단)
300만원
1일
2개
A_탑배너(중단)
150만원
1일
3개
A_탑배너(하단)
100만원
1일
4개
B_오늘의메인행사
180만원
1일
1개
C_타임딜
150만원
1일
1개
D_월간신상
70만원
1일
3개
E_MD 제안
20만원
1일
2개
F_오늘의추천상품
30만원
1일
1개
G_지금주목할기획전(상단)
120만원
1일
1개
G_지금주목할기획전(중단)
100만원
1일
2개
H_믿고보는혜택상품(상단)
100만원
1일
2개
H_믿고보는혜택상품(중단)
50만원
1일
4개
I_오늘특가
2만원
1일
무제한

----------------------------------------------------------------------------------------------------

PyMuPDF + Markdown - 5페이지

문자수: 2576
metadata: {'producer': 'Microsoft® PowerPoint® Microsoft 365용', 'creator': 'Microsoft® PowerPoint® Microsoft 365용', 'creationdate': '2026-08-27T16:53:20+09:00', 'source': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'file_path': 'manual/4. 광고 상품 소개서 (p.24).pdf', 'total_pages': 24, 'format': 'PDF 1.7', 'title': 'PowerPoint 프레젠테이션', 'author': 'Hhome', 'subject': '', 'keywords': '', 'moddate': '2026-08-27T16:53:20+09:00', 'trapped': '', 'modDate': "D:20260827165320+09'00'", 'creationDate': "D:20260827165320+09'00'", 'page': 4}
page_content: D_월간신상
(추천브랜드)
C_타임딜
영역별광고단가– 현대홈쇼핑탭
노출도가높은영역으로브랜드마케팅메시지를효과적으로전달할수있습니다.
4
구분
상품명
단가(만원) 노출기간구좌수(日)
현대
홈쇼핑탭
A_탑배너(상단)
300만원
1일
2개
A_탑배너(중단)
150만원
1일
3개
A_탑배너(하단)
100만원
1일
4개
B_오늘의메인행사
180만원
1일
1개
C_타임딜
150만원
1일
1개
D_월간신상
70만원
1일
3개
E_MD 제안
20만원
1일
2개
F_오늘의추천상품
30만원
1일
1개
G_지금주목할기획전(상단)
120만원
1일
1개
G_지금주목할기획전(중단)
100만원
1일
2개
H_믿고보는혜택상품(상단)
100만원
1일
2개
H_믿고보는혜택상품(중단)
50만원
1일
4개
I_오늘특가
2만원
1일
무제한


|구분<br>A 탑배|상품명 단가<br>너(상단) 3|(만원) 노출기간<br>00만원 1일|
|---|---|---|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|너(중단)<br>1|50만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|너(~~하~~단)<br>1|00만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|의메인~~행~~사<br>1|80만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|딜<br>1|50만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|신상<br><br> 제안<br>|70만원<br>1일<br>0만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|<br><br>의추천상~~품~~<br>|30만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|주~~목할~~기~~획~~전(상단)<br>1|20만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|주~~목할~~기~~획~~전(중단)<br>1<br>~~보는혜~~택상~~품~~(상단)<br>1|00만원<br>1일<br>0만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|~~보는혜~~택상~~품~~(중단)<br>|50만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|가|2만원<br>1일|

D_월간신상
(추천브랜드)
C_타임딜
영역별광고단가– 현대홈쇼핑탭
노출도가높은영역으로브랜드마케팅메시지를효과적으로전달할수있습니다.
4
구분
상품명
단가(만원) 노출기간구좌수(日)
현대
홈쇼핑탭
A_탑배너(상단)
300만원
1일
2개
A_탑배너(중단)
150만원
1일
3개
A_탑배너(하단)
100만원
1일
4개
B_오늘의메인행사
180만원
1일
1개
C_타임딜
150만원
1일
1개
D_월간신상
70만원
1일
3개
E_MD 제안
20만원
1일
2개
F_오늘의추천상품
30만원
1일
1개
G_지금주목할기획전(상단)
120만원
1일
1개
G_지금주목할기획전(중단)
100만원
1일
2개
H_믿고보는혜택상품(상단)
100만원
1일
2개
H_믿고보는혜택상품(중단)
50만원
1일
4개
I_오늘특가
2만원
1일
무제한


|구분<br>A 탑배|상품명 단가<br>너(상단) 3|(만원) 노출기간<br>00만원 1일|
|---|---|---|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|너(중단)<br>1|50만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|너(~~하~~단)<br>1|00만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|의메인~~행~~사<br>1|80만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|딜<br>1|50만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|신상<br><br> 제안<br>|70만원<br>1일<br>0만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|<br><br>의추천상~~품~~<br>|30만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|주~~목할~~기~~획~~전(상단)<br>1|20만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|주~~목할~~기~~획~~전(중단)<br>1<br>~~보는혜~~택상~~품~~(상단)<br>1|00만원<br>1일<br>0만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|~~보는혜~~택상~~품~~(중단)<br>|50만원<br>1일|
|~~**현**~~**대**<br>~~**홈**~~**쇼핑**~~**탭**~~<br>_<br>A_~~탑~~배<br>A_~~탑~~배<br>B_오~~늘~~<br>C_타~~임~~<br>D_월간<br>E_MD<br>F_오~~늘~~<br>G_지~~금~~<br>G_지~~금~~<br>H_믿고<br>H_믿고<br>I_오~~늘특~~|가|2만원<br>1일|

----------------------------------------------------------------------------------------------------

In [ ]:
extract_all_markdown_tables(PDF_LIST[3])

In [ ]:
#5. 협력사시스템 사용설명서 : 아무것도 못읽음 -> 일단 제외
show_page_content(pdf_path=PDF_LIST[4], page_num=3)

In [ ]:
#6. 신규협력사 입점절차 : PyMu + Markdown / 2~21
show_page_content(pdf_path=PDF_LIST[5], page_num=17)

In [ ]:
extract_all_markdown_tables(PDF_LIST[5])

In [ ]:
#7. 데이터영역 광고제안서 : PyMu + Markdown / 2~7
show_page_content(pdf_path=PDF_LIST[6], page_num=6)

In [ ]:
extract_all_markdown_tables(PDF_LIST[6])

In [ ]:
#8. QA 가이드 : PyMu + Markdown / 4~8, 10~15, 17~18, 20~27, 29~34, 36~37
show_page_content(pdf_path=PDF_LIST[7], page_num=37)

In [ ]:
extract_all_markdown_tables(PDF_LIST[7])

In [31]:
import pdfplumber

with pdfplumber.open(PDF_LIST[3]) as pdf:
    tables = pdf.pages[4].extract_tables()
print(len(tables), "개 표")

1 개 표

In [34]:
for row in tables[0][:5]:
    print(" ", [(cell or "")[:20].replace("\n", " ") for cell in row])

  ['구분', '상품명 A_탑배너(상단)', '단가(만원) 노출기간 구 300만원 ', '']
  ['현대 홈쇼핑', 'A_탑배너(중단) A_탑배너(하단) ', '150만원 1일', '']
  ['', '', '100만원 1일', '']
  ['', '', '180만원 1일', '']
  ['', '', '150만원 1일', '']

표 추출 함께 사용하는 경우
page.find_tables()
→ table.bbox
→ 표 영역 text 제외
→ table.extract()

## Chunking

In [12]:
PDF_CONFIGS = {
    "manual/1. 협력사 운영 통합 안내서 (p.23).pdf": "pymupdf_markdown",
    "manual/2. Hmall 소개서 (p.30).pdf": "pdfplumber",
    "manual/4. 광고 상품 소개서 (p.24).pdf": "pdfplumber",
    "manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf": "pymupdf_markdown",
    "manual/7. 데이터 영역 광고 제안서 (p.8).pdf": "pymupdf_markdown",
    "manual/8. QA가이드 (p.21).pdf": "pymupdf_markdown",
}

***TODO : 목차 빼야함

In [13]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

def load_pymupdf_markdown(pdf_path) :
    markdown_PyMuPDFLoader = PyMuPDFLoader(
                                pdf_path,
                                mode="page",
                                extract_tables="markdown"
                            )
    docs = markdown_PyMuPDFLoader.load()
    return docs

def load_pdfplumber(pdf_path) :
    docs = PDFPlumberLoader(pdf_path).load()
    return docs

all_chunks = []
for pdf_idx, pdf_path in enumerate(PDF_LIST):
    pdf_path = str(pdf_path)
    if pdf_path not in PDF_CONFIGS:
        continue

    method = PDF_CONFIGS[pdf_path]
    print(pdf_idx, method)

    # 1. PDF별 로딩
    print(pdf_path)
    if method == "pymupdf_markdown":
        docs = load_pymupdf_markdown(pdf_path)

    elif method == "pdfplumber":
        docs = load_pdfplumber(pdf_path)

    # 2. PDF 특성에 맞게 청킹
    chunks = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=80
    ).split_documents(docs)
    print(len(chunks))

    # 3. metadata 추가
    for chunk in chunks:
        chunk.metadata["source"] = pdf_path.split("manual/", 1)[1]
        chunk.metadata["loader"] = method

    all_chunks.extend(chunks)

0 pymupdf_markdown
manual/1. 협력사 운영 통합 안내서 (p.23).pdf
47
1 pdfplumber
manual/2. Hmall 소개서 (p.30).pdf
30
3 pdfplumber
manual/4. 광고 상품 소개서 (p.24).pdf
28
5 pymupdf_markdown
manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf
25
6 pymupdf_markdown
manual/7. 데이터 영역 광고 제안서 (p.8).pdf
10
7 pymupdf_markdown
manual/8. QA가이드 (p.21).pdf
135

In [ ]:
all_chunks

## Embedding & Vector store

In [14]:
# 벡터스토어별 비교 : 인메모리, 크로마, FAISS, Qdrant

from langchain_chroma import Chroma
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_community.vectorstores import FAISS
from langchain_qdrant import QdrantVectorStore

#chroma.delete_collection()

memory = InMemoryVectorStore.from_documents(all_chunks, embeddings)
chroma = Chroma.from_documents(all_chunks, embeddings, collection_name="hyundaihomeshopping_vendor_manual_chroma")
faiss_store = FAISS.from_documents(all_chunks, embeddings)
qdrant = QdrantVectorStore.from_documents(all_chunks, embeddings, location=":memory:", collection_name="hyundaihomeshopping_vendor_manual_qdrant")
Q = "현대홈쇼핑에 신규 입점하려면 어떻게 해?"

In [15]:
for name, store in [("InMemory", memory), ("Chroma", chroma), ("FAISS", faiss_store), ("Qdrant", qdrant)]:
    hits = store.similarity_search_with_score(Q, k=3)
    print(f"{name:9}", [(d.metadata["source"], d.metadata["page"], round(float(s), 3)) for d, s in hits])

InMemory  [('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 0, 0.655), ('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 1, 0.539), ('1. 협력사 운영 통합 안내서 (p.23).pdf', 9, 0.537)]
Chroma    [('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 0, 0.691), ('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 1, 0.923), ('1. 협력사 운영 통합 안내서 (p.23).pdf', 9, 0.926)]
FAISS     [('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 0, 0.691), ('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 1, 0.923), ('1. 협력사 운영 통합 안내서 (p.23).pdf', 9, 0.926)]
Qdrant    [('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 0, 0.655), ('6. 신규 협력사 입점 절차 안내 (p.21).pdf', 1, 0.539), ('1. 협력사 운영 통합 안내서 (p.23).pdf', 9, 0.537)]

## Naive RAG

In [16]:
retriever = faiss_store.as_retriever(search_kwargs={"k":3})
context = retriever.invoke(Q)
for doc in context:
    print(doc.metadata["page"], doc.page_content[:100].replace("\n", " "))

0 신규협력사 입점절차안내 현대홈쇼핑
1 가입여부확인및기초가입하기 현대홈쇼핑입점프로세스 신규협력사의신상품제안프로세스는, 협력사시스템의[ 신규입점제안] 메뉴를통해이루어집니다. !
9 5. 신규입점 ○신규입점은파트너시스템에서진행됩니다.신규입점매뉴얼을참고해주세요. Hmall홈페이지최하단[신규입점] 탭에서도절차확인이가능합니다. 입점ID/PW 확인 전자계약서등록및작성

In [17]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

answer_prompt = ChatPromptTemplate.from_messages([
    ("system", "근거만으로 답한다. 근거에 없으면 '문서에 없음' 이라고 답한다."),
    ("human", "근거\n{context}\n\n질문\n{question}"),
])
answers = answer_prompt | ChatOpenAI(model=MODEL) | StrOutputParser()
answer = answers.invoke({
    "context": context,
    "question": Q
})
print(answer)

문서에 따르면, 현대홈쇼핑 신규 입점은 **파트너/협력사 시스템의 `[신규입점제안]` 메뉴**를 통해 진행됩니다.

절차:
1. **파트너시스템 접속**
2. **입점 ID/PW 확인**
3. **`[신규입점제안]` 클릭**
4. **협력사 정보 입력**
5. **상품 제안 및 결과 확인**
6. **전자계약서 등록 및 작성**

추가로 문서에는
- **신규입점 매뉴얼 참고**
- **Hmall 홈페이지 최하단 `[신규입점]` 탭에서도 절차 확인 가능**
하다고 되어 있습니다.

## golden dataset

In [33]:
TARGET = {"단일홉": 6, "멀티홉": 4, "집계": 3, "조건" : 2, "절차" : 2,  "무답변": 3}
OVERSAMPLE = 2  # 검수에서 절반 가까이 떨어진다. 처음부터 넉넉히 만든다 (2배 정도로 미리 만든다)
print(sum(TARGET.values()), "문항 목표")

20 문항 목표

In [34]:
import numpy as np

V = np.array(embeddings.embed_documents([c.page_content for c in all_chunks]))
print(V.shape)

(275, 1536)

In [35]:
def having_all(*words, n):
    return [c for c in all_chunks if all(w in c.page_content for w in words)][:n]

def having_any(*words, n):
    return [c for c in all_chunks if any(w in c.page_content for w in words)][:n]

step = max(1, len(all_chunks) // (TARGET["단일홉"] * OVERSAMPLE))
single = all_chunks[::step][:TARGET["단일홉"] * OVERSAMPLE]
counting = having_all("①", "②", n=TARGET["집계"] * (OVERSAMPLE+1))
condition = having_any("위해", "구분", n=TARGET["조건"] * (OVERSAMPLE+2))
step = having_any("프로세스", "단계", n=TARGET["절차"] * OVERSAMPLE)
print({"단일홉": len(single), "집계": len(counting), "조건": len(condition), "절차": len(step)})

{'단일홉': 12, '집계': 9, '조건': 8, '절차': 4}

In [36]:
pairs = []
for i in range(0, len(all_chunks), max(1, len(all_chunks) // (TARGET["멀티홉"] * OVERSAMPLE))):
    order = np.argsort(-(V @ V[i]))
    j = next(
        (
            int(k)
            for k in order[1:275]
            if (
                all_chunks[int(k)].metadata["source"]
                != all_chunks[i].metadata["source"]
                or
                all_chunks[int(k)].metadata["page"]
                != all_chunks[i].metadata["page"]
            )
        ),
        None
    )
    if j is not None:
        pairs.append((all_chunks[i], all_chunks[j]))
pairs = pairs[:TARGET["멀티홉"] * OVERSAMPLE]
print(len(pairs), "쌍", [(a.metadata["page"], b.metadata["page"]) for a, b in pairs[:3]])

8 쌍 [(0, 34), (19, 20), (21, 18)]

In [37]:
from langchain_core.prompts import ChatPromptTemplate
from typing import Literal
from pydantic import BaseModel, Field

# todo : draft에 필요한 항목들
class Draft(BaseModel):
    question: str = Field(description="질문만 읽어도 무엇을 묻는지 특정되어야 한다. 지시대명사를 쓰지 않는다")
    answer: str
    quote: str = Field(description="근거에서 그대로 복사한 한 문장. 요약하거나 고치지 않는다")
    difficulty: Literal["easy", "medium", "hard"]

writer = ChatPromptTemplate.from_messages([
    ("system", "현대홈쇼핑 협력사용 가이드 문서를 근거로 질문과 답을 만든다. 근거에 없는 사실을 쓰지 않는다.\n{guide}"),
    ("human", "근거\n{context}"),
]) | ChatOpenAI(model=MODEL).with_structured_output(Draft)

In [38]:
GUIDES = {
    "단일홉": "근거 한 곳만 보면 답할 수 있는 질문을 만든다.",
    "멀티홉": "두 근거를 모두 봐야 답할 수 있는 질문을 만든다. 한쪽만 보면 답이 나오지 않아야 한다.",
    "집계": "근거에 열거된 항목이 몇 개인지 세거나 나열하는 질문을 만든다. 답에는 개수와 목록을 함께 쓴다.",
    "조건": "무엇을 하기 위해 필요한 것을 물어보는 질문을 만든다. 혹은 구분되는 분류 항목들에 따른 서로 다른 조건을 물어보는 질문을 만든다.",
    "절차": "무엇을 진행하기 위해 필요한 절차를 물어보는 질문을 만든다. 답은 단계별로 정해진 순서대로 쓴다.",
}

In [39]:
jobs = ([("단일홉", [c]) for c in single] + [("멀티홉", list(p)) for p in pairs]
        + [("집계", [c]) for c in counting] + [("조건", [c]) for c in condition]
        + [("절차", [c]) for c in step])
print(len(jobs), "건")

41 건

In [40]:
drafts = writer.batch([{"guide": GUIDES[t], "context": "\n\n".join(c.page_content for c in cs)}
                       for t, cs in jobs], config={"callbacks": [usage]})
print(len(drafts), "초안")

41 초안

In [41]:
for d in drafts :
    print (d)

question='현대홈쇼핑 협력사운영통합안내서의 기준 일자는 언제인가요?' answer='2024.06입니다.' quote='2024.06' difficulty='easy'
question='주말과 공휴일은 출고기준일 산정에 포함되는가?' answer='주말과 공휴일은 출고기준일 산정에 포함되지 않는다.' quote='○주말/공휴일은출고기준일산정에미포함' difficulty='easy'
question='신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자 연락처는 무엇인가요?' answer='yunsh_@hyundaihmall.com' quote='▷담당자연락처yunsh_@hyundaihmall.com' difficulty='easy'
question='플랫폼행사는 Hmall의 어느 영역에 노출되는가?' answer='플랫폼행사는 Hmall의 PC · 모바일 메인영역에 노출된다.' quote='플랫폼행사는Hmall의PC · 모바일메인영역에노출됩니다.' difficulty='easy'
question='검색 광고에서 A_검색창문구의 1일 단가는 얼마인가요?' answer='180만원입니다.' quote='검색창 A_검색창문구 1개 180만원 1일 1개' difficulty='easy'
question='신상품 제안서 심사 결과 확인까지 영업일 기준으로 어느 정도 소요됩니까?' answer='영업일 기준 5일 정도 소요됩니다.' quote='제안서심사결과는영업일기준5일정도소요됩니다.' difficulty='easy'
question='카탈로그 의류만 판매했을 때 2024년 매출액은 얼마인가?' answer='100억' quote='‘24년매출액\n(카탈로그의류만판매)\n100억' difficulty='easy'
question='당도를 소구하는 경우 브릭스측정자료로 추가 제출해야 하는 자료는 무엇인가요?' answer='자동당도선별기관련 사진 또는 동영상 자료를 전달해야 합니다.' quote='자동당도선별기관련사진/동영상자료전달' difficulty='easy'
question="표시광고에서 '500달톤이하' 또는 '글루타치온성분% 함유' 문구를 사용하려면 어떤 증빙자료를 제출해야 하나요?" answer='증빙 가능한 국내 공인기관 성적서를 제출해야 합니다.' quote="- '500달톤이하', '글루타치온성분% 함유' 등증빙가능한국내공인기관성적서제출" difficulty='easy'
question='가이드라인 내 제시사항에 대해 상품에 따라 추가 준수사항이 있을 수 있는지 알려주세요.' answer='가이드라인 내 제시사항은 기본적인 사항이므로, 상품에 따라 추가 준수사항이 있을 수 있습니다.' quote='가이드라인內제시사항은기본적인사항으로, 상품에따라추가준수사항이있을수있습니다.' difficulty='easy'
question='세탁제품의 내세탁성 시험에서 물세탁 치수변화율 기준은 얼마인가?' answer='물세탁 치수변화율 기준은 ±3%이다.' quote='* 치수변화율 : 물세탁: ±3% /  드 라이: ±2%' difficulty='easy'
question='린넨 소재로 소구하려면 혼용률 세부감별 결과에서 무엇을 확인해야 하나요?' answer='혼용률 세부감별 결과에서 ‘아마’를 확인해야 합니다.' quote='* 린넨: 마세부감별결과‘아마’ 확인' difficulty='easy'
question='현대홈쇼핑 협력사 운영 통합 안내서 2024.06 기준으로, 문서의 3장 제목과 그 아래 협력사 지원 관련 소제목을 함께 쓰면 무엇인가?' answer="3장 제목은 '현대홈쇼핑품질연구소'이고, 그 아래 협력사 지원 관련 소제목은 '협력사주요지원제도'이다." quote='3. 현대홈쇼핑품질연구소' difficulty='easy'
question='개인사업자가 신규 입점한 뒤 역발행 방식으로 세금계산서를 처리할 때, 상품대금 부가세를 받기 위해 매월 언제까지 인증해야 하며, 신규 입점 시 통장 사본에는 어떤 이름 표시가 필수인가?' answer='개인사업자가 역발행 세금계산서로 상품대금 부가세를 받으려면 매월 1~10일에 세금계산서 인증이 필요하며, 신규 입점 시 제출하는 통장 사본에는 당사 협력사 현황표에 기재된 사업자명 표시가 필수입니다.' quote='협력사 ‘매월1~10일’세금계산서인증필요' difficulty='medium'
question='Hmall에서 입점 브랜드와 상품을 제휴사까지 포함해 홍보·판매할 수 있는 수단과, 담당 MD와 협의해 참여할 때 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사는 무엇인가요?' answer='입점 브랜드와 상품은 APP PUSH, 포털·리타겟팅 광고, 가격비교 사이트와 같은 내·외부 수단으로 홍보할 수 있고, 카드사 쇼핑몰·통신사 멤버십몰 등 20개 이상의 제휴사에도 연동되어 판매됩니다. 또한 담당 MD와 협의해 참여할 수 있으며 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사로는 페어, 브랜드줌, 올-인데이, 릴레이푸드, 불금데이, 스마일테스터가 있습니다.' quote='Hmall 마케팅 부서는 APP PUSH, 포털 · 리타겟팅 광고, 가격 비교 사이트 등 다양한 내 · 외부 수단을 통해 입점 브랜드 및 상품을 홍보하고 있습니다.' difficulty='medium'
question='쇼라생방 D-10부터 진행해야 하면서 연관검색(1주)이 포함되고, 평일·주말 모두 가능하다고 명시된 패키지 중 쇼라PICK(1일)까지 포함된 상품의 금액은 얼마인가?' answer='100만원' quote='라방플러스패키지B 100만원 신청가능 · 신한PLAY 앱내‘라방플러스알림’신청배너.연관검색(1주), 쇼라PICK (1일)\n평일O/ 주말O' difficulty='medium'
question='PSD 가이드파일이 공유되고 수정 가능한 항목이 이미지, 소구포인트, 상품명, 가격, 상품코드, 간편번호로 안내된 형식과, 레이아웃이 자유형식이지만 제작 전 이미지 내 기재 텍스트 내용을 사전협의해야 하는 형식의 공통 파일포맷과 소재전달일은 무엇인가?' answer='공통 파일포맷은 이미지 JPG, PNG이고, 소재전달일은 노출일 기준 7일 전이다.' quote='파일포맷|이미지JPG, PNG' difficulty='medium'
question='분말류 또는 환제품에 수입산 특이원료를 사용하는 경우, 금속성이물성적서의 인정 기간과 원물추적성자료 제출 범위를 함께 설명하시오.' answer='금속성이물성적서는 분말류/환제품에 해당하며 공인기관 성적서로 6개월 이내여야 한다. 또한 수입산 특이원료의 경우 최초취급자부터 상품제조사까지 들어가는 유통간 모든 거래명세서를 제출해야 한다.' quote='- 분말류/환제품해당(공인기관성적서, 6개월이내)' difficulty='medium'
question='섬유 상품과 식품의 QA 제출 항목을 함께 고려할 때, 포장 관련 금지사항과 함께 공인기관 성적서로 제출해야 하는 포장 관련 서류는 각각 무엇인가?' answer="섬유 상품 준비서류에서는 샘플 포장 시 종이 무지테이프는 사용할 수 있고, 식품 QA 기본서류에서는 '개봉후반품불가' 테이프 사용이 금지된다. 또한 식품 성적서 항목에서는 제품이 닿는 내면 포장재질에 대한 공인기관 포장지 성적서를 제출해야 한다." quote="- '개봉후반품불가' 테이프사용금지" difficulty='medium'
question='린넨 소재를 단독으로 소구하려면 어떤 세부감별 결과가 확인되어야 하고, 혼용률 기준상 어떤 함량 조건을 함께 충족해야 하는가?' answer='린넨 소재를 단독으로 소구하려면 혼용률 세부감별에서 마의 세부감별 결과가 ‘아마’로 확인되어야 하며, 혼용률 기준상 천연섬유 단독소구 조건에 따라 마 함량이 100%여야 한다.' quote='* 린넨: 마세부감별결과‘아마’ 확인' difficulty='medium'
question='근거에 제시된 방송상품 QA 프로세스 단계는 모두 몇 개인가요? 단계 번호와 명칭을 함께 나열해주세요.' answer='방송상품 QA 프로세스 단계는 8개입니다. ① QA 의뢰, ② QA 자료업로드, ③ QA 검토, ④ 합격/ 불합격, ⑤ 방송진행, ⑥ 사후관리, ⑦ 검사, ⑧ 합격/ 불합격입니다.' quote='①QA 의뢰' difficulty='easy'
question='단계별 QA 종류는 총 몇 가지이며, 각 종류의 명칭은 무엇인가요?' answer='단계별 QA 종류는 총 3가지입니다. 목록은 사전QA, 현장QA, 입고QA입니다.' quote='사전QA' difficulty='easy'
question='근거에서 파일별 진행상태는 몇 가지로 안내되며, 각 진행상태 항목은 무엇인가요?' answer='파일별 진행상태는 4가지입니다. 미등록, 등록, 수정요청, 승인완료입니다.' quote='②파일별진행상태확인이가능합니다.\n(미등록/ 등록/ 수정요청/ 승인완료)' difficulty='easy'
question='현대홈쇼핑 배송은 몇 가지 형태로 구분 운영되며, 배송형태안내에 나온 항목은 무엇인가?' answer='현대홈쇼핑 배송은 4가지 형태로 구분 운영됩니다. 목록은 ①센터배송, ②현대홈직택배, ③협력사직택배, ④협력사직송입니다.' quote='○현대홈쇼핑배송은4가지형태로구분운영됩니다.' difficulty='easy'
question='물류및배송의 배송형태별프로세스에는 몇 가지 배송형태가 나오며, 배송형태 이름은 무엇인가?' answer='3가지입니다. 센터배송, 현대홈직택배/협력사직택배, 협력사직송입니다.' quote='○배송형태별프로세스' difficulty='easy'
question='전자계약서 서명 시 해당 계약서에 첨부하는 항목은 몇 가지이며, 항목 목록은 무엇입니까?' answer='총 3가지입니다. 목록은 ① 보증보험 ② 통장사본 ③ 사업자등록증 입니다.' quote='①보증보험 ②통장사본 ③사업자등록증 을해당계약서에첨부하고 기업범용공인인증서 ( 사업자용) 로서명합니다.' difficulty='easy'
question='표준거래계약서에 첨부하는 제출서류는 몇 종이며, 어떤 서류를 차례로 업로드해야 하나요?' answer='제출서류는 3종입니다. 목록은 ① 보증보험 ② 통장사본 ③ 사업자등록증입니다.' quote='-표준거래계약서에제출서류(3종)을차례로업로드후, 양사가서명을하면계약체결이됩니다.' difficulty='easy'
question='협력사시스템(HELP 시스템)에서 QA자료관리 화면(화면번호 VD036)에 접속하는 경로에는 몇 개의 단계가 나열되어 있나요? 단계 이름을 모두 쓰세요.' answer='3개입니다. ① 메뉴클릭, ② 상품승인, ③ QA진행List입니다.' quote='접속경로: ①메뉴클릭→ ②상품승인→ ③QA진행List' difficulty='easy'
question='식품유형별/방송소구점 관련 세부 필요서류와 가이드 항목은 총 몇 개인가? 각 항목의 제목을 모두 나열하라.' answer='총 7개이다. 항목은 ① 크릴오일, 아르간오일, 복분자종자유 등 식용유지류, ② 500달톤, 300달톤 이하 저분자콜라겐, ③ 농산물/축산물 등의 품종 관련 소구, ④ 특허증, ⑤ 무첨가 관련 표현, ⑥ 원물 투입 후 추출 관련 표현, ⑦ NFC 주스(정제수 없이 통째로 착즙)이다.' quote='⑦NFC 주스(정제수없이통째로착즙):' difficulty='easy'
question='주문번호가 있는 주문, 교환, AS, 반품, 배송비 문의를 접수하려면 어느 화면이 필요한가요?' answer='협력사 Ref 접수(VD401) 화면에서 접수해야 합니다.' quote='○주문, 교환, AS, 반품, 배송비등주문번호가있는문의 :협력사Ref 접수(VD401)화면에서접수' difficulty='easy'
question='방송상품 판매 전에 품질 적합성과 리스크 확인을 위해 진행하는 절차는 무엇인가요, 그리고 Hmall 상품은 같은 절차를 따르나요?' answer='방송상품 판매 전에는 QA를 진행합니다. 방송상품 QA 프로세스는 QA 의뢰, QA 자료 업로드, QA 검토, 합격/불합격, 방송 진행, 사후관리, 검사, 합격/불합격 순서로 안내되어 있습니다. Hmall 상품은 별도의 프로세스를 따르며, 등록된 웹기술서를 토대로 QA(심의)를 진행합니다.' quote='※ Hmall상품은별도의프로세스를따릅니다. 등록된웹기술서를토대로QA(심의)를진행합니다.' difficulty='easy'
question='방송일 기준 최소 10일 전에 의뢰해야 하는 QA 종류와 해당 QA에서 점검하는 업무 항목은 무엇인가요?' answer='방송일 기준 최소 10일 전에 의뢰해야 하는 QA 종류는 현장QA입니다. 현장QA에서는 제조사 위생점검, 원료 및 자재 관리 점검, 품질표시정보 확인, 완제품 규격 및 포장상태 점검, 외관불량 및 구성품 혼입 점검 등을 수행합니다.' quote='현장QA 제조사, 물류센터방문을통한완제품의진정성을확인 기준일 의뢰: 방송일기준최소10일전의뢰/ 완료: 방송일기준최소4일전완료 업무 제조사위생점검및원료및자재관리점검, 품질표시정보확인, 완제품규격및포장상태점검, 외관불량및구성품혼입점검등' difficulty='easy'
question='사전QA를 진행하려면 방송일 기준으로 의뢰 완료는 각각 언제까지 해야 하나요?' answer='사전QA는 방송일 기준 최소 14일 전에 의뢰해야 하고, 최소 4일 전에 완료해야 합니다.' quote='의뢰: 방송일기준최소14일전의뢰/ 완료: 방송일기준최소4일전완료' difficulty='easy'
question='협력사가 고객정보를 받아 직접 출고와 회수를 처리하려면 어떤 배송형태를 선택해야 합니까?' answer='협력사가 고객정보를 제공받아 직접 출고와 회수를 처리하려면 협력사직송을 선택해야 합니다.' quote='④협력사직송 고객정보를제공하여협력사가직접 출고/회수합니다.' difficulty='easy'
question='토요일에도 출고하려는 협력사가 추가로 등록해야 하는 항목은 무엇인가?' answer='SCM 담당자를 통해 토요일 휴무 제외 등록이 필요하다.' quote='※토요일출고희망협력사: SCM 담당자통해토요일휴무제외등록' difficulty='easy'
question='일반상품 또는 일반식품의 방송 시간과 출고 기준일에 따라 방송 당일, 방송 +1일, 방송 +2일, 방송 +3일 출고 비율은 각각 어떻게 다른가요?' answer='일반상품 또는 일반식품의 출고 비율은 방송 시간과 출고 기준일에 따라 다릅니다. 출고 기준일이 1일인 경우, 주간 방송은 방송 당일 60%, 방송 +1일 40%이며, 야간 방송은 방송 +1일 100%입니다. 출고 기준일이 2일인 경우, 주간 방송은 방송 당일 60%, 방송 +1일 30%, 방송 +2일 10%이고, 야간 방송은 방송 +1일 90%, 방송 +2일 10%입니다. 출고 기준일이 3일인 경우, 주간 방송은 방송 당일 60%, 방송 +1일 20%, 방송 +2일 10%, 방송 +3일 10%이며, 야간 방송은 방송 +1일 80%, 방송 +2일 10%, 방송 +3일 10%입니다.' quote='|**일반상품/**<br>**일반식품**|**3일**|**야간**|**-**|**80%**|**10%**|**10%**|' difficulty='medium'
question='신규 입점 시 개인사업자가 추가로 제출해야 하는 서류는 무엇인가요?' answer='개인사업자는 사업자등록증 외에 주민등록등본(원본)과 신분증 사본이 필요합니다.' quote='※ 개인사업자의경우주민등록등본(원본), 신분증사본' difficulty='easy'
question='현대홈쇼핑 협력사 가이드에서 신규 입점을 진행하기 위해 따라야 하는 절차는 무엇인가요?' answer='1. 현대홈쇼핑 온라인몰 Hmall 또는 기업 홈페이지로 이동합니다.\n2. 협력사용 가이드의 목차에서 신규입점 항목을 확인합니다.\n3. 신규입점 관련 안내에 따라 입점 절차를 진행합니다.\n4. 진행 중 필요한 내용은 업무문의(담당자/1:1문의) 항목을 통해 확인합니다.' quote='5. 신규입점' difficulty='easy'
question='방송운영으로 상품을 판매하기 위해 필요한 절차를 순서대로 알려주세요.' answer='방송운영으로 상품을 판매하기 위한 절차는 다음 순서입니다.\n1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.\n2. 상품평가및입점: MD가 상품을 검토한 후 최종 입점을 결정합니다.\n3. 상품등록: 상품정보를 입력합니다.\n4. QA: 현장 및 사전 QA를 진행합니다.\n5. 방송편성: 상품군과 목표 등을 고려하여 방송시간을 편성합니다.\n6. 심의: 영상 및 자막에 대한 심의 검토를 진행합니다.\n7. 사전전략회의: 상품 특장점 및 소구 포인트 등 방송 진행 방향을 논의합니다.\n8. 방송판매: Live 방송을 진행합니다.\n9. 사후전략회의: 방송 실적을 분석하고 개선점을 공유하며 차후 운영 방향을 협의합니다.\n10. 배송: 출고 및 배송을 체크합니다.\n11. CS: 고객불만을 접수하고 처리합니다.\n12. 정산: 대금을 지급합니다.' quote='협력사가파트너시스템을통해신상품제안' difficulty='easy'
question='신상품을 제안한 뒤 방송판매와 정산까지 진행하기 위해 필요한 절차를 순서대로 알려주세요.' answer='1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.\n2. 상품평가및입점: MD가 상품을 검토한 후 최종 입점을 결정합니다.\n3. 상품등록: 상품정보를 입력합니다.\n4. QA: 현장 및 사전 QA를 진행합니다.\n5. 방송편성: 상품군과 목표 등을 고려하여 방송시간을 편성합니다.\n6. 심의: 영상 및 자막에 대한 심의 검토를 진행합니다.\n7. 사전전략회의: 상품 특장점 및 소구 포인트 등 방송 진행 방향을 논의합니다.\n8. 방송판매: Live 방송을 진행합니다.\n9. 사후전략회의: 방송 실적을 분석하고 개선점을 공유하며 차후 운영 방향을 협의합니다.\n10. 배송: 출고 및 배송을 체크합니다.\n11. CS: 고객불만을 접수하고 처리합니다.\n12. 정산: 대금을 지급합니다.' quote='**협력사가파트너시스템을통해신상품제안**' difficulty='easy'
question='신상품을 Hmall에 판매하기 위해 어떤 절차를 순서대로 진행해야 하나요?' answer='1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.\n2. 상품평가및입점: MD가 상품을 검토한 후 최종 입점 여부를 결정합니다.\n3. 상품등록: 상품정보를 입력합니다.\n4. QA/심의: 웹기술서 심의를 진행합니다.\n5. 프로모션: 상품 및 행사에 맞는 쿠폰, 적립, 무이자 등 판촉을 협의합니다.\n6. 광고: 상품 및 행사에 맞는 배너, 탭, 팝업 등 광고를 협의합니다.\n7. 링크/DB 제휴: 가격비교사이트 및 타쇼핑몰 노출을 협의합니다.\n8. 판매: Hmall에 노출합니다.\n9. 사후관리: 실적을 분석하고 행사 및 기획전을 리뷰합니다.\n10. 배송: 출고 및 배송을 체크합니다.\n11. CS: 고객불만을 접수하고 처리합니다.\n12. 정산: 대금을 지급합니다.' quote='**협력사가파트너시스템을통해신상품제안**' difficulty='easy'

In [42]:
# 검수1. 인용 확인 (짧은 인용 제거)
def squash(s):
    return "".join(s.split())

stage1, dropped = [], []
for (kind, cs), d in zip(jobs, drafts):
    source = squash("\n".join(c.page_content for c in cs))
    if len(squash(d.quote)) > 10 and squash(d.quote) in source:
        stage1.append((kind, cs, d))
    else:
        dropped.append((kind, "인용 불일치", d.question, d.quote, d.answer))
print(f"통과 {len(stage1)}  탈락 {len(dropped)}")

for row in dropped:
    print("  ", row)

통과 35  탈락 6
   ('단일홉', '인용 불일치', '현대홈쇼핑 협력사운영통합안내서의 기준 일자는 언제인가요?', '2024.06', '2024.06입니다.')
   ('단일홉', '인용 불일치', '린넨 소재로 소구하려면 혼용률 세부감별 결과에서 무엇을 확인해야 하나요?', '* 린넨: 마세부감별결과‘아마’ 확인', '혼용률 세부감별 결과에서 ‘아마’를 확인해야 합니다.')
   ('집계', '인용 불일치', '근거에 제시된 방송상품 QA 프로세스 단계는 모두 몇 개인가요? 단계 번호와 명칭을 함께 나열해주세요.', '①QA 의뢰', '방송상품 QA 프로세스 단계는 8개입니다. ① QA 의뢰, ② QA 자료업로드, ③ QA 검토, ④ 합격/ 불합격, ⑤ 방송진행, ⑥ 사후관리, ⑦ 검사, ⑧ 합격/ 불합격입니다.')
   ('집계', '인용 불일치', '단계별 QA 종류는 총 몇 가지이며, 각 종류의 명칭은 무엇인가요?', '사전QA', '단계별 QA 종류는 총 3가지입니다. 목록은 사전QA, 현장QA, 입고QA입니다.')
   ('집계', '인용 불일치', '물류및배송의 배송형태별프로세스에는 몇 가지 배송형태가 나오며, 배송형태 이름은 무엇인가?', '○배송형태별프로세스', '3가지입니다. 센터배송, 현대홈직택배/협력사직택배, 협력사직송입니다.')
   ('절차', '인용 불일치', '현대홈쇼핑 협력사 가이드에서 신규 입점을 진행하기 위해 따라야 하는 절차는 무엇인가요?', '5. 신규입점', '1. 현대홈쇼핑 온라인몰 Hmall 또는 기업 홈페이지로 이동합니다.\n2. 협력사용 가이드의 목차에서 신규입점 항목을 확인합니다.\n3. 신규입점 관련 안내에 따라 입점 절차를 진행합니다.\n4. 진행 중 필요한 내용은 업무문의(담당자/1:1문의) 항목을 통해 확인합니다.')

In [43]:
# 검수2. 자기완결성
class SelfContained(BaseModel):
    ok: bool = Field(description="질문만 읽고 무엇을 묻는지 특정되면 True")
    reason: str


checker = ChatPromptTemplate.from_messages([
    ("system", "현대홈쇼핑 협력사용 가이드 문서에 대한 질문이다. 이 질문을 문서 전체를 아는 사람에게 "
               "단독으로 던졌을 때 무엇을 묻는지 특정되는지 판단한다. "
               "주어나 대상이 빠져 있거나 '이 경우' 같은 지시대명사에 기대면 False 다."),
    ("human", "{question}"),
]) | ChatOpenAI(model=JUDGE).with_structured_output(SelfContained)

In [44]:
verdicts = checker.batch([{"question": d.question} for _, _, d in stage1], config={"callbacks": [usage]})
print(f"판정 {len(verdicts)}건 중 통과 {sum(v.ok for v in verdicts)}건")

판정 35건 중 통과 34건

In [45]:
stage2 = []
for (kind, cs, d), v in zip(stage1, verdicts):
    if v.ok:
        stage2.append((kind, cs, d))
    else:
        dropped.append((kind, "자기완결성 없음", d.question))
        print("  탈락", d.question, "|", v.reason)
print(f"통과 {len(stage2)}")

  탈락 카탈로그 의류만 판매했을 때 2024년 매출액은 얼마인가? | 질문에 매출액을 산정할 주체나 기준(어느 협력사/사례의 판매액인지, 어떤 표나 계산 조건을 적용하는지)이 명시되어 있지 않습니다. ‘카탈로그 의류만 판매’라는 조건만으로 2024년 매출액이 특정되지 않습니다.
통과 34

In [47]:
# 수동검수
for i, (kind, cs, d) in enumerate(stage2):
    print(f"{i:2d} [{kind}] {d.question}")
    print(f"     답 {d.answer}")
    print(f"     근거 doc.{sorted({c.metadata['source'] for c in cs})} p.{sorted({c.metadata['page']+1 for c in cs})}  {d.quote[:55]}")

 0 [단일홉] 주말과 공휴일은 출고기준일 산정에 포함되는가?
     답 주말과 공휴일은 출고기준일 산정에 포함되지 않는다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[16]  ○주말/공휴일은출고기준일산정에미포함
 1 [단일홉] 신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자 연락처는 무엇인가요?
     답 yunsh_@hyundaihmall.com
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[22]  ▷담당자연락처yunsh_@hyundaihmall.com
 2 [단일홉] 플랫폼행사는 Hmall의 어느 영역에 노출되는가?
     답 플랫폼행사는 Hmall의 PC · 모바일 메인영역에 노출된다.
     근거 doc.['2. Hmall 소개서 (p.30).pdf'] p.[20]  플랫폼행사는Hmall의PC · 모바일메인영역에노출됩니다.
 3 [단일홉] 검색 광고에서 A_검색창문구의 1일 단가는 얼마인가요?
     답 180만원입니다.
     근거 doc.['4. 광고 상품 소개서 (p.24).pdf'] p.[12]  검색창 A_검색창문구 1개 180만원 1일 1개
 4 [단일홉] 신상품 제안서 심사 결과 확인까지 영업일 기준으로 어느 정도 소요됩니까?
     답 영업일 기준 5일 정도 소요됩니다.
     근거 doc.['6. 신규 협력사 입점 절차 안내 (p.21).pdf'] p.[6]  제안서심사결과는영업일기준5일정도소요됩니다.
 5 [단일홉] 당도를 소구하는 경우 브릭스측정자료로 추가 제출해야 하는 자료는 무엇인가요?
     답 자동당도선별기관련 사진 또는 동영상 자료를 전달해야 합니다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[10]  자동당도선별기관련사진/동영상자료전달
 6 [단일홉] 표시광고에서 '500달톤이하' 또는 '글루타치온성분% 함유' 문구를 사용하려면 어떤 증빙자료를 제출해야 하나요?
     답 증빙 가능한 국내 공인기관 성적서를 제출해야 합니다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[13]  - '500달톤이하', '글루타치온성분% 함유' 등증빙가능한국내공인기관성적서제출
 7 [단일홉] 가이드라인 내 제시사항에 대해 상품에 따라 추가 준수사항이 있을 수 있는지 알려주세요.
     답 가이드라인 내 제시사항은 기본적인 사항이므로, 상품에 따라 추가 준수사항이 있을 수 있습니다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[18]  가이드라인內제시사항은기본적인사항으로, 상품에따라추가준수사항이있을수있습니다.
 8 [단일홉] 세탁제품의 내세탁성 시험에서 물세탁 치수변화율 기준은 얼마인가?
     답 물세탁 치수변화율 기준은 ±3%이다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[23]  * 치수변화율 : 물세탁: ±3% /  드 라이: ±2%
 9 [멀티홉] 현대홈쇼핑 협력사 운영 통합 안내서 2024.06 기준으로, 문서의 3장 제목과 그 아래 협력사 지원 관련 소제목을 함께 쓰면 무엇인가?
     답 3장 제목은 '현대홈쇼핑품질연구소'이고, 그 아래 협력사 지원 관련 소제목은 '협력사주요지원제도'이다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf', '8. QA가이드 (p.21).pdf'] p.[1, 35]  3. 현대홈쇼핑품질연구소
10 [멀티홉] 개인사업자가 신규 입점한 뒤 역발행 방식으로 세금계산서를 처리할 때, 상품대금 부가세를 받기 위해 매월 언제까지 인증해야 하며, 신규 입점 시 통장 사본에는 어떤 이름 표시가 필수인가?
     답 개인사업자가 역발행 세금계산서로 상품대금 부가세를 받으려면 매월 1~10일에 세금계산서 인증이 필요하며, 신규 입점 시 제출하는 통장 사본에는 당사 협력사 현황표에 기재된 사업자명 표시가 필수입니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[20, 21]  협력사 ‘매월1~10일’세금계산서인증필요
11 [멀티홉] Hmall에서 입점 브랜드와 상품을 제휴사까지 포함해 홍보·판매할 수 있는 수단과, 담당 MD와 협의해 참여할 때 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사는 무엇인가요?
     답 입점 브랜드와 상품은 APP PUSH, 포털·리타겟팅 광고, 가격비교 사이트와 같은 내·외부 수단으로 홍보할 수 있고, 카드사 쇼핑몰·통신사 멤버십몰 등 20개 이상의 제휴사에도 연동되어 판매됩니다. 또한 담당 MD와 협의해 참여할 수 있으며 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사로는 페어, 브랜드줌, 올-인데이, 릴레이푸드, 불금데이, 스마일테스터가 있습니다.
     근거 doc.['2. Hmall 소개서 (p.30).pdf'] p.[19, 22]  Hmall 마케팅 부서는 APP PUSH, 포털 · 리타겟팅 광고, 가격 비교 사이트 등 다양한 내
12 [멀티홉] 쇼라생방 D-10부터 진행해야 하면서 연관검색(1주)이 포함되고, 평일·주말 모두 가능하다고 명시된 패키지 중 쇼라PICK(1일)까지 포함된 상품의 금액은 얼마인가?
     답 100만원
     근거 doc.['4. 광고 상품 소개서 (p.24).pdf'] p.[22, 23]  라방플러스패키지B 100만원 신청가능 · 신한PLAY 앱내‘라방플러스알림’신청배너.연관검색(1주),
13 [멀티홉] PSD 가이드파일이 공유되고 수정 가능한 항목이 이미지, 소구포인트, 상품명, 가격, 상품코드, 간편번호로 안내된 형식과, 레이아웃이 자유형식이지만 제작 전 이미지 내 기재 텍스트 내용을 사전협의해야 하는 형식의 공통 파일포맷과 소재전달일은 무엇인가?
     답 공통 파일포맷은 이미지 JPG, PNG이고, 소재전달일은 노출일 기준 7일 전이다.
     근거 doc.['7. 데이터 영역 광고 제안서 (p.8).pdf'] p.[6, 7]  파일포맷|이미지JPG, PNG
14 [멀티홉] 분말류 또는 환제품에 수입산 특이원료를 사용하는 경우, 금속성이물성적서의 인정 기간과 원물추적성자료 제출 범위를 함께 설명하시오.
     답 금속성이물성적서는 분말류/환제품에 해당하며 공인기관 성적서로 6개월 이내여야 한다. 또한 수입산 특이원료의 경우 최초취급자부터 상품제조사까지 들어가는 유통간 모든 거래명세서를 제출해야 한다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[12, 13]  - 분말류/환제품해당(공인기관성적서, 6개월이내)
15 [멀티홉] 섬유 상품과 식품의 QA 제출 항목을 함께 고려할 때, 포장 관련 금지사항과 함께 공인기관 성적서로 제출해야 하는 포장 관련 서류는 각각 무엇인가?
     답 섬유 상품 준비서류에서는 샘플 포장 시 종이 무지테이프는 사용할 수 있고, 식품 QA 기본서류에서는 '개봉후반품불가' 테이프 사용이 금지된다. 또한 식품 성적서 항목에서는 제품이 닿는 내면 포장재질에 대한 공인기관 포장지 성적서를 제출해야 한다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[12, 20]  - '개봉후반품불가' 테이프사용금지
16 [멀티홉] 린넨 소재를 단독으로 소구하려면 어떤 세부감별 결과가 확인되어야 하고, 혼용률 기준상 어떤 함량 조건을 함께 충족해야 하는가?
     답 린넨 소재를 단독으로 소구하려면 혼용률 세부감별에서 마의 세부감별 결과가 ‘아마’로 확인되어야 하며, 혼용률 기준상 천연섬유 단독소구 조건에 따라 마 함량이 100%여야 한다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[24, 25]  * 린넨: 마세부감별결과‘아마’ 확인
17 [집계] 근거에서 파일별 진행상태는 몇 가지로 안내되며, 각 진행상태 항목은 무엇인가요?
     답 파일별 진행상태는 4가지입니다. 미등록, 등록, 수정요청, 승인완료입니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[13]  ②파일별진행상태확인이가능합니다.
(미등록/ 등록/ 수정요청/ 승인완료)
18 [집계] 현대홈쇼핑 배송은 몇 가지 형태로 구분 운영되며, 배송형태안내에 나온 항목은 무엇인가?
     답 현대홈쇼핑 배송은 4가지 형태로 구분 운영됩니다. 목록은 ①센터배송, ②현대홈직택배, ③협력사직택배, ④협력사직송입니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[14]  ○현대홈쇼핑배송은4가지형태로구분운영됩니다.
19 [집계] 전자계약서 서명 시 해당 계약서에 첨부하는 항목은 몇 가지이며, 항목 목록은 무엇입니까?
     답 총 3가지입니다. 목록은 ① 보증보험 ② 통장사본 ③ 사업자등록증 입니다.
     근거 doc.['6. 신규 협력사 입점 절차 안내 (p.21).pdf'] p.[6]  ①보증보험 ②통장사본 ③사업자등록증 을해당계약서에첨부하고 기업범용공인인증서 ( 사업자용) 로서명합니
20 [집계] 표준거래계약서에 첨부하는 제출서류는 몇 종이며, 어떤 서류를 차례로 업로드해야 하나요?
     답 제출서류는 3종입니다. 목록은 ① 보증보험 ② 통장사본 ③ 사업자등록증입니다.
     근거 doc.['6. 신규 협력사 입점 절차 안내 (p.21).pdf'] p.[18]  -표준거래계약서에제출서류(3종)을차례로업로드후, 양사가서명을하면계약체결이됩니다.
21 [집계] 협력사시스템(HELP 시스템)에서 QA자료관리 화면(화면번호 VD036)에 접속하는 경로에는 몇 개의 단계가 나열되어 있나요? 단계 이름을 모두 쓰세요.
     답 3개입니다. ① 메뉴클릭, ② 상품승인, ③ QA진행List입니다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[4]  접속경로: ①메뉴클릭→ ②상품승인→ ③QA진행List
22 [집계] 식품유형별/방송소구점 관련 세부 필요서류와 가이드 항목은 총 몇 개인가? 각 항목의 제목을 모두 나열하라.
     답 총 7개이다. 항목은 ① 크릴오일, 아르간오일, 복분자종자유 등 식용유지류, ② 500달톤, 300달톤 이하 저분자콜라겐, ③ 농산물/축산물 등의 품종 관련 소구, ④ 특허증, ⑤ 무첨가 관련 표현, ⑥ 원물 투입 후 추출 관련 표현, ⑦ NFC 주스(정제수 없이 통째로 착즙)이다.
     근거 doc.['8. QA가이드 (p.21).pdf'] p.[14]  ⑦NFC 주스(정제수없이통째로착즙):
23 [조건] 주문번호가 있는 주문, 교환, AS, 반품, 배송비 문의를 접수하려면 어느 화면이 필요한가요?
     답 협력사 Ref 접수(VD401) 화면에서 접수해야 합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[8]  ○주문, 교환, AS, 반품, 배송비등주문번호가있는문의 :협력사Ref 접수(VD401)화면에서접수
24 [조건] 방송상품 판매 전에 품질 적합성과 리스크 확인을 위해 진행하는 절차는 무엇인가요, 그리고 Hmall 상품은 같은 절차를 따르나요?
     답 방송상품 판매 전에는 QA를 진행합니다. 방송상품 QA 프로세스는 QA 의뢰, QA 자료 업로드, QA 검토, 합격/불합격, 방송 진행, 사후관리, 검사, 합격/불합격 순서로 안내되어 있습니다. Hmall 상품은 별도의 프로세스를 따르며, 등록된 웹기술서를 토대로 QA(심의)를 진행합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[12]  ※ Hmall상품은별도의프로세스를따릅니다. 등록된웹기술서를토대로QA(심의)를진행합니다.
25 [조건] 방송일 기준 최소 10일 전에 의뢰해야 하는 QA 종류와 해당 QA에서 점검하는 업무 항목은 무엇인가요?
     답 방송일 기준 최소 10일 전에 의뢰해야 하는 QA 종류는 현장QA입니다. 현장QA에서는 제조사 위생점검, 원료 및 자재 관리 점검, 품질표시정보 확인, 완제품 규격 및 포장상태 점검, 외관불량 및 구성품 혼입 점검 등을 수행합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[13]  현장QA 제조사, 물류센터방문을통한완제품의진정성을확인 기준일 의뢰: 방송일기준최소10일전의뢰/ 완료
26 [조건] 사전QA를 진행하려면 방송일 기준으로 의뢰 완료는 각각 언제까지 해야 하나요?
     답 사전QA는 방송일 기준 최소 14일 전에 의뢰해야 하고, 최소 4일 전에 완료해야 합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[13]  의뢰: 방송일기준최소14일전의뢰/ 완료: 방송일기준최소4일전완료
27 [조건] 협력사가 고객정보를 받아 직접 출고와 회수를 처리하려면 어떤 배송형태를 선택해야 합니까?
     답 협력사가 고객정보를 제공받아 직접 출고와 회수를 처리하려면 협력사직송을 선택해야 합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[14]  ④협력사직송 고객정보를제공하여협력사가직접 출고/회수합니다.
28 [조건] 토요일에도 출고하려는 협력사가 추가로 등록해야 하는 항목은 무엇인가?
     답 SCM 담당자를 통해 토요일 휴무 제외 등록이 필요하다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[16]  ※토요일출고희망협력사: SCM 담당자통해토요일휴무제외등록
29 [조건] 일반상품 또는 일반식품의 방송 시간과 출고 기준일에 따라 방송 당일, 방송 +1일, 방송 +2일, 방송 +3일 출고 비율은 각각 어떻게 다른가요?
     답 일반상품 또는 일반식품의 출고 비율은 방송 시간과 출고 기준일에 따라 다릅니다. 출고 기준일이 1일인 경우, 주간 방송은 방송 당일 60%, 방송 +1일 40%이며, 야간 방송은 방송 +1일 100%입니다. 출고 기준일이 2일인 경우, 주간 방송은 방송 당일 60%, 방송 +1일 30%, 방송 +2일 10%이고, 야간 방송은 방송 +1일 90%, 방송 +2일 10%입니다. 출고 기준일이 3일인 경우, 주간 방송은 방송 당일 60%, 방송 +1일 20%, 방송 +2일 10%, 방송 +3일 10%이며, 야간 방송은 방송 +1일 80%, 방송 +2일 10%, 방송 +3일 10%입니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[16]  |**일반상품/**<br>**일반식품**|**3일**|**야간**|**-**|**80%**|**10
30 [조건] 신규 입점 시 개인사업자가 추가로 제출해야 하는 서류는 무엇인가요?
     답 개인사업자는 사업자등록증 외에 주민등록등본(원본)과 신분증 사본이 필요합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[20]  ※ 개인사업자의경우주민등록등본(원본), 신분증사본
31 [절차] 방송운영으로 상품을 판매하기 위해 필요한 절차를 순서대로 알려주세요.
     답 방송운영으로 상품을 판매하기 위한 절차는 다음 순서입니다.
1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.
2. 상품평가및입점: MD가 상품을 검토한 후 최종 입점을 결정합니다.
3. 상품등록: 상품정보를 입력합니다.
4. QA: 현장 및 사전 QA를 진행합니다.
5. 방송편성: 상품군과 목표 등을 고려하여 방송시간을 편성합니다.
6. 심의: 영상 및 자막에 대한 심의 검토를 진행합니다.
7. 사전전략회의: 상품 특장점 및 소구 포인트 등 방송 진행 방향을 논의합니다.
8. 방송판매: Live 방송을 진행합니다.
9. 사후전략회의: 방송 실적을 분석하고 개선점을 공유하며 차후 운영 방향을 협의합니다.
10. 배송: 출고 및 배송을 체크합니다.
11. CS: 고객불만을 접수하고 처리합니다.
12. 정산: 대금을 지급합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[4]  협력사가파트너시스템을통해신상품제안
32 [절차] 신상품을 제안한 뒤 방송판매와 정산까지 진행하기 위해 필요한 절차를 순서대로 알려주세요.
     답 1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.
2. 상품평가및입점: MD가 상품을 검토한 후 최종 입점을 결정합니다.
3. 상품등록: 상품정보를 입력합니다.
4. QA: 현장 및 사전 QA를 진행합니다.
5. 방송편성: 상품군과 목표 등을 고려하여 방송시간을 편성합니다.
6. 심의: 영상 및 자막에 대한 심의 검토를 진행합니다.
7. 사전전략회의: 상품 특장점 및 소구 포인트 등 방송 진행 방향을 논의합니다.
8. 방송판매: Live 방송을 진행합니다.
9. 사후전략회의: 방송 실적을 분석하고 개선점을 공유하며 차후 운영 방향을 협의합니다.
10. 배송: 출고 및 배송을 체크합니다.
11. CS: 고객불만을 접수하고 처리합니다.
12. 정산: 대금을 지급합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[4]  **협력사가파트너시스템을통해신상품제안**
33 [절차] 신상품을 Hmall에 판매하기 위해 어떤 절차를 순서대로 진행해야 하나요?
     답 1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.
2. 상품평가및입점: MD가 상품을 검토한 후 최종 입점 여부를 결정합니다.
3. 상품등록: 상품정보를 입력합니다.
4. QA/심의: 웹기술서 심의를 진행합니다.
5. 프로모션: 상품 및 행사에 맞는 쿠폰, 적립, 무이자 등 판촉을 협의합니다.
6. 광고: 상품 및 행사에 맞는 배너, 탭, 팝업 등 광고를 협의합니다.
7. 링크/DB 제휴: 가격비교사이트 및 타쇼핑몰 노출을 협의합니다.
8. 판매: Hmall에 노출합니다.
9. 사후관리: 실적을 분석하고 행사 및 기획전을 리뷰합니다.
10. 배송: 출고 및 배송을 체크합니다.
11. CS: 고객불만을 접수하고 처리합니다.
12. 정산: 대금을 지급합니다.
     근거 doc.['1. 협력사 운영 통합 안내서 (p.23).pdf'] p.[4]  **협력사가파트너시스템을통해신상품제안**

절차 : 계속 동일한것만 여러개 가져옴 -> 가져오는 조건을 바꾸거나, 절차형을 알아볼 수 있게 개선 필요

In [49]:
REJECT = [6,7,9,17]
selected, seen = [], {k: 0 for k in TARGET}
for i, (kind, cs, d) in enumerate(stage2):
    if i in REJECT or seen[kind] >= TARGET[kind]:
        continue
    seen[kind] += 1
    selected.append((kind, cs, d))
print({k: v for k, v in seen.items() if k != "무답변"}, " 합계", len(selected))

{'단일홉': 6, '멀티홉': 4, '집계': 3, '조건': 2, '절차': 2}  합계 17

In [50]:
for kind, want in TARGET.items():
    if kind != "무답변" and seen[kind] < want:
        print(f"  {kind} 이 {want - seen[kind]}개 모자란다")

In [51]:
UNANSWERABLE = [("협력사 시스템 사용자 추가는 누구나 할 수 있나요?", "대표계정"),
                ("쇼라의 누적매출액은 얼마인가요?", "5800억"),
                ("협력사 휴무일 신청은 어디서 하나요?", "VD106")]

In [52]:
whole = squash("".join(c.page_content for c in all_chunks))
for q, key in UNANSWERABLE:
    print(f"{key:8} 코퍼스 등장 {whole.count(key)}회   {q}")

대표계정     코퍼스 등장 0회   협력사 시스템 사용자 추가는 누구나 할 수 있나요?
5800억    코퍼스 등장 0회   쇼라의 누적매출액은 얼마인가요?
VD106    코퍼스 등장 0회   협력사 휴무일 신청은 어디서 하나요?

In [ ]:
# 스키마 저장
records = [{"id": f"manual-{i:03d}", "type": kind, "question": d.question,
            "reference_answer": d.answer, "answerable": True,
            "evidence_pages": [
                list(source_page)
                for source_page in sorted({
                    (c.metadata["source"], c.metadata["page"])  # 문서명까지 함께 저장
                    for c in cs
                })
            ],
            "evidence_quotes": [d.quote], "difficulty": d.difficulty}
           for i, (kind, cs, d) in enumerate(selected, 1)]
print(len(records), "문항")

17 문항

In [108]:
from collections import Counter

records += [{"id": f"manual-{j:03d}", "type": "무답변", "question": q,
             "reference_answer": "문서에 없음", "answerable": False,
             "evidence_pages": [], "evidence_quotes": [], "difficulty": "medium"}
            for j, (q, _) in enumerate(UNANSWERABLE, len(records) + 1)]
print(len(records), "문항", Counter(r["type"] for r in records))

20 문항 Counter({'단일홉': 6, '멀티홉': 4, '집계': 3, '무답변': 3, '조건': 2, '절차': 2})

In [109]:
import json
from pathlib import Path

print(json.dumps(records[0], ensure_ascii=False, indent=1))

Path(GOLDEN).parent.mkdir(parents=True, exist_ok=True)
Path(GOLDEN).write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n", encoding="utf-8")

{
 "id": "manual-001",
 "type": "단일홉",
 "question": "주말과 공휴일은 출고기준일 산정에 포함되는가?",
 "reference_answer": "주말과 공휴일은 출고기준일 산정에 포함되지 않는다.",
 "answerable": true,
 "evidence_pages": [
  [
   "1. 협력사 운영 통합 안내서 (p.23).pdf",
   15
  ]
 ],
 "evidence_quotes": [
  "○주말/공휴일은출고기준일산정에미포함"
 ],
 "difficulty": "easy"
}

7426

In [40]:
#근거
def is_evidence(chunk, record):
    text = squash(chunk.page_content)
    return any(squash(q) in text for q in record["evidence_quotes"])


print(sum(is_evidence(c, records[0]) for c in all_chunks), "청크가 첫 문항의 근거다")

1 청크가 첫 문항의 근거다

In [41]:
from langchain_core.output_parsers import StrOutputParser

probe = [r for r in records if r["answerable"]][:5]
ask = ChatPromptTemplate.from_messages([("system", "근거만으로 두 문장 이내로 답한다."),
                                        ("human", "근거\n{ctx}\n\n질문\n{q}")])
ctx = {r["id"]: " ".join(c.page_content for c in all_chunks if is_evidence(c, r)) for r in probe}
reference = [r["reference_answer"] for r in probe]
print(len(probe), "문항")

5 문항

In [42]:
answers = {}
for label, name in [("참조를 쓴 모델", MODEL), ("평가 대상 모델", LOWER)]:
    answers[label] = (ask | ChatOpenAI(model=name) | StrOutputParser()).batch(
        [{"ctx": ctx[r["id"]], "q": r["question"]} for r in probe], config={"callbacks": [usage]})
    print(f"{label:14} {answers[label][3]}")

참조를 쓴 모델       검색 광고에서 A_검색창문구의 단가는 180만원이며, 노출기간은 1일입니다. 근거 표에 “검색창 A_검색창문구 1개 180만원 1일 1개”라고 명시되어 있습니다.
평가 대상 모델       검색창 A_검색창문구의 단가는 180만원이고, 노출기간은 1일입니다.

In [43]:
R = np.array(embeddings.embed_documents(reference))
for label, outs in answers.items():
    A = np.array(embeddings.embed_documents(outs))
    print(f"{label:14} 참조와의 평균 코사인 {float((A * R).sum(axis=1).mean()):.4f}")

참조를 쓴 모델       참조와의 평균 코사인 0.6885
평가 대상 모델       참조와의 평균 코사인 0.7591

## RAG 평가 (retrieval, generation)

<h3> 사전 세팅 _ 골든셋 가져오기, retrieval 구현, 임베딩 후 벡터DB 저장 </h3>

In [3]:
# 골든셋
import json

golden = [json.loads(line) for line in open(GOLDEN, encoding="utf-8")]
answerable = [r for r in golden if r["answerable"]]
print(len(golden), "문항 중 답이 있는 것", len(answerable))

20 문항 중 답이 있는 것 17

In [4]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader, PDFPlumberLoader, PyMuPDFLoader
from langchain_community.vectorstores import FAISS

PDF_LIST = sorted(Path(PDF_DIR).glob("*.pdf"))
PDF_CONFIGS = {
    "manual/1. 협력사 운영 통합 안내서 (p.23).pdf": "pymupdf_markdown",
    "manual/2. Hmall 소개서 (p.30).pdf": "pdfplumber",
    "manual/4. 광고 상품 소개서 (p.24).pdf": "pdfplumber",
    "manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf": "pymupdf_markdown",
    "manual/7. 데이터 영역 광고 제안서 (p.8).pdf": "pymupdf_markdown",
    "manual/8. QA가이드 (p.21).pdf": "pymupdf_markdown",
}

def load_pymupdf_markdown(pdf_path) :
    markdown_PyMuPDFLoader = PyMuPDFLoader(
                                pdf_path,
                                mode="page",
                                extract_tables="markdown"
                            )
    docs = markdown_PyMuPDFLoader.load()
    return docs

def load_pdfplumber(pdf_path) :
    docs = PDFPlumberLoader(pdf_path).load()
    return docs

# 청킹
chunks = []
for pdf_idx, pdf_path in enumerate(PDF_LIST):
    pdf_path = str(pdf_path)
    if pdf_path not in PDF_CONFIGS:
        continue

    method = PDF_CONFIGS[pdf_path]
    print(pdf_idx, method)

    # 1. PDF별 로딩
    print(pdf_path)
    if method == "pymupdf_markdown":
        docs = load_pymupdf_markdown(pdf_path)

    elif method == "pdfplumber":
        docs = load_pdfplumber(pdf_path)

    # 2. PDF 특성에 맞게 청킹
    rec_chunk = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=80
    ).split_documents(docs)
    print(len(rec_chunk))

    # 3. metadata 추가
    for chunk in rec_chunk:
        chunk.metadata["source"] = pdf_path.split("manual/", 1)[1]
        chunk.metadata["loader"] = method

    chunks.extend(rec_chunk)

# 벡터스토어
store = FAISS.from_documents(chunks, embeddings)

/home/ubuntu/work/kosa-ict-genai-2026-hyundai/src/exercise/csmoon1010/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

0 pymupdf_markdown
manual/1. 협력사 운영 통합 안내서 (p.23).pdf
Consider using the pymupdf_layout package for a greatly improved page layout analysis.
47
1 pdfplumber
manual/2. Hmall 소개서 (p.30).pdf
30
3 pdfplumber
manual/4. 광고 상품 소개서 (p.24).pdf
28
5 pymupdf_markdown
manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf
25
6 pymupdf_markdown
manual/7. 데이터 영역 광고 제안서 (p.8).pdf
10
7 pymupdf_markdown
manual/8. QA가이드 (p.21).pdf
135

In [5]:
# 기본 RAG
print(len(chunks), "청크")

275 청크

<h3> 1. k값 결정 </h3>

answerable 평가
- `hit_at_k`: 상위 k개 중 정답이 하나라도 있으면 1, 없으면 0이다. 개수가 아니라 예/아니오다.
- `precision_at_k`: 상위 k개 중 정답 개수를 k로 나눈다. 가져온 것 중 쓸모 있는 비율이다. 분모가 k로 고정되므로 정답 청크가 1개뿐이면 k=5에서 최대 0.2다. (단일홉이면 0.2인게 올바른 것!)
- `recall_at_k`: 상위 k개 중 정답 개수를 찾아야 할 정답 수로 나눈다. 찾아야 할 것 중 얼마나 찾았는가다. `n`은 청크 겹침 때문에 한 문항에 2개 이상일 수 있다.
- `mrr`: Mean Reciprocal Rank. 첫 정답이 나온 순위의 역수다. 1위면 1, 2위면 1/2, 5위면 1/5이고 정답이 없으면 0이다. 문항마다 구한 값을 평균한 것이 MRR이다. 첫 정답만 보므로 그 뒤에 정답이 더 있어도 점수가 오르지 않는다.
- `ndcg_at_k`: normalized Discounted Cumulative Gain. 상위 k개의 정답 각각에 순위가 낮을수록 작아지는 가중치 `1/log2(순위+1)`를 곱해 더한 값이 DCG다. 같은 정답들이 1위부터 빈틈없이 놓였을 때의 DCG로 나눠 0과 1 사이로 맞춘 것이 nDCG다. 정답이 여러 개일 때 각각의 순위를 모두 반영한다.

In [6]:
# 평가지표
import math

def hit_at_k(rel, k):
    return float(any(rel[:k]))


def precision_at_k(rel, k):
    return sum(rel[:k]) / k


def recall_at_k(rel, k, n):
    return sum(rel[:k]) / min(n, k) if n else float("nan")  # n 이 k 보다 크면 상한이 k 다

def mrr(rel):
    return next((1 / (i + 1) for i, r in enumerate(rel) if r), 0.0)


def ndcg_at_k(rel, k, n):
    dcg = sum(r / math.log2(i + 2) for i, r in enumerate(rel[:k]))
    ideal = sum(1 / math.log2(i + 2) for i in range(min(n, k)))
    return dcg / ideal if ideal else float("nan")

In [7]:
# 유사도 검색결과를 골든데이터셋의 evidence_quotes랑 비교
def is_evidence(chunk, record):
    text = "".join(chunk.page_content.split())
    return any("".join(q.split()) in text for q in record["evidence_quotes"])

def relevance(record, k):
    found = store.similarity_search(record["question"], k=k)
    return [int(is_evidence(c, record)) for c in found]

n_relevant = {r["id"]: sum(is_evidence(c, r) for c in chunks) for r in answerable}

In [8]:
# k 값 비교
# k=5 (각 지표의 균형이 가장 적절 / k=10인 경우 불필요 청크도 많아져 노이즈가 큼)
import pandas as pd

rows = []
for k in [1, 3, 5, 10]:
    rel = {r["id"]: relevance(r, k) for r in answerable}
    rows.append({"k": k,
                 "hit": sum(hit_at_k(rel[r["id"]], k) for r in answerable) / len(answerable),
                 "precision": sum(precision_at_k(rel[r["id"]], k) for r in answerable) / len(answerable),
                 "recall": sum(recall_at_k(rel[r["id"]], k, n_relevant[r["id"]]) for r in answerable) / len(answerable),
                 "MRR": sum(mrr(rel[r["id"]]) for r in answerable) / len(answerable),
                 "nDCG": sum(ndcg_at_k(rel[r["id"]], k, n_relevant[r["id"]]) for r in answerable) / len(answerable)})

pd.DataFrame(rows).set_index("k").round(3)

      hit  precision  recall    MRR   nDCG
k
1   0.471      0.471   0.471  0.471  0.471
3   0.824      0.373   0.657  0.637  0.578
5   1.000      0.306   0.878  0.678  0.674
10  1.000      0.171   0.939  0.678  0.702

유형별 평균</br>
- 단일홉 : 성능 우수</br>
MRR=0.917로 정답 청크가 대부분 매우 상위에 있습니다. recall=0.933도 높아 현재 검색 성능이 가장 안정적입니다.

- 멀티홉 : 순위 개선 필요</br>
recall=1.000이므로 필요한 정답 청크는 모두 검색했습니다. 하지만 MRR=0.446으로 낮아 정답 청크가 상위보다는 뒤쪽에 배치되는 문제가 있습니다. 검색 자체보다 청크 순위 조정이 필요합니다.

- 절차 : 필요한 정답 청크에 비해 recall이 낮음</br>
가장 개선이 필요한 유형입니다. 평균적으로 정답 청크가 2.5개 필요한데 recall@5=0.417에 그칩니다. 즉, top-5 안에 정답 청크가 하나 이상은 있지만 필요한 절차 정보 중 상당 부분을 놓치고 있습니다. hit@5=1.0만 보면 좋아 보이지만, 실제로는 답변에 필요한 전체 근거가 부족할 수 있습니다.

- 조건 : 순위 개선 필요</br>
정답 청크는 모두 찾았지만 MRR=0.500입니다. 조건 관련 청크가 검색 결과의 1위보다는 낮은 순위에 나오는 경향이 있습니다.

- 집계 : 양호</br>
recall=0.833, MRR=0.750으로 전반적으로 양호합니다. 다만 여러 수치나 항목을 함께 요구하는 질문에서 일부 근거가 누락될 가능성이 있습니다.

In [9]:
# k=5일 때 유형별 평균
K = 5
rel5 = {r["id"]: relevance(r, K) for r in answerable}

by_type = pd.DataFrame([{"유형": r["type"], "정답청크": n_relevant[r["id"]],
                         "hit@5": hit_at_k(rel5[r["id"]], K),
                         "recall@5": recall_at_k(rel5[r["id"]], K, n_relevant[r["id"]]),
                         "MRR": mrr(rel5[r["id"]])} for r in answerable])
by_type.groupby("유형").mean(numeric_only=True).round(3)

      정답청크  hit@5  recall@5    MRR
유형
단일홉  2.667    1.0     0.933  0.917
멀티홉  1.250    1.0     1.000  0.446
절차   2.500    1.0     0.417  0.500
조건   1.000    1.0     1.000  0.500
집계   1.333    1.0     0.833  0.750

무답변 문항 평가 :검색점수의 분포

In [10]:
# 무답변 문항 평가
# FAISS _ 거리값이 낮을 수록 질문과 청크가 유사 => 답이 있는 경우가 더 낮음
# 단, 최대와 최소가 겹치는 구간이 있기 때문에, 잘못 판단 가능성도 있음
# FAISS가 아닌 경우 : 코사인 유사도이므로 높은 점수가 더 유사한 것
for label, group in [("답이 있는 문항", answerable), ("무답변 문항", [r for r in golden if not r["answerable"]])]:
    tops = [store.similarity_search_with_score(r["question"], k=1)[0][1] for r in group]
    print(f"{label:12} 1위 점수 평균 {sum(tops) / len(tops):.3f}  최소 {min(tops):.3f}  최대 {max(tops):.3f}")

답이 있는 문항     1위 점수 평균 0.900  최소 0.746  최대 1.127
무답변 문항       1위 점수 평균 1.007  최소 0.894  최대 1.133

<h3> 2. 검색기 결정 (앙상블 제외) </h3>

<검색기>
MMR/BM25와 비교 : 앙상블 활용 고려

- MMR : Maximal Marginal Relevance / 질문과 관련있으면서, 이미 선택한 문서와는 최대한 다른 문서를 가져오게끔 (질문과의 관련성 - 이미 선택된 문서와의 중복성)
- BM25 : 의미 유사성이 아닌 단어의 일치로 판단하는 검색함수

In [11]:
from langchain_community.retrievers import BM25Retriever

bm25 = BM25Retriever.from_documents(chunks)
bm25.k = K
original = {r["id"]: r["question"] for r in answerable}

def score(name, fetch, questions):
    rel = {r["id"]: [int(is_evidence(c, r)) for c in fetch(questions[r["id"]])] for r in answerable}
    m = len(answerable)
    return {"구성": name,
            "hit@5": sum(hit_at_k(rel[r["id"]], K) for r in answerable) / m,
            "recall@5": sum(recall_at_k(rel[r["id"]], K, n_relevant[r["id"]]) for r in answerable) / m,
            "MRR": sum(mrr(rel[r["id"]]) for r in answerable) / m,
            "nDCG@5": sum(ndcg_at_k(rel[r["id"]], K, n_relevant[r["id"]]) for r in answerable) / m}

- MMR의 다양성 확보 과정 시, 필요한 근거까지 제거하여 Recall이 낮아짐. mult값을 늘렸을 때 성능이 더 좋아지는 것으로 보아, vector가 더 적합 
</br> (lambda_mult : 1.0에 가까울수록 유사도 중시, 0.0에 가까울수록 다양성 중시)
- BM25 : 단어의 일치를 통한 매칭보다 semantic matching이 더 적합

</br>
기본적으로 벡터 검색으로 가되, 앙상블은 retrieval pattern 비교시 고려!

In [12]:
table = pd.DataFrame([score("벡터 k=5", lambda q: store.similarity_search(q, k=K), original),
                      score("MMR k=5", lambda q: store.max_marginal_relevance_search(q, k=K, fetch_k=20), original),
                      score("MMR k=5/mult=0.7", lambda q: store.max_marginal_relevance_search(q, k=K, fetch_k=20, lambda_mult=0.7), original),
                      score("BM25 k=5", bm25.invoke, original)]).set_index("구성").round(3)
table

                  hit@5  recall@5    MRR  nDCG@5
구성
벡터 k=5            1.000     0.878  0.678   0.674
MMR k=5           0.647     0.399  0.520   0.365
MMR k=5/mult=0.7  0.824     0.622  0.595   0.494
BM25 k=5          0.471     0.441  0.431   0.414

<h3>3. RAGAS 평가 (1차)</h3>

| 지표 | 정의  |
|---|---|
| faithfulness | 답변이 검색된 문맥에 근거하고 있는지, 즉 환각(hallucination) 여부를 본다 |
| answer relevancy | 답변이 질문에 제대로 대응하는지를 본다. 정확성이 아니라 관련성. 답변에서 역생성한 질문들(n개)와 원 질문의 임베딩 유사도 |
| context precision | 검색된 청크 중 정말 필요한 것들이 상위에 랭크되어 있는지를 본다 |
| context recall | 정답을 만드는 데 필요한 정보를 빠짐없이 가져왔는지를 본다 |

In [17]:
# golden으로 부터 유사도검색 결과 가져오기
contexts = {g["id"]: [d.page_content for d in store.similarity_search(g["question"], k=5)] for g in golden}
print(len(contexts[golden[0]["id"]]), "청크")

5 청크

In [18]:
contexts[golden[17]["id"]]

['B 신규협력사\n가입여부확인및기초가입하기\n사업자등록번호\n앞으로이ID를사용하게됩니다\n1\n2\n정보입력후[ 저장] 버튼을누르면협력사정보가등록되었으며\nID/비밀번호를입력하여로그인하라는팝업이뜹니다.\n로그인창으로돌아가,\n1 에서생성한ID와비밀번호로로그인하시면됩니다.\n모든정보를기입하여저장합니다.\n앞으로이곳에서신규생성한ID를사용하게됩니다.\n※ 영업책임자의휴대폰번호와이메일주소는비밀번호찾기및\n단계진행현황알림을받는데사용되므로, 정확한기재바랍니다.\n1\n2',
 '3. 파트너시스템\n○현대홈쇼핑과거래하는협력사전용업무시스템입니다. 시스템가이드및교육영상을확인후이용해주시기바랍니다.\n협력사지원센터에서업무에필요한도움을받으실수있습니다.\n(1:1 문의, 신규입점방법, 담당자연락처등)\n협력사광고정보에서광고계약및단가등의통합정보를확인하실수있습니다.\nQ&A에서시스템이용과관련한★주요문의사항을확인하실수있습니다.\n1\n2\n3\n[로그인전]메인화면안내\n교육영상\n(QR 스캔/클릭→)\n←모바일어플설치: QR 스캔또는‘모바일HELP’버튼을클릭하세요.\n4\n파트너시스템바로가기\n시스템가이드바로가기',
 'STAGE 1\nSTAGE 2\nSTAGE 3\nSTAGE 4\nSTAGE 5\nSTAGE 6\n협력사기초가입시입력했던\n협력사정보및영업책임자정보를확인및수정할수있습니다.\n1\n모든정보를기입하여저장합니다.\n앞으로이곳에서신규생성한ID를사용하게됩니다.\n2\n정보입력후[ 저장] 버튼을누르면협력사정보가등록되었으며\nID/비밀번호를입력하여로그인하라는팝업이뜹니다.\n로그인창으로돌아가,\n2 에서생성한ID와비밀번호로로그인하시면됩니다.\n3\nSTAGE 1협력사정보확인/수정하기\n현대홈쇼핑입점프로세스STAGE 1.\n사업자등록번호\n앞으로이ID를사용하게됩니다\n2\n3\n1',
 '1\n신규입점제안버튼클릭→사업자등록번호입력후[ 가입여부확인] 버튼클릭\n1\n기초정보가등록된협력사인경우\n기존ID & PW로로그인\nA\n신규협력사인경우\n기초정보등록진행\nB\n가입여부확인및기초가입하기\n현대홈쇼핑입점프로세스\n신규협력사기초정보\n등록을진행합니다.',
 'QA공통가이드라인\n협력사시스템서류업로드가이드\n※ ‘중소기업유통센터’ 코드사용협력사의경우사전에담당QA에게내용공유부탁드립니다.\n협력사시스템(HELP 시스템) 內\nQA자료관리(화면번호: VD036) 화면접속\n화면번호바로검색: VD036\n접속경로: ①메뉴클릭→ ②상품승인→ ③QA진행List\n①\n②\n③\n화면접속하기\nSTEP 01']

In [ ]:
# golden 질문들의 RAG 답변 확인 (k=5, vector 검색기)
from langchain_core.output_parsers import StrOutputParser

answer_prompt = ChatPromptTemplate.from_messages([
    ("system", "근거만으로 답한다. 근거에 없으면 '문서에 없음' 이라고 답한다. 사용한 근거 번호를 [n] 으로 붙인다."),
    ("human", "근거\n{context}\n\n질문\n{question}"),
])
answer_chain = answer_prompt | ChatOpenAI(model=LOWER) | StrOutputParser()

answers = dict(zip([g["id"] for g in golden],
                   answer_chain.batch([{"context": "\n\n".join(f"[{i}] {t}" for i, t in enumerate(contexts[g["id"]], 1)),
                                        "question": g["question"]} for g in golden], config={"callbacks": [usage]})))
print(answers[golden[1]["id"]])

신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자 연락처는 **yunsh_@hyundaihmall.com** 입니다. [1][2]

In [ ]:
from ragas import EvaluationDataset, SingleTurnSample, evaluate
from ragas.embeddings.base import LangchainEmbeddingsWrapper
from ragas.llms.base import LangchainLLMWrapper
from ragas.metrics import Faithfulness, LLMContextPrecisionWithReference, LLMContextRecall, ResponseRelevancy
from ragas.run_config import RunConfig

run_config = RunConfig(timeout=180, max_retries=2, max_workers=2)
samples = [SingleTurnSample(user_input=g["question"], response=answers[g["id"]],
                            retrieved_contexts=contexts[g["id"]], reference=g["reference_answer"]) for g in golden]
dataset = EvaluationDataset(samples=samples)
ragas_llm = LangchainLLMWrapper(ChatOpenAI(model=LOWER))
ragas_emb = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model=EMBEDDING))

metrics = [Faithfulness(), ResponseRelevancy(), LLMContextPrecisionWithReference(), LLMContextRecall()]
result = evaluate(dataset, metrics=metrics, llm=ragas_llm, embeddings=ragas_emb, run_config=run_config, raise_exceptions=True, callbacks=[usage])
result

/tmp/ipykernel_168434/658113805.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import Faithfulness, LLMContextPrecisionWithReference, LLMContextRecall, ResponseRelevancy
/tmp/ipykernel_168434/658113805.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import Faithfulness, LLMContextPrecisionWithReference, LLMContextRecall, ResponseRelevancy
/tmp/ipykernel_168434/658113805.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import Faithfulness, LLMContextPrecisionWithReference, LLMContextRecall, ResponseRelevancy
/tmp/ipykernel_168434/658113805.py:4: DeprecationWarning: Importing ResponseRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ResponseRelevancy
  from ragas.metrics import Faithfulness, LLMContextPrecisionWithReference, LLMContextRecall, ResponseRelevancy
/tmp/ipykernel_168434/658113805.py:11: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; client = OpenAI(api_key='...'); llm = llm_factory('gpt-4o-mini', client=client)
  ragas_llm = LangchainLLMWrapper(ChatOpenAI(model=LOWER))
/tmp/ipykernel_168434/658113805.py:12: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_emb = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model=EMBEDDING))
Evaluating:   2%|▎         | 2/80 [00:28<17:53, 13.76s/it]

In [143]:
METRIC_COLS = [m.name for m in metrics]
table = result.to_pandas()
table.insert(0, "id", [g["id"] for g in golden])
table.insert(1, "쪽", [g["evidence_pages"] for g in golden])
table.set_index("id")[["쪽"] + METRIC_COLS].round(3)
table

,id,쪽,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,llm_context_precision_with_reference,context_recall
0,manual-001,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 15]]",주말과 공휴일은 출고기준일 산정에 포함되는가?,[8. 물류및배송\n○출고기준일/ 출고마감일\n주문일\n출고기준일\n출고마감일\n내...,주말/공휴일은 출고기준일 산정에 포함되지 않습니다. [1],주말과 공휴일은 출고기준일 산정에 포함되지 않는다.,1.000000,0.931470,1.000000,1.0
1,manual-002,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 21]]",신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자...,[|Hmall제휴|홍보 / 브랜드마케팅|Col3|\n|---|---|---|\n|*...,신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자...,yunsh_@hyundaihmall.com,1.000000,0.995495,1.000000,1.0
2,manual-003,"[[2. Hmall 소개서 (p.30).pdf, 19]]",플랫폼행사는 Hmall의 어느 영역에 노출되는가?,[┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n03\nHmall에 입점하면\n어떤...,플랫폼행사는 Hmall의 **PC·모바일 메인 영역**에 노출됩니다. 메인 탭부터 ...,플랫폼행사는 Hmall의 PC · 모바일 메인영역에 노출된다.,1.000000,0.720727,1.000000,1.0
3,manual-004,"[[4. 광고 상품 소개서 (p.24).pdf, 11]]",검색 광고에서 A_검색창문구의 1일 단가는 얼마인가요?,[영역별 광고 단가 – 검색 광고\n상품을 검색하는 과정에서 자연스럽게 노출되어 접...,A_검색창문구의 1일 단가는 180만원입니다. [1],180만원입니다.,1.000000,0.701812,1.000000,1.0
4,manual-005,"[[6. 신규 협력사 입점 절차 안내 (p.21).pdf, 5]]",신상품 제안서 심사 결과 확인까지 영업일 기준으로 어느 정도 소요됩니까?,[제안서심사결과는영업일기준5일정도소요됩니다.\n제안상품은담당MD가단독으로결정하지않고...,제안서 심사 결과는 영업일 기준 5일 정도 소요됩니다.[1][2][4],영업일 기준 5일 정도 소요됩니다.,1.000000,0.521088,1.000000,1.0
5,manual-006,"[[8. QA가이드 (p.21).pdf, 9]]",당도를 소구하는 경우 브릭스측정자료로 추가 제출해야 하는 자료는 무엇인가요?,[|제출 서류|세부 내용|\n|---|---|\n|수입업소사업자등록증|수입업소사업자...,당도를 소구하는 경우 추가 제출해야 하는 자료는 **자동당도선별기관련 사진 또는 동...,자동당도선별기관련 사진 또는 동영상 자료를 전달해야 합니다.,1.000000,0.820119,0.866667,1.0
6,manual-007,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 19], [1. 협력사 운영...","개인사업자가 신규 입점한 뒤 역발행 방식으로 세금계산서를 처리할 때, 상품대금 부가...",[|구분|내용|Col3|Col4|\n|---|---|---|---|\n|**발행방식...,개인사업자가 역발행 방식으로 세금계산서를 처리할 때는 **매월 1~10일 사이에 세...,개인사업자가 역발행 세금계산서로 상품대금 부가세를 받으려면 매월 1~10일에 세금계...,0.750000,0.603213,1.000000,1.0
7,manual-008,"[[2. Hmall 소개서 (p.30).pdf, 18], [2. Hmall 소개서 ...","Hmall에서 입점 브랜드와 상품을 제휴사까지 포함해 홍보·판매할 수 있는 수단과,...",[11. 광고/ 마케팅/ 제휴\n○현대홈쇼핑과의사업제휴및협업을희망하는협력사의많은관심...,Hmall에서 입점 브랜드와 상품을 홍보·판매할 수 있는 수단은 다음입니다. \n...,"입점 브랜드와 상품은 APP PUSH, 포털·리타겟팅 광고, 가격비교 사이트와 같은...",1.000000,0.751262,0.887500,1.0
8,manual-009,"[[4. 광고 상품 소개서 (p.24).pdf, 21], [4. 광고 상품 소개서 ...","쇼라생방 D-10부터 진행해야 하면서 연관검색(1주)이 포함되고, 평일·주말 모두 ...","[머니알림패키지 100만원 - - 쇼쇼 쇼쇼 D-10 · 쇼라캘린더코인노출, 탑배너...","조건에 맞는 상품은 **메타패키지A**이며, 금액은 **100만원**입니다. \n...",100만원,0.833333,0.327242,1.000000,1.0
9,manual-010,"[[7. 데이터 영역 광고 제안서 (p.8).pdf, 5], [7. 데이터 영역 광...","PSD 가이드파일이 공유되고 수정 가능한 항목이 이미지, 소구포인트, 상품명, 가격...","[|구분|내용|\n|---|---|\n|해상도|ACAP : 가로212 pixel, ...","공통 파일포맷은 **이미지 JPG, PNG**이고, 소재전달일은 **노출일 기준 7...","공통 파일포맷은 이미지 JPG, PNG이고, 소재전달일은 노출일 기준 7일 전이다.",1.000000,0.508843,0.887500,1.0
10,manual-011,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 13]]","현대홈쇼핑 배송은 몇 가지 형태로 구분 운영되며, 배송형태안내에 나온 항목은 무엇인가?",[8. 물류및배송\n①센터배송\n④협력사직송\n②현대홈직택배\n③협력사직택배\n현대...,현대홈쇼핑 배송은 **4가지 형태**로 구분 운영됩니다.[1]\n\n배송형태안내에 ...,"현대홈쇼핑 배송은 4가지 형태로 구분 운영됩니다. 목록은 ①센터배송, ②현대홈직택배...",1.000000,0.890248,1.000000,1.0
11,manual-012,"[[6. 신규 협력사 입점 절차 안내 (p.21).pdf, 5]]","전자계약서 서명 시 해당 계약서에 첨부하는 항목은 몇 가지이며, 항목 목록은 무엇입니까?",[STAGE 5 표준거래계약서서명\n현대홈쇼핑입점프로세스\nSTAGE 1\nSTAG...,전자계약서 서명 시 해당 계약서에 첨부하는 항목은 **3가지**입니다. 항목 목록은...,총 3가지입니다. 목록은 ① 보증보험 ② 통장사본 ③ 사업자등록증 입니다.,1.000000,0.950841,1.000000,1.0
12,manual-013,"[[6. 신규 협력사 입점 절차 안내 (p.21).pdf, 17]]","표준거래계약서에 첨부하는 제출서류는 몇 종이며, 어떤 서류를 차례로 업로드해야 하나요?",[제출서류안내\n현대홈쇼핑입점프로세스STAGE 4.\nSTAGE 1\nSTAGE 2...,표준거래계약서에 첨부하는 제출서류는 **총 3종**입니다. 차례로 업로드해야 하는 ...,제출서류는 3종입니다. 목록은 ① 보증보험 ② 통장사본 ③ 사업자등록증입니다.,0.250000,0.889859,0.916667,1.0
13,manual-014,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 7]]","주문번호가 있는 주문, 교환, AS, 반품, 배송비 문의를 접수하려면 어느 화면이 ...","[상표등록원부, 브랜드라이선스계약서(영문/한글본)\n법인또는개인확인서류\n첨부\n수...","주문번호가 있는 주문, 교환, AS, 반품, 배송비 문의는 **협력사Ref 접수(V...",협력사 Ref 접수(VD401) 화면에서 접수해야 합니다.,1.000000,0.913322,0.500000,1.0
14,manual-015,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 11]]","방송상품 판매 전에 품질 적합성과 리스크 확인을 위해 진행하는 절차는 무엇인가요, ...",[Hmall 복수상품등록\nSTAGE 2. 신상품제안\nSTAGE 1\nSTAGE ...,방송상품 판매 전에는 **QA(품질 적합성 및 리스크 확인)** 를 진행합니다. 이...,"방송상품 판매 전에는 QA를 진행합니다. 방송상품 QA 프로세스는 QA 의뢰, QA...",0.800000,0.630653,0.450000,1.0
15,manual-016,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 3]]",방송운영으로 상품을 판매하기 위해 필요한 절차를 순서대로 알려주세요.,[-\n야간\n-\n90%\n10%\n-\n3일\n주간\n60%\n20%\n10%\...,방송운영으로 상품을 판매하기 위한 절차는 다음 순서입니다. [2]\n\n1. 협력사...,방송운영으로 상품을 판매하기 위한 절차는 다음 순서입니다.\n1. 협력사제안: 협력...,1.000000,0.807435,0.500000,1.0
16,manual-017,"[[1. 협력사 운영 통합 안내서 (p.23).pdf, 3]]",신상품을 제안한 뒤 방송판매와 정산까지 진행하기 위해 필요한 절차를 순서대로 알려주세요.,[신상품제안\n제안결과확인\n현대홈쇼핑입점프로세스STAGE 2.\nSTAGE 1\n...,신상품 제안 후 방송판매와 정산까지의 절차는 다음과 같습니다. [2][5]\n\n1...,1. 협력사제안: 협력사가 파트너시스템을 통해 신상품을 제안합니다.\n2. 상품평가...,1.000000,0.798025,0.866667,1.0
17,manual-018,[],협력사 시스템 사용자 추가는 누구나 할 수 있나요?,[B 신규협력사\n가입여부확인및기초가입하기\n사업자등록번호\n앞으로이ID를사용하게됩...,문서에 없음.,문서에 없음,0.000000,0.000000,0.500000,0.0
18,manual-019,[],쇼라의 누적매출액은 얼마인가요?,"[머니알림패키지 100만원 - - 쇼쇼 쇼쇼 D-10 · 쇼라캘린더코인노출, 탑배너...",문서에 없음.,문서에 없음,1.000000,0.000000,1.000000,0.0
19,manual-020,[],협력사 휴무일 신청은 어디서 하나요?,"[현대홈쇼핑\n협력사운영통합안내서\n2024.06, B 신규협력사\n가입여부확인및기...",문서에 없음.,문서에 없음,1.000000,0.000000,0.000000,0.0

answer relevancy가 낮은편이라, 최하값 확인
=> 금액만 묻는 질문에, 실 답변은 부가적인 설명이 포함되어있음

In [ ]:
worst = table[:17]["answer_relevancy"].idxmin() # unanswerable 제외
g = golden[worst]
print("질문:", g["question"])
print("참조:", g["reference_answer"])
print("답변:", answers[g["id"]].replace("\n", " "))
print({m: round(table.loc[worst, m], 2) for m in METRIC_COLS})

질문: 쇼라생방 D-10부터 진행해야 하면서 연관검색(1주)이 포함되고, 평일·주말 모두 가능하다고 명시된 패키지 중 쇼라PICK(1일)까지 포함된 상품의 금액은 얼마인가?
참조: 100만원
답변: 조건에 맞는 상품은 **메타패키지A**이며 금액은 **100만원**입니다. 연관검색(1주)가 포함되고, 평일·주말 모두 가능하며, 쇼라PICK(1일)도 포함되어 있고, 신청기한이 쇼라생방 D-10입니다.[2]
{'faithfulness': np.float64(0.83), 'answer_relevancy': np.float64(0.33), 'llm_context_precision_with_reference': np.float64(1.0), 'context_recall': np.float64(1.0)}

커스텀 메트릭

In [160]:
samples

[SingleTurnSample(user_input='주말과 공휴일은 출고기준일 산정에 포함되는가?', retrieved_contexts=['8. 물류및배송\n○출고기준일/ 출고마감일\n주문일\n출고기준일\n출고마감일\n내용\n05.27(월)\n1일\n05.28(화)\n05.27~28출고가능\n2일\n05.29(수)\n05.27~29출고가능\n3일\n05.30(목)\n05.27~30출고가능\n05.24(금)\n1일\n05.25(토)\n05.24~25출고가능\n2일\n05.27(월)\n05.24~27출고가능\n3일\n05.28(화)\n05.24~28출고가능\n○출고기준일은매체별, 상품군별로상이함\n○결제일(D-day) 기준으로D+1일, D+2일등으로표현\n○주말/공휴일은출고기준일산정에미포함\n※토요일출고희망협력사: SCM 담당자통해토요일휴무제외등록\n구분\n출고\n기준일\n방송\n시간\n방송\n당일\n방송\n+1일\n방송\n+2일\n방송\n+3일\n일반상품/\n일반식품\n1일\n주간\n60%\n40%\n-\n-\n야간\n-\n100%\n-\n-\n2일\n주간\n60%\n30%\n10%\n-\n야간\n-\n90%\n10%\n-\n3일\n주간\n60%\n20%\n10%\n10%\n야간\n-\n80%\n10%\n10%\n냉동/냉장\n식품\n3일\n주간\n50%\n20%', '|주문일|출고기준일|출고마감일|내용|\n|---|---|---|---|\n|**05.27(월)**|**1일**|**05.28(화)**|**05.27~28출고가능**|\n|**05.27(월)**|**2일**|**05.29(수)**|**05.27~29출고가능**|\n|**05.27(월)**|**3일**|**05.30(목)**|**05.27~30출고가능**|\n|**05.24(금)**|**1일**|**05.25(토)**|**05.24~25출고가능**|\n|**05.24(금)**|**2일**|**05.27(월)**|**05.24~27출고가능**|\n|**05.24(금)**|**3일**|**05.28(화)**|**05.24~28출고가능**|', '|구분|출고<br>기준일|방송<br>시간|방송<br>당일|방송<br>+1일|방송<br>+2일|방송<br>+3일|\n|---|---|---|---|---|---|---|\n|**일반상품/**<br>**일반식품**|**1일**|**주간**|**60%**|**40%**|**-**|**-**|\n|**일반상품/**<br>**일반식품**|**1일**|**야간**|**-**|**100%**|**-**|**-**|\n|**일반상품/**<br>**일반식품**|**2일**|**주간**|**60%**|**30%**|**10%**|**-**|\n|**일반상품/**<br>**일반식품**|**2일**|**야간**|**-**|**90%**|**10%**|**-**|\n|**일반상품/**<br>**일반식품**|**3일**|**주간**|**60%**|**20%**|**10%**|**10%**|\n|**일반상품/**<br>**일반식품**|**3일**|**야간**|**-**|**80%**|**10%**|**10%**|', '|구분|내용|\n|---|---|\n|**정산**<br>**주기**|**· 1주기: 01일~ 10일**<br>**· 2주기: 11일~ 20일**<br>**· 3주기: 21일~ 31일(말일)**|\n|**대금**<br>**정산**|**· 공급가정산:주기별마감후영업일기준+5일**<br>**※ 대기업의경우정산주기마감+25 영업일뒤지급**<br>**· 부가세정산: 익월10일세금계산서승인마감후+5영업일**<br>**※ 대기업의경우매월1주기대금지급일**|\n|**정산**<br>**기준**|**· 특약: 주문출고확정일기준매출발생**<br>**· 직매입: 입고확정일기준매출발생**|', '|구분|내용|Col3|Col4|\n|---|---|---|---|\n|**발행방식**|**정발행**|**상품을공급하는자→ 상품을공급받는자**|**상품을공급하는자→ 상품을공급받는자**|\n|**발행방식**|**역발행**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|\n|**마감**|**당사**|**매월1일마감세금계산서발행**|**매월1일마감세금계산서발행**|\n|**마감**|**협력사**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='주말/공휴일은 출고기준일 산정에 포함되지 않습니다. [1]', multi_responses=None, reference='주말과 공휴일은 출고기준일 산정에 포함되지 않는다.', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자 연락처는 무엇인가요?', retrieved_contexts=['|Hmall제휴|홍보 / 브랜드마케팅|Col3|\n|---|---|---|\n|**○신규매체/플랫폼전략제휴**<br>**○판매수수료기반CPS(Cost per sale) 제휴**|**○언론홍보/보도자료**<br>**○온라인바이럴/디지털광고**|**○방송행사및대외이벤트**<br>**○친환경캠페인**|\n|**▷담당자연락처yunsh_@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|\n|**퍼포먼스마케팅**|**Hmall내부광고**|**Hmall내부광고**|', '11. 광고/ 마케팅/ 제휴\n○현대홈쇼핑과의사업제휴및협업을희망하는협력사의많은관심부탁드립니다.\nHmall제휴\n홍보/ 브랜드마케팅\n○신규매체/플랫폼전략제휴\n○판매수수료기반CPS(Cost per sale) 제휴\n○언론홍보/보도자료\n○온라인바이럴/디지털광고\n○방송행사및대외이벤트\n○친환경캠페인\n▷담당자연락처yunsh_@hyundaihmall.com\n▷담당자연락처jhdo919@hyundaihmall.com\n퍼포먼스마케팅\nHmall내부광고\n○방송/Hmall신규광고및플랫폼제안\n○검색광고-키워드/쇼핑검색등\n○퍼포먼스광고-DA/APP/SNS\n○HmallPC/모바일광고\n○Hmall배너광고\n▷담당자연락처chasy@hyundaihmall.com\n▷담당자연락처kmsong1523377@hyundaihmall.com\n광고상품소개서바로가기', '┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n05\n오픈마켓 등 외부 사이트에\n상품을 연동할 수 있나요?\n여러 사이트에 입점할 필요 없이, Hmall과 제휴되어 있는\n오픈마켓, 복지몰 등에 상품 DB를 연동하여 판매할 수 있습니다.\n오픈마켓 메인딜 및 대형 행사 참여 기회를 잡아 보세요.\n주요DB제휴사\n·DB제휴:제휴사이트에Hmall상품및주문데이터를연동하여판매한후,\n사후에대금을정산하는방법(고객은제휴사이트에서결제함)\n구분 대표행사 대표딜 비고\n※ 제휴행사참여를원할경우담당MD와협의하세요.\n23', '진행단계마다영업책임자의휴대폰으로SMS가발송됩니다.\n기존입점이완료된협력사( = 협력사코드가발급된협력사) 의경우, \n협력사시스템에로그인하여진행하여주시기바랍니다.\n( 신규입점제안시스템이용불가)\n!\n제안결과확인', '|단계|내용|\n|---|---|\n|**협력사제안**|**협력사가파트너시스템을통해신상품제안**|\n|**상품평가및입점**|**MD가상품검토후, 최종입점결정**|\n|**상품등록**|**상품정보입력**|\n|**QA/심의**|**웹기술서심의**|\n|**(프로모션)**|**상품및행사에맞는쿠폰/적립/무이자등판촉협의**|\n|**(광고)**|**상품및행사에맞는배너/탭/팝업등광고협의**|\n|**(링크/DB 제휴)**|**가격비교사이트및타쇼핑몰노출협의**|\n|**판매**|**Hmall노출**|\n|**사후관리**|**실적분석, 행사/기획전리뷰**|\n|**배송**|**출고및배송체크**|\n|**CS**|**고객불만접수및처리**|\n|**정산**|**대금지급**|'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='신규매체/플랫폼전략제휴와 판매수수료기반CPS(Cost per sale) 제휴 담당자 연락처는 **yunsh_@hyundaihmall.com** 입니다. [1][2]', multi_responses=None, reference='yunsh_@hyundaihmall.com', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='플랫폼행사는 Hmall의 어느 영역에 노출되는가?', retrieved_contexts=['┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n03\nHmall에 입점하면\n어떤 행사에 참여할 수 있나요?\nHmall 마케팅 부서는 매월 다양한 플랫폼 행사를 운영합니다.\n참여시 판촉 및 메인 노출 등의 지원을 받을 수\n(리워드,카드할인등)\n있습니다. 담당 MD와 협의하여 플랫폼 행사에 참여해보세요!\nHmall 주요 플랫폼행사\n매주시즌· 이슈에맞춰 단일브랜드or 연합으로\n진행하는카테고리단위행사 진행하는브랜드단위행사\n페어 브랜드줌\n매주화요일, 전상품 식품연속구매유도를위한\n추가적립프로모션 다건적립프로모션\n올-인데이 릴레이푸드\n매주금요일, 상품홍보,리뷰확보를위한\n원데이핫딜상품특가 신상품체험단\n불금데이 스마일테스터\n19', '┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n플랫폼 행사 메인 노출 구좌\n플랫폼행사는Hmall의PC · 모바일메인영역에노출됩니다.\n메인탭부터팝업, 앱 스플래시, 별도탭까지.\n상품을효과적으로홍보할수있는노출기회를잡으세요!\n이상품지금딱(기획전)\n딜배너\n이상품지금딱(단품)\n기획전배너\n눈여겨보는센스\n※ 행사에따라노출구좌가상이합니다.\n20', '|**퍼포먼스마케팅**|**Hmall내부광고**|**Hmall내부광고**|\n|**○방송/Hmall신규광고및플랫폼제안**<br>**○검색광고-키워드/쇼핑검색등**<br>**○퍼포먼스광고-DA/APP/SNS**|**○HmallPC/모바일광고**<br>**○Hmall배너광고**<br>**광고상품소개서바로가기**|**○HmallPC/모바일광고**<br>**○Hmall배너광고**<br>**광고상품소개서바로가기**|\n|**▷담당자연락처chasy@hyundaihmall.com**|**▷담당자연락처kmsong1523377@hyundaihmall.com**|**▷담당자연락처kmsong1523377@hyundaihmall.com**|', '영역별 광고 단가 – 팝업\nHmall 접속 시 가장 주목도가 높은 영역에 노출되어 프로모션 효과를 극대화할 수 있습니다.\n구분 상품명 단가(만원) 노출기간 구좌수(日)\nA_팝업\nA_팝업(오전) 300만원 12시간 1개\nㆍ오전: 00-12시(12시간)\n팝업\nㆍ오후: 12-24시(12시간)\nA_팝업(오후) 500만원 12시간 1개\nB_단독브랜드탭1번 700만원 1일 1개\n탭광고\nB_단독브랜드탭2번 400만원 1일 1개\n1', 'V.4\nHmall 소개서\n발행일 2024년6월\n발 행 현대홈쇼핑\n서울특별시강동구올림픽로70길34\n본Hmall소개서일체의무단복사,전시,배포,대여,변형을금하며,\n기재된내용을이용하려면반드시서면동의를받아야합니다.'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='플랫폼행사는 Hmall의 **PC·모바일 메인 영역**에 노출됩니다. 메인 탭부터 팝업, 앱 스플래시, 별도 탭까지 노출될 수 있습니다. 행사에 따라 노출 구좌는 다릅니다. [2]', multi_responses=None, reference='플랫폼행사는 Hmall의 PC · 모바일 메인영역에 노출된다.', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='검색 광고에서 A_검색창문구의 1일 단가는 얼마인가요?', retrieved_contexts=['영역별 광고 단가 – 검색 광고\n상품을 검색하는 과정에서 자연스럽게 노출되어 접근성이 좋고 구매를 유도할 수 있습니다.\nA_검색창문구\n구좌수\n구분 노출형태 키워드 단가(만원) 노출기간\n(日)\nB_검색전배너(기획전)\n검색창 A_검색창문구 1개 180만원 1일 1개\n검색전\nB_배너형(1개) 또는상품형(2개) - 180만원 1일 3개\n배너\n최대\n연관검색 C_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50개\n최대\n검색결과 D_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50개\nB_검색전배너(상품형)\n검색결과 E_영상배너(1개) -패키지A 최대\n175만원 7일 무제한\n영상 → 일반+ 브랜드키워드 130개\n검색결과 E_영상배너(1개) -패키지B 최대\n90만원 7일 무제한\n영상 → 브랜드키워드 50개\n9', '영역별 광고 단가 – 검색 광고\n상품을 검색하는 과정에서 자연스럽게 노출되어 접근성이 좋고 구매를 유도할 수 있습니다.\n키\n구좌수\n구분 노출형태 워 단가(만원) 노출기간\n(日)\n드\nD_검색결과(배너형)\n검색창 A_검색창문구 1개 180만원 1일 1개\n검색전배너 B_배너형(1개) 또는상품형(2개) - 180만원 1일 3개\n최\n대\n연관검색 C_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50\n개\n최\n대\n검색결과 D_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50\n개\n최\n검색결과 E_영상배너(1개) -패키지A 대\n175만원 7일 무제한\n영상 → 일반+ 브랜드키워드 13\n0개\n최 D_검색결과(상품형)\n검색결과 E_영상배너(1개) -패키지B 대\n90만원 7일 무제한\n영상 → 브랜드키워드 50\n개\n11', '영역별 광고 단가 – 검색 광고\n상품을 검색하는 과정에서 자연스럽게 노출되어 접근성이 좋고 구매를 유도할 수 있습니다.\n구좌수\n구분 노출형태 키워드 단가(만원) 노출기간\n(日)\n검색창 A_검색창문구 1개 180만원 1일 1개\n검색전배너 B_배너형(1개) 또는상품형(2개) - 180만원 1일 3개\n최대\n연관검색 C_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50개\nC_연관검색(배너형)\n최대\n검색결과 D_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50개\n검색결과 E_영상배너(1개) -패키지A 최대\n175만원 7일 무제한\n영상 → 일반+ 브랜드키워드 130개\n검색결과 E_영상배너(1개) -패키지B 최대\n90만원 7일 무제한\n영상 → 브랜드키워드 50개 C_연관검색(상품형)\n10', '영역별 광고 단가 – 검색 광고\n상품을 검색하는 과정에서 자연스럽게 노출되어 접근성이 좋고 구매를 유도할 수 있습니다.\n구좌수\n구분 노출형태 키워드 단가(만원) 노출기간\n(日)\n검색창 A_검색창문구 1개 180만원 1일 1개\n검색전배너 B_배너형(1개) 또는상품형(2개) - 180만원 1일 3개\n최대\n연관검색 C_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50개 E_영상배너(1개)\n최대\n검색결과 D_배너형(1개) 또는상품형(2개) 50만원 7일 무제한\n50개\n검색결과 E_영상배너(1개) -패키지A 최대\n175만원 7일 무제한\n영상 → 일반+ 브랜드키워드 130개\n검색결과 E_영상배너(1개) -패키지B 최대\n90만원 7일 무제한\n영상 → 브랜드키워드 50개\n12', '영역별 광고 단가 – 현대홈쇼핑탭\n노출도가 높은 영역으로 브랜드 마케팅 메시지를 효과적으로 전달할 수 있습니다.\n구분 상품명 단가(만원) 노출기간 구좌수(日) E_MD 제안\nA_탑배너(상단) 300만원 1일 2개\nA_탑배너(중단) 150만원 1일 3개\nA_탑배너(하단) 100만원 1일 4개\nB_오늘의메인행사 180만원 1일 1개\nC_타임딜 150만원 1일 1개\nD_월간신상 70만원 1일 3개\n현대\nE_MD제안 20만원 1일 2개\n홈쇼핑탭\nF_오늘의추천상품 30만원 1일 1개\nG_지금주목할기획전(상단) 120만원 1일 1개\nG_지금주목할기획전(중단) 100만원 1일 2개\nH_믿고보는혜택상품(상단) 100만원 1일 2개\nH_믿고보는혜택상품(중단) 50만원 1일 4개\nI_오늘특가 2만원 1일 무제한 F_오늘의추천상품\n5'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='A_검색창문구의 1일 단가는 180만원입니다. [1]', multi_responses=None, reference='180만원입니다.', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='신상품 제안서 심사 결과 확인까지 영업일 기준으로 어느 정도 소요됩니까?', retrieved_contexts=['제안서심사결과는영업일기준5일정도소요됩니다.\n제안상품은담당MD가단독으로결정하지않고,\nMD/팀/사업부의제안상품평가를통해결정합니다.\n全방송상품/Hmal일부상품은사전품질평가를거칩니다.\n입점단계진행완료시마다영업책임자의휴대폰번호로SMS가발송됩니다.\ni', '신상품제안\n제안결과확인\n현대홈쇼핑입점프로세스STAGE 2.\nSTAGE 1\nSTAGE 2\nSTAGE 3\nSTAGE 4\nSTAGE 5\nSTAGE 6\n당사에입점하시기위해대표상품을제안하는단계로,\n귀사의대표상품하나를선정하시어제안서를작성바랍니다.\n1\nSTAGE 2\n신상품제안\nSTAGE 3\n제안결과확인및\nQA 자료등록\n제안하신상품은심사를거쳐입점여부가결정됩니다..\n제안서심사결과는영업일기준5일정도소요됩니다.\n제안상품은담당MD/팀/사업부의평가를거치며\nMD 단독으로결정하지않습니다.\n방송상품의경우MD평가+상품설명회결과+품질평가를\n종합하여최종방송여부를결정합니다.\n全방송상품/Hmal 일부상품은사전품질평가를거칩니다.\n입력\nQA 자료등록\n!\n매체단독또는복수의매체에동시지원이가능합니다.\n제안된상품은제안일기준5영업일이내에결과가등록됩니다.\n(단,담당MD의확인에따라제안서확인일자는조금씩달라질수있습니다.)\n진행단계마다영업책임자의휴대폰으로SMS가발송됩니다.\n기존입점이완료된협력사( = 협력사코드가발급된협력사) 의경우,', '입점심사진행상태\n현대홈쇼핑입점프로세스STAGE 3.\nSTAGE 1\nSTAGE 2\nSTAGE 3\nSTAGE 4\nSTAGE 5\nSTAGE 6\n상품제안일이후, 영업일기준5일이내제안결과가나옵니다.\n방송상품은상품설명회, 품질평가추가진행\nHmall/카탈로그일부상품군은품질평가추가진행\nMD 의견클릭시담당MD 의견확인가능합니다.\ni\n진행상태\n내용\nMD접수\nMD 미배정\nMD이관\n(동일매체)\nMD배정,검토中\n타매체이관\n상담요청/완료\n미채택\n제안상품미채택\n채택\n상품채택\n(※방송상품의경우, 상품설명회/ 품질평가추가진행함)\n결재완료\nMD의입점심사내용(채택/ 미채택) 에대한내부결재완료\n이링크를클릭하시면품질평가기준가이드라인을\n확인하실수있습니다.\n품질평가기준안내\n!', '입점프로세스안내\n현대홈쇼핑입점프로세스\nSTAGE 1\n협력사정보\n화면/수정하기\nSTAGE 2\n신상품제안\nSTAGE 3\n제안결과확인및\nQA 자료등록\nSTAGE 4\n전자계약서\n정보등록\nSTAGE 5\n표준거래계약서\n서명\nSTAGE 6\nID/PW 확인\n기초가입시입력했던\n협력사정보를확인및\n수정합니다.\n협력사정보입력을마친\n협력사는,최종입점완료\n까지의모든단계를\n입력,수정할수있습니다.\n계약완료후\n협력사코드가발급되면,\n계정정보및담당자정보를\n최종확인합니다.\n[ 협력사상세정보] 를\n입력하면,담당MD가\n표준거래계약서를작성\n합니다.\n①보증보험\n②통장사본\n③사업자등록증\n을해당계약서에첨부하고\n기업범용공인인증서\n( 사업자용) 로서명합니다.\n제안서결과확인후,\n입점이결정된협력사는\n계약체결을위해\n[ 협력사상세정보] 를\n입력합니다.\n제안하신상품은심사를거쳐입점여부가결정됩니다..\n제안서심사결과는영업일기준5일정도소요됩니다.\n제안상품은담당MD가단독으로결정하지않고,\nMD/팀/사업부의제안상품평가를통해결정합니다.', 'STAGE 3 제안결과확인\n현대홈쇼핑입점프로세스STAGE 3.\nSTAGE 1\nSTAGE 2\nSTAGE 3\nSTAGE 4\nSTAGE 5\nSTAGE 6\n제안하신상품의당사내부검토결과를확인합니다.\n제안하신상품의결과가나오는대로입력된영업책임자의정보로SMS가발송됩니다.\n-방송상품의경우, MD평가+상품설명회결과+품질평가결과등을종합하여방송진행여부가결정됩니다.\n-全방송상품/ Hmall 카탈로그일부상품군은사전품질평가를거칩니다.\ni\n제안일자/매체선택후조회버튼클릭\n1\n제안상품목록에서제안상태확인\n채택: MD 상담진행\n미채택: 해당상품제안프로세스종료\n2\nMD 의견확인\n채택: 상담일정안내\n미채택: 미채택불가사유안내\n3\n조회된제안상품이여기에표시됩니다\n1\n채택\n/\n미채택\n버튼클릭시\nMD 의견이\n표시됩니다\n3\n2'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='제안서 심사 결과는 영업일 기준 5일 정도 소요됩니다.[1][2][4]', multi_responses=None, reference='영업일 기준 5일 정도 소요됩니다.', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='당도를 소구하는 경우 브릭스측정자료로 추가 제출해야 하는 자료는 무엇인가요?', retrieved_contexts=['|제출 서류|세부 내용|\n|---|---|\n|수입업소사업자등록증|수입업소사업자등록증제출|\n|수입업소영업자등록증|수입업소수입판매업영업등록증제출|\n|수입서류|수입신고서, 수입신고필증, 수입신고확인증, 식물검역증제출|\n|거래명세서|수입업소- 포장업체간의거래명세서제출|\n|PL보험증권|수입업소PL보험증권|\n|한글표시사항/디자인시안|1) 반드시QA담당자와협의후진행<br>~~※~~ 임의진행후, 기준미준수시해당표시사항발주분사용불가<br>2) 사전에완충제, 보냉제등사용여부관련QA담당자사전협의|\n|합포장사진|합포장사진|\n|잔류농약검사성적서|공인시험기관성적서/ 정밀검사성적서제출|\n|브릭스측정자료(당도소구시필요)|자동당도선별기관련사진/동영상자료전달|\n|크기자료(길이, 개당중량등)|현장QA를통한원과상태조율필수진행|\n|기타인증서|유기농/무농약/GAP/지리적표시제등|', '|브릭스측정자료(당도소구시필요)|자동당도선별기관련사진/동영상자료전달|\n|크기자료(길이, 개당중량등)|현장QA를통한원과상태조율필수진행|\n|기타인증서|유기농/무농약/GAP/지리적표시제등해당상품소구포인트관<br>련인증서제출|', '|제출 서류|세부 내용|\n|---|---|\n|생산자사업자등록증|생산자단체사업자등록증제출|\n|수입업소영업자등록증|수입업소수입판매업영업등록증제출|\n|수입서류|1) 수입신고서, 수입신고필증, 수입신고확인증제출<br>2) 수입시검역증제출|\n|거래명세서|수입업소- 포장업체간의거래명세서제출|\n|PL보험증권|수입업소PL보험증권|\n|한글표시사항/디자인시안|1) 반드시QA담당자와협의후진행<br>※ 임의진행후, 기준미준수시해당표시사항발주분사용불가<br>2) 사전에완충제, 보냉제등사용여부관련QA담당자협의후진행|\n|합포장사진|합포장사진|\n|검사성적서|정밀검사성적서/ 유형별기준이다르므로, 사전QA담당자협의|\n|사이즈소구<br>(길이, 원물손질전/후중량)|1) 법적으로등재되어있는품목가능<br>2) 당사자체마련기준품목의경우, 별도담당자문의<br>3) 현장QA를통한원물상태조율필수진행|\n|기타인증서|상품소구포인트관련인증서제출|', '상표등록원부, 브랜드라이선스계약서(영문/한글본)\n법인또는개인확인서류\n첨부\n수입신고필증\n수입상품에한해제출\n입고수량파악가능해야함\n작업지시서\n상의– 가슴둘레, 총장\n/   하의– 허리둘레, 총장\n상품스펙(치수등) 측정기\n준\n부자재차트\n제품에사용되는중요부자재\n※ 사전QA 담당자와협의\n필수\n특허증/ 의장/ 디자인\n등록등\n담당자판별이어려운경우, 공증필수\n※ 사전QA 담당자와협의\n필수\n기타\n인증서/ 특정섬유\n기타희망하는소구포인트는입증자료\n(공인단체인증서, 거래명세서등)\n※ 사전QA 담당자와협의\n필수\n상품군별주요QA서류및가이드\n패\n션Q A 준비서류[ 공통]\n가이드라인內제시사항은기본적인사항으로, 상품에따라추가준수사항이있을수있습니다.\n참고용으로활용부탁드리며, 담당QA에게세부적인안내받으신후, QA준비부탁드립니다.', '|제출 서류|세부 내용|\n|---|---|\n|생산자사업자등록증|생산자단체사업자등록증제출|\n|원산지증명서|1) 최초원물채취자의증명서류인정<br>2) 농가가인증서가지고있을시, 농가의증명서류인정<br>3) 농협이관리하는경우, 농협의증명서류인정<br>4) 수확시기, 품종소구시해당내용기재후공문형태전달必|\n|원산지확약서|원산지확약서|\n|거래명세서|최초원물채취자로부터작업장(조합, 농가등) 까지의거래명세<br>서|\n|한글표시사항/디자인시안|1) 반드시QA담당자와협의후진행하며, 사전에표준규격품여<br>부확인필요<br>※ 임의진행후, 기준미준수시해당표시사항발주분사용불가<br>2) 사전에완충제, 보냉제등사용여부관련QA담당자협의후<br>진행|\n|합포장사진|합포장사진|\n|잔류농약검사성적서|공인시험기관성적서제출|\n|브릭스측정자료(당도소구시필요)|자동당도선별기관련사진/동영상자료전달|\n|크기자료(길이, 개당중량등)|현장QA를통한원과상태조율필수진행|'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='당도를 소구하는 경우 추가 제출해야 하는 자료는 **자동당도선별기관련 사진 또는 동영상 자료**입니다.[1][2][5]', multi_responses=None, reference='자동당도선별기관련 사진 또는 동영상 자료를 전달해야 합니다.', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='개인사업자가 신규 입점한 뒤 역발행 방식으로 세금계산서를 처리할 때, 상품대금 부가세를 받기 위해 매월 언제까지 인증해야 하며, 신규 입점 시 통장 사본에는 어떤 이름 표시가 필수인가?', retrieved_contexts=['|구분|내용|Col3|Col4|\n|---|---|---|---|\n|**발행방식**|**정발행**|**상품을공급하는자→ 상품을공급받는자**|**상품을공급하는자→ 상품을공급받는자**|\n|**발행방식**|**역발행**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|**상품을공급받는자(당사)가세금계산서발행**<br>**상품을공급하는자(협력사)가세금계산서승인**|\n|**마감**|**당사**|**매월1일마감세금계산서발행**|**매월1일마감세금계산서발행**|\n|**마감**|**협력사**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|**‘매월1~10일’세금계산서인증필요**<br>**※ 미인증시상품대금부가세지급불가(세무신고불가)**|', '|구분|내용|\n|---|---|\n|**사업자**<br>**등록증**|**발행일자구분없음**<br>**※ 개인사업자의경우주민등록등본(원본), 신분증사본**|\n|**통장**<br>**사본**|**당사협력사현황표에기재된사업자명표시필수(★인감날인본)**<br>**※ 개인사업자의경우대표자명과회사명함께기재가능**|\n|**이행(지급)**<br>**보증보험**|**· 일반상품군: 방송/데이터방송1천만원~, 인터넷5백만원~**<br>**· A/S상품군: 방송/데이터방송5천만원~, 인터넷1천만원~**|\n|**이행(지급)**<br>**보증보험**|**최초2년가입1년단위추가갱신/ 1년이상보증보험기간상시유지**|', '10. 정산\n○세금계산서인증\n구분\n내용\n발행방식\n정발행\n상품을공급하는자→ 상품을공급받는자\n역발행\n상품을공급받는자(당사)가세금계산서발행\n상품을공급하는자(협력사)가세금계산서승인\n마감\n당사\n매월1일마감세금계산서발행\n협력사\n‘매월1~10일’세금계산서인증필요\n※ 미인증시상품대금부가세지급불가(세무신고불가)\n부가세\n지급\n부가세금액은월1회(매월10일)인증값을기준으로마감,\n익월중순경해당월1주기상품대금과합산하여지급\n발행금액\n(배송형태별)\n물류센터입고\n물류센터입고분(당사매입분)\n직접배송\n출고분(상품대금지급대상금액)\n○정산관련파트너시스템주요화면\n화면명(번호)\n내용\n매입매출현황\n(VD603) \n협력사의기간별매입/매출내역파악\n대금지불내역\n(VD606) \n협력사의주기별정산내역확인\n공제상세현황\n(VD607)\n협력사의주기별공제항목별상세내역확인\n전자세금계산서\n(DP502) \n세금계산서종류별발행내역확인및\n세금계산서승인화면접속\n전자채권채무조회\n(AF341) \n협력사의채권채무조회서전자발급신청\n교육영상', '제출서류안내\n현대홈쇼핑입점프로세스STAGE 4.\nSTAGE 1\nSTAGE 2\nSTAGE 3\nSTAGE 4\nSTAGE 5\nSTAGE 6\n표준거래계약서체결을위해필요한서류는총3가지입니다.\n첨부파일이누락된경우계약서신뢰도하락으로체결절차재진행합니다.\n표준거래계약서협력사서명시에계약서內첨부파일업로드를통해스캔된파일을업로드해주시기바랍니다.\n일반적인이미지파일로(JPEG, PNG 등)업로드해주시기바라며,\n인식이어려울정도로너무흐리거나밝은경우제한이있을수있습니다.\n별도의용량제한은없으나일반적인수준의파일을업로드해주시기바랍니다.\n!\n제출서류\n내용\n사업자등록증1부\n사업자등록증명원혹은사업자등록증\n통장사본1부\n예금주명: [법인] 상호명과동일, [개인] 대표자, 상호명과동일\n보증보험증권사본1부\nSGI서울보증보험사이트에서가입후발급→링크', '|제출서류|내용|\n|---|---|\n|사~~업자등록증~~1~~부~~|사~~업자등록증명~~원~~혹은~~사~~업자등록증~~|\n|통장사~~본~~1~~부~~|예~~금~~주~~명~~: **[**~~**법**~~**인]** 상호~~명~~과동일,**[개인]** 대~~표~~자, 상호~~명~~과동일|\n|~~보증보험증권~~사~~본~~1~~부~~|SGI서울~~보증보험~~사~~이트에~~서가~~입~~후~~발급~~→**링크**|'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='개인사업자가 역발행 방식으로 세금계산서를 처리할 때는 **매월 1~10일 사이에 세금계산서 인증이 필요**합니다. 미인증 시 상품대금 부가세 지급이 불가합니다. [1][3]\n\n신규 입점 시 통장 사본에는 **당사 협력사 현황표에 기재된 사업자명 표시가 필수**이며, 개인사업자의 경우 **대표자명과 회사명 함께 기재 가능**합니다. [2]', multi_responses=None, reference='개인사업자가 역발행 세금계산서로 상품대금 부가세를 받으려면 매월 1~10일에 세금계산서 인증이 필요하며, 신규 입점 시 제출하는 통장 사본에는 당사 협력사 현황표에 기재된 사업자명 표시가 필수입니다.', rubrics=None, persona_name=None, query_style=None, query_length=None),
 SingleTurnSample(user_input='Hmall에서 입점 브랜드와 상품을 제휴사까지 포함해 홍보·판매할 수 있는 수단과, 담당 MD와 협의해 참여할 때 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사는 무엇인가요?', retrieved_contexts=['11. 광고/ 마케팅/ 제휴\n○현대홈쇼핑과의사업제휴및협업을희망하는협력사의많은관심부탁드립니다.\nHmall제휴\n홍보/ 브랜드마케팅\n○신규매체/플랫폼전략제휴\n○판매수수료기반CPS(Cost per sale) 제휴\n○언론홍보/보도자료\n○온라인바이럴/디지털광고\n○방송행사및대외이벤트\n○친환경캠페인\n▷담당자연락처yunsh_@hyundaihmall.com\n▷담당자연락처jhdo919@hyundaihmall.com\n퍼포먼스마케팅\nHmall내부광고\n○방송/Hmall신규광고및플랫폼제안\n○검색광고-키워드/쇼핑검색등\n○퍼포먼스광고-DA/APP/SNS\n○HmallPC/모바일광고\n○Hmall배너광고\n▷담당자연락처chasy@hyundaihmall.com\n▷담당자연락처kmsong1523377@hyundaihmall.com\n광고상품소개서바로가기', '┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n03\nHmall에 입점하면\n어떤 행사에 참여할 수 있나요?\nHmall 마케팅 부서는 매월 다양한 플랫폼 행사를 운영합니다.\n참여시 판촉 및 메인 노출 등의 지원을 받을 수\n(리워드,카드할인등)\n있습니다. 담당 MD와 협의하여 플랫폼 행사에 참여해보세요!\nHmall 주요 플랫폼행사\n매주시즌· 이슈에맞춰 단일브랜드or 연합으로\n진행하는카테고리단위행사 진행하는브랜드단위행사\n페어 브랜드줌\n매주화요일, 전상품 식품연속구매유도를위한\n추가적립프로모션 다건적립프로모션\n올-인데이 릴레이푸드\n매주금요일, 상품홍보,리뷰확보를위한\n원데이핫딜상품특가 신상품체험단\n불금데이 스마일테스터\n19', '┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n05\n오픈마켓 등 외부 사이트에\n상품을 연동할 수 있나요?\n여러 사이트에 입점할 필요 없이, Hmall과 제휴되어 있는\n오픈마켓, 복지몰 등에 상품 DB를 연동하여 판매할 수 있습니다.\n오픈마켓 메인딜 및 대형 행사 참여 기회를 잡아 보세요.\n주요DB제휴사\n·DB제휴:제휴사이트에Hmall상품및주문데이터를연동하여판매한후,\n사후에대금을정산하는방법(고객은제휴사이트에서결제함)\n구분 대표행사 대표딜 비고\n※ 제휴행사참여를원할경우담당MD와협의하세요.\n23', '|Hmall제휴|홍보 / 브랜드마케팅|Col3|\n|---|---|---|\n|**○신규매체/플랫폼전략제휴**<br>**○판매수수료기반CPS(Cost per sale) 제휴**|**○언론홍보/보도자료**<br>**○온라인바이럴/디지털광고**|**○방송행사및대외이벤트**<br>**○친환경캠페인**|\n|**▷담당자연락처yunsh_@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|**▷담당자연락처jhdo919@hyundaihmall.com**|\n|**퍼포먼스마케팅**|**Hmall내부광고**|**Hmall내부광고**|', '┐\nⅢ. PC · 모바일 · 라이브 플랫폼\n04\n행사와 상품을 알릴 수 있는\n광고 · 홍보 채널이 있나요?\nHmall 마케팅 부서는 APP PUSH, 포털 · 리타겟팅 광고, 가격\n비교 사이트 등 다양한 내 · 외부 수단을 통해 입점 브랜드 및\n상품을 홍보하고 있습니다. 또 카드사 쇼핑몰, 통신사 멤버십몰\n등 20개 이상의 제휴사에 Hmall 상품을 연동하여 판매합니다.\nHmall APPPUSH 포털배너광고\n검색광고 가격비교연동\n22'], reference_contexts=None, retrieved_context_ids=None, reference_context_ids=None, response='Hmall에서 입점 브랜드와 상품을 홍보·판매할 수 있는 수단은 다음입니다.  \n- APP PUSH, 포털·리타겟팅 광고, 가격비교 사이트 등 내·외부 홍보 수단 [5]  \n- 카드사 쇼핑몰, 통신사 멤버십몰 등 20개 이상의 제휴사에 Hmall 상품을 연동해 판매하는 방식 [5]  \n- 오픈마켓, 복지몰 등 외부 사이트에 상품 DB를 연동해 판매하는 DB 제휴 [3]  \n- 신규매체/플랫폼 전략 제휴, CPS(Cost per sale) 제휴 [1][4]  \n- 언론홍보/보도자료, 온라인 바이럴/디지털 광고, 방송행사 및 대외이벤트, 친환경캠페인 [1][4]  \n- 검색광고(키워드/쇼핑검색), 퍼포먼스 광고(DA/APP/SNS), Hmall PC/모바일 광고, Hmall 배너광고 [1]\n\n담당 MD와 협의해 참여할 수 있고, 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사는 다음입니다.  \n- 페어 [2]  \n- 브랜드줌 [2]  \n- 올-인데이 [2]  \n- 릴레이푸드 [2]  \n- 불금데이 [2]  \n- 스마일테스터 [2]\n\n제휴사까지 포함해 홍보·판매할 수 있는 수단과, 판촉 및 메인 노출 지원을 받을 수 있는 행사에 대한 정보는 위와 같습니다. [2][3][5]', multi_responses=None, reference='입점 브랜드와 상품은 APP PUSH, 포털·리타겟팅 광고, 가격비교 사이트와 같은 내·외부 수단으로 홍보할 수 있고, 카드사 쇼핑몰·통신사 멤버십몰 등 20개 이상의 제휴사에도 연동되어 판매됩니다. 또한 담당 MD와 협의해 참여할 수 있으며 판촉 및 메인 노출 등의 지원을 받을 수 있는 플랫폼 행사로는 페어, 브랜드줌, 올-인데이, 릴레이푸드, 불금데이, 스마일테스터가 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None),

In [ ]:
# 계산형_커스텀 메트릭1 : 답변에 인용 표현 유무
import re
import typing as t
from dataclasses import dataclass, field

from ragas.metrics.base import MetricType, MetricWithLLM, SingleTurnMetric


@dataclass
class CitationFormat(SingleTurnMetric):
    name: str = "citation_format"
    _required_columns: t.Dict[MetricType, t.Set[str]] = field(
        default_factory=lambda: {MetricType.SINGLE_TURN: {"response"}})

    def init(self, run_config):
        pass

    async def _single_turn_ascore(self, sample, callbacks) -> float:    # 1이면 있는 것, 0이면 없는 것 - 쪽수가 포함되어있는가 여부 (무답변일 땐 없는게 정상)
        return 1.0 if re.search(r"\[\d+\]", sample.response) else 0.0

In [162]:
print(await CitationFormat().single_turn_ascore(samples[0]))

1.0

In [179]:
# LLM판정형_커스텀 메트릭2 : 업무영향도
from enum import Enum
from pydantic import BaseModel, Field

class RiskLevel(str, Enum):
    NONE = "0"
    MINOR = "1"
    MAJOR = "2"
    CRITICAL = "3"

class BusinessRisk(BaseModel):
    risk_level: RiskLevel = Field(
        description="답변 오류가 실제 업무에 미치는 위험 수준"
    )
    reason: str = Field(
        description="해당 위험 수준으로 판단한 근거"
    )

@dataclass
class BusinessSafetyScore(MetricWithLLM, SingleTurnMetric):
    name: str = "business_safety_score"

    _required_columns: t.Dict[MetricType, t.Set[str]] = field(
        default_factory=lambda: {
            MetricType.SINGLE_TURN: {
                "user_input",
                "response",
                "reference",
            }
        }
    )

    debug_results: list = field(default_factory=list)

    async def _single_turn_ascore(self, sample, callbacks) -> float:
        judge = self.llm.langchain_llm.with_structured_output(BusinessRisk)

        prompt = f"""
                    당신은 홈쇼핑 업무 매뉴얼 기반 RAG 시스템의 평가자입니다.

                    질문과 정답(reference)을 기준으로 답변(response)의 오류가
                    실제 업무 수행에 미치는 위험 수준을 평가하십시오.

                    판정 기준:

                    NONE (0):
                    핵심 업무 정보가 정확하며 업무 수행에 문제가 없다.

                    MINOR (1):
                    사소한 누락이나 표현상의 부정확성이 있으나
                    실제 업무 수행 결과에는 실질적인 영향이 없다.

                    MAJOR (2):
                    중요 정보의 누락 또는 잘못된 정보로 인해
                    사용자가 잘못된 업무를 수행할 가능성이 있다.

                    CRITICAL (3):
                    핵심 정책, 필수 절차, 금지사항 등을 잘못 안내하여
                    심각한 업무 오류를 발생시킬 가능성이 있다.

                    질문:
                    {sample.user_input}

                    정답:
                    {sample.reference}

                    답변:
                    {sample.response}

                    답변의 업무 위험 수준을 판단하십시오.
                    """

        out = await judge.ainvoke(prompt, config={"callbacks": [usage]})
        
        risk_score = int(out.risk_level.value) / 3
        safety_score = 1 - risk_score

        # 판정 과정 저장
        self.debug_results.append({
            "question": sample.user_input,
            "reference": sample.reference,
            "response": sample.response,
            "prompt": prompt,
            "risk_level": out.risk_level,
            "reason": out.reason,
            "score": score,
        })

        return safety_score

In [190]:
business_safety = BusinessSafetyScore(llm=ragas_llm)
print(await business_safety.single_turn_ascore(samples[14]))

0.6666666666666667

In [191]:
business_safety.debug_results

[{'question': '방송상품 판매 전에 품질 적합성과 리스크 확인을 위해 진행하는 절차는 무엇인가요, 그리고 Hmall 상품은 같은 절차를 따르나요?',
  'reference': '방송상품 판매 전에는 QA를 진행합니다. 방송상품 QA 프로세스는 QA 의뢰, QA 자료 업로드, QA 검토, 합격/불합격, 방송 진행, 사후관리, 검사, 합격/불합격 순서로 안내되어 있습니다. Hmall 상품은 별도의 프로세스를 따르며, 등록된 웹기술서를 토대로 QA(심의)를 진행합니다.',
  'response': '방송상품 판매 전에는 **QA(품질 적합성 및 리스크 확인)** 를 진행합니다. 이 과정은 **QA 의뢰 → QA 자료 업로드 → QA 검토 → 합격/불합격** 순으로 진행됩니다. [2]\n\n**Hmall 상품은 별도의 프로세스를 따르며**, 등록된 **웹기술서를 토대로 QA(심의)** 를 진행합니다. 따라서 방송상품과 동일한 절차를 그대로 따르지는 않습니다. [2]',
  'prompt': '\n                    당신은 홈쇼핑 업무 매뉴얼 기반 RAG 시스템의 평가자입니다.\n\n                    질문과 정답(reference)을 기준으로 답변(response)의 오류가\n                    실제 업무 수행에 미치는 위험 수준을 평가하십시오.\n\n                    판정 기준:\n\n                    NONE (0):\n                    핵심 업무 정보가 정확하며 업무 수행에 문제가 없다.\n\n                    MINOR (1):\n                    사소한 누락이나 표현상의 부정확성이 있으나\n                    실제 업무 수행 결과에는 실질적인 영향이 없다.\n\n                    MAJOR (2):\n                    중요 정보의 누락 또는 잘못된 정보로 인해\n                    사용자가 잘못된 업무를 수행할 가능성이 있다.\n\n                    CRITICAL (3):\n                    핵심 정책, 필수 절차, 금지사항 등을 잘못 안내하여\n                    심각한 업무 오류를 발생시킬 가능성이 있다.\n\n                    질문:\n                    방송상품 판매 전에 품질 적합성과 리스크 확인을 위해 진행하는 절차는 무엇인가요, 그리고 Hmall 상품은 같은 절차를 따르나요?\n\n                    정답:\n                    방송상품 판매 전에는 QA를 진행합니다. 방송상품 QA 프로세스는 QA 의뢰, QA 자료 업로드, QA 검토, 합격/불합격, 방송 진행, 사후관리, 검사, 합격/불합격 순서로 안내되어 있습니다. Hmall 상품은 별도의 프로세스를 따르며, 등록된 웹기술서를 토대로 QA(심의)를 진행합니다.\n\n                    답변:\n                    방송상품 판매 전에는 **QA(품질 적합성 및 리스크 확인)** 를 진행합니다. 이 과정은 **QA 의뢰 → QA 자료 업로드 → QA 검토 → 합격/불합격** 순으로 진행됩니다. [2]\n\n**Hmall 상품은 별도의 프로세스를 따르며**, 등록된 **웹기술서를 토대로 QA(심의)** 를 진행합니다. 따라서 방송상품과 동일한 절차를 그대로 따르지는 않습니다. [2]\n\n                    답변의 업무 위험 수준을 판단하십시오.\n                    ',
  'risk_level': <RiskLevel.MINOR: '1'>,
  'reason': '답변은 방송상품 QA와 Hmall 상품의 처리 방식이라는 핵심 방향을 모두 맞게 설명하고 있습니다. 다만 정답에 있는 방송상품 QA의 전체 절차(방송 진행, 사후관리, 검사, 추가 합격/불합격 단계)가 일부 누락되어 있어 세부 프로세스 안내로는 불완전합니다. 그러나 실제 업무를 잘못 수행하게 할 정도의 오류는 아니므로 MINOR 수준입니다.',
  'score': <function __main__.score(name, fetch, questions)>}]

In [185]:
custom = [CitationFormat(), BusinessSafetyScore()]
extra = evaluate(dataset, metrics=custom, llm=ragas_llm, callbacks=[usage]).to_pandas()
for m in custom:
    table[m.name] = extra[m.name]
table.set_index("id")[METRIC_COLS + [m.name for m in custom]].round(3)

Evaluating: 100%|██████████| 40/40 [00:02<00:00, 17.04it/s]

,faithfulness,answer_relevancy,llm_context_precision_with_reference,context_recall,citation_format,business_safety_score
id,,,,,,
manual-001,1.000,0.931,1.000,1.0,1.0,1.000
manual-002,1.000,0.995,1.000,1.0,1.0,1.000
manual-003,1.000,0.721,1.000,1.0,1.0,0.667
manual-004,1.000,0.702,1.000,1.0,1.0,1.000
manual-005,1.000,0.521,1.000,1.0,1.0,1.000
manual-006,1.000,0.820,0.867,1.0,1.0,1.000
manual-007,0.750,0.603,1.000,1.0,1.0,1.000
manual-008,1.000,0.751,0.887,1.0,1.0,1.000
manual-009,0.833,0.327,1.000,1.0,1.0,1.000
manual-010,1.000,0.509,0.887,1.0,1.0,1.000
manual-011,1.000,0.890,1.000,1.0,1.0,1.000
manual-012,1.000,0.951,1.000,1.0,1.0,1.000
manual-013,0.250,0.890,0.917,1.0,1.0,1.000
manual-014,1.000,0.913,0.500,1.0,1.0,1.000
manual-015,0.800,0.631,0.450,1.0,1.0,0.667
manual-016,1.000,0.807,0.500,1.0,1.0,1.000
manual-017,1.000,0.798,0.867,1.0,1.0,1.000
manual-018,0.000,0.000,0.500,0.0,0.0,1.000
manual-019,1.000,0.000,1.000,0.0,0.0,1.000
manual-020,1.000,0.000,0.000,0.0,0.0,1.000

In [193]:
# 지표 변동성 확인
import asyncio

probe = samples
for metric in [CitationFormat(), BusinessSafetyScore(llm=ragas_llm)]:
    runs = [await asyncio.gather(*[metric.single_turn_ascore(s) for s in probe]) for _ in range(3)]
    spread = [round(max(col) - min(col), 3) for col in zip(*runs)]
    print(f"{metric.name:22} 1회차 {[round(v, 2) for v in runs[0]]}  문항별 폭 {spread}")

citation_format        1회차 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]  문항별 폭 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
business_safety_score  1회차 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.67, 1.0, 1.0, 1.0, 1.0, 1.0]  문항별 폭 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

<h3>4. pre-retrieval 패턴 적용</h3>

- 쿼리 재작성 : 검색에 맞는 문장으로 고침
- 쿼리 분해 : 여러 질의로 쪼개서 검색
- HyDE : 가짜 답변 생성
- step-back : 일반화한 질문으로 바꿔 배경 찾기
- 쿼리 확장 : 동의어와 관련 용어 덧붙이기
- 메타데이터 라우팅 : 질의를 바꾸지 않고 검색 범위를 줄임

In [20]:
import hashlib
from pathlib import Path
import time
import json
from langchain_core.prompts import ChatPromptTemplate

CACHE = Path("cache")
CACHE.mkdir(exist_ok=True)

PDF_LIST = sorted(Path(PDF_DIR).glob("*.pdf"))
PDF_CONFIGS = {
    "manual/1. 협력사 운영 통합 안내서 (p.23).pdf": "pymupdf_markdown",
    "manual/2. Hmall 소개서 (p.30).pdf": "pdfplumber",
    "manual/4. 광고 상품 소개서 (p.24).pdf": "pdfplumber",
    "manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf": "pymupdf_markdown",
    "manual/7. 데이터 영역 광고 제안서 (p.8).pdf": "pymupdf_markdown",
    "manual/8. QA가이드 (p.21).pdf": "pymupdf_markdown",
}

# 청크와 리트리버를 만들어 리턴
def create_chunks(chunk_size, chunk_overlap) :
    for pdf_idx, pdf_path in enumerate(PDF_LIST):
        pdf_path = str(pdf_path)
        if pdf_path not in PDF_CONFIGS:
            continue

        method = PDF_CONFIGS[pdf_path]

        # 1. PDF별 로딩
        print(pdf_path)
        if method == "pymupdf_markdown":
            docs = load_pymupdf_markdown(pdf_path)

        elif method == "pdfplumber":
            docs = load_pdfplumber(pdf_path)

        # 2. PDF 특성에 맞게 청킹
        rec_chunk = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        ).split_documents(docs)

        # 3. metadata 추가
        for chunk in rec_chunk:
            chunk.metadata["source"] = pdf_path.split("manual/", 1)[1]
            chunk.metadata["loader"] = method

        chunks.extend(rec_chunk)

    return chunks      

def build(config, chunks):
    #chunks = create_chunks(chunk_size=config["chunk_size"], chunk_overlap=config["chunk_overlap"])
    if config["retriever"] == "bm25":
        bm = BM25Retriever.from_documents(chunks)
        bm.k = config["k"]
        return chunks, bm
    store = FAISS.from_documents(chunks, embeddings)
    kind = "mmr" if config["retriever"] == "mmr" else "similarity"
    return chunks, store.as_retriever(search_type=kind, search_kwargs={"k": config["k"]})

# invoke 및 golden을 가지고 답변을 기록 (config만 바꾸면 반복적으로 평가 가능)
def run(config, chunks, retriever=None):
    golden = [json.loads(line) for line in open(config["golden"], encoding="utf-8")]
    chunks, default = build(config, chunks)
    retriever = default if retriever is None else retriever  # Part 4 는 자기 검색기를 넣는다
    chain = ChatPromptTemplate.from_messages([("system", config["prompt"]),
                                              ("human", "근거\n{context}\n\n질문\n{question}")]) | ChatOpenAI(model=config["model"])
    rows = []
    for g in golden:
        key = hashlib.sha1(json.dumps([config, g["id"]], sort_keys=True, ensure_ascii=False).encode()).hexdigest()
        cached = CACHE / f"{key}.json"
        if cached.exists():
            rows.append(json.loads(cached.read_text(encoding="utf-8")))
            continue
        docs = retriever.invoke(g["question"])
        t0 = time.perf_counter()
        msg = chain.invoke({"context": "\n\n".join(d.page_content for d in docs), "question": g["question"]},
                           config={"callbacks": [usage]})
        row = {"run": config["name"], "id": g["id"], "type": g["type"], "answerable": g["answerable"],
               "answer": msg.content, "contexts": [d.page_content for d in docs],
               "latency": round(time.perf_counter() - t0, 2),
               "input_tokens": msg.usage_metadata["input_tokens"],
               "output_tokens": msg.usage_metadata["output_tokens"]}
        cached.write_text(json.dumps(row, ensure_ascii=False), encoding="utf-8")
        rows.append(row)
    return golden, chunks, rows

In [14]:
import math


import pandas as pd


def squash(s):
    return "".join(s.split())


def is_evidence(text, record):
    return any(squash(q) in squash(text) for q in record["evidence_quotes"])


def mrr(rel):
    return next((1 / (i + 1) for i, r in enumerate(rel) if r), 0.0)


def ndcg(rel, n):
    dcg = sum(r / math.log2(i + 2) for i, r in enumerate(rel))
    ideal = sum(1 / math.log2(i + 2) for i in range(min(n, len(rel))))
    return dcg / ideal if ideal else float("nan")

# 실행이 언제 + hit, recall, mrr과 같은 수치들 체크하여 데이터프레임으로 만듦
def grade(golden, chunks, rows):
    total = {g["id"]: sum(is_evidence(c.page_content, g) for c in chunks) for g in golden if g["answerable"]}
    out = []
    for row, g in zip(rows, golden):
        rel = [int(is_evidence(t, g)) for t in row["contexts"]] if g["answerable"] else []
        n = total.get(g["id"], 0)
        out.append({"run": row["run"], "id": row["id"], "type": row["type"], "answerable": row["answerable"],
                    "hit": float(any(rel)) if rel else float("nan"),
                    "recall": sum(rel) / min(n, len(rel)) if rel and n else float("nan"),
                    "mrr": mrr(rel) if rel else float("nan"),
                    "ndcg": ndcg(rel, n) if rel and n else float("nan"),
                    "abstained": "문서에 없음" in row["answer"],
                    "latency": row["latency"], "input_tokens": row["input_tokens"],
                    "output_tokens": row["output_tokens"], "answer": row["answer"]})
    return pd.DataFrame(out)

# 데이터프레임을 받아서 각 구동에 대한 점수와 비용을 집계
def summarize(df, config):
    ok = df[df["answerable"]]
    cost = (df["input_tokens"].sum() / 1e6 * PRICES[config["model"]][0]
            + df["output_tokens"].sum() / 1e6 * PRICES[config["model"]][1])
    return {"run": config["name"], "hit": ok["hit"].mean(), "recall": ok["recall"].mean(),
            "mrr": ok["mrr"].mean(), "ndcg": ok["ndcg"].mean(),
            "기권율": df[~df["answerable"]]["abstained"].mean(),
            "오기권": ok["abstained"].mean(), "지연": df["latency"].mean(), "USD": cost}

In [21]:
PROMPT = "근거만으로 답한다. 근거에 없으면 '문서에 없음' 이라고 답한다."
BASE = {"name": "base", "chunk_size": 500, "chunk_overlap": 80, "k": 5,
        "retriever": "vector", "model": LOWER, "prompt": PROMPT, "golden": GOLDEN}
chunks = create_chunks(chunk_size=BASE["chunk_size"], chunk_overlap=BASE["chunk_overlap"])


golden, chunks, rows = run(BASE, chunks)
frames = {"base": grade(golden, chunks, rows)}
results = [summarize(frames["base"], BASE)]
print({k: round(v, 3) if isinstance(v, float) else v for k, v in results[0].items()})

#base_retriever = store.as_retriever(search_kwargs={"k": BASE["k"]})

manual/1. 협력사 운영 통합 안내서 (p.23).pdf
manual/2. Hmall 소개서 (p.30).pdf
manual/4. 광고 상품 소개서 (p.24).pdf
manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf
manual/7. 데이터 영역 광고 제안서 (p.8).pdf
manual/8. QA가이드 (p.21).pdf
{'run': 'base', 'hit': np.float64(0.765), 'recall': np.float64(0.569), 'mrr': np.float64(0.529), 'ndcg': np.float64(0.526), '기권율': np.float64(1.0), '오기권': np.float64(0.059), '지연': np.float64(1.038), 'USD': np.float64(0.026)}

In [22]:
base_retriever = store.as_retriever(search_kwargs={"k": BASE["k"]})

In [224]:
# 쿼리 재작성
rewrite_prompt = ChatPromptTemplate.from_messages([
    ("system", """
당신은 현대홈쇼핑 협력사용 매뉴얼 검색을 위한 질의 재작성기입니다.
사용자의 질문을 매뉴얼에서 관련 내용을 찾기 쉬운 하나의 검색 질의로 바꾸세요.

규칙:
- 원본 질문의 의도와 범위를 그대로 유지하세요.
- 검색에 도움이 되도록 핵심 대상, 업무, 메뉴, 절차를 명확히 표현하세요.
- 원본에 없는 상황, 조건, 원인, 정책을 추측해 추가하지 마세요.
- 시스템명, 메뉴명, 업무 용어, 약어는 원본 표현을 우선 보존하세요.
- 질문에 이미 드러난 맥락만 사용해 독립적으로 이해할 수 있는 질의로 작성하세요.
- 답변, 설명, 서문, 따옴표 없이 재작성한 질의만 출력하세요.
"""),
    ("human", "원본 질문: {query}")
])
rewrite = rewrite_prompt | llm | StrOutputParser()
rewrite_retriever = rewrite | base_retriever

print("원본 : ", golden[6]["question"])
print("재작성 : ", rewrite.invoke({"query": golden[6]["question"]}, config={"callbacks": []}))

원본 :  개인사업자가 신규 입점한 뒤 역발행 방식으로 세금계산서를 처리할 때, 상품대금 부가세를 받기 위해 매월 언제까지 인증해야 하며, 신규 입점 시 통장 사본에는 어떤 이름 표시가 필수인가?
재작성 :  개인사업자 신규 입점 후 역발행 방식 세금계산서 처리 시 상품대금 부가세 수령을 위한 월별 인증 기한과 신규 입점 시 통장 사본에 필수로 표시해야 하는 이름

In [231]:
# 쿼리 분해
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda


class Queries(BaseModel):
    queries: list[str] = Field(
        description="원본 질문의 답을 찾기 위한 검색 질의 목록"
    )


decompose = (
    ChatPromptTemplate.from_template("""
당신은 현대홈쇼핑 협력사용 매뉴얼 RAG 검색을 위한 질의 분해기입니다.
원본 질문에 답하는 데 필요한 검색 질의를 작성하세요.

판단 기준:
- 서로 다른 정보나 절차를 둘 이상 찾아야 답할 수 있다면 질의를 분해하세요.
- 여러 대상이나 조건을 비교하거나 각각 확인해야 한다면 질의를 분해하세요.
- 하나의 정보만 찾으면 답할 수 있는 질문은 분해하지 마세요.
- 질문이 길거나 복합문이라는 이유만으로 분해하지 마세요.

작성 규칙:
- 분해가 필요하면 답변에 필요한 최소한의 질의만 작성하세요. 2~5개로 제한합니다.
- 분해가 필요하지 않으면 검색 질의 하나만 작성하세요.
- 각 질의는 매뉴얼에서 독립적으로 검색할 수 있게 구체적으로 작성하세요.
- 원본의 업체, 업무, 시점, 조건, 시스템명, 메뉴명, 약어를 보존하세요.
- 원본에 없는 사실이나 조건을 추측해 추가하지 마세요.
- 답변이나 설명은 출력하지 말고, 지정된 구조의 검색 질의 목록만 반환하세요.

원본 질문:
{query}
""")
    | llm.with_structured_output(Queries)
)


def dedupe(docs, k=None):
    if k is None:
        k = BASE["k"]

    seen = set()
    out = []

    for doc in docs:
        if doc.page_content not in seen:
            seen.add(doc.page_content)
            out.append(doc)

    return out[:k]


def retrieve_for_queries(result):
    docs = []

    for query in result.queries:
        docs.extend(base_retriever.invoke(query))

    return dedupe(docs)


multi_retriever = decompose | RunnableLambda(retrieve_for_queries)

print("원본 : ", golden[9]["question"])
print("쿼리 분해 : ", decompose.invoke({"query": golden[9]["question"]}, config={"callbacks": [usage]}).queries)

원본 :  PSD 가이드파일이 공유되고 수정 가능한 항목이 이미지, 소구포인트, 상품명, 가격, 상품코드, 간편번호로 안내된 형식과, 레이아웃이 자유형식이지만 제작 전 이미지 내 기재 텍스트 내용을 사전협의해야 하는 형식의 공통 파일포맷과 소재전달일은 무엇인가?
쿼리 분해 :  ['PSD 가이드파일 공통 파일포맷 소재전달일', 'PSD 가이드파일 이미지 소구포인트 상품명 가격 상품코드 간편번호 공유 수정 가능한 항목 형식', 'PSD 가이드파일 레이아웃 자유형식 제작 전 이미지 내 기재 텍스트 내용 사전협의 형식']

In [235]:
# HyDE
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

hyde = (
    ChatPromptTemplate.from_messages([
        ("system", """다음 질문에 대한 답변을 두 문장으로 지어낸다. 사실 여부는 상관없고 가이드 문서에 맞는 문체로 쓴다."""),
        ("human", "질문: {query}")
    ]) | llm | StrOutputParser()
)
hyde_retriever = hyde | base_retriever

print("원본 : ", golden[2]["question"])
print("HyDE : ", hyde.invoke({"query": golden[2]["question"]}, config={"callbacks": [usage]}))

원본 :  플랫폼행사는 Hmall의 어느 영역에 노출되는가?
HyDE :  플랫폼행사는 Hmall 메인 및 관련 프로모션 영역에 노출됩니다. 또한 행사 성격에 따라 카테고리 진입부나 배너 지면에서도 함께 노출될 수 있습니다.

In [240]:
# Step-back
stepback = ChatPromptTemplate.from_template(
    "다음 질문의 배경이 되는 더 일반적인 질문 하나로 바꾼다. 질문만 출력한다.\n\n{query}"
) | llm | StrOutputParser()
stepback_retriever = RunnableLambda(
    lambda q: dedupe(base_retriever.invoke(q) + base_retriever.invoke(stepback.invoke({"query": q}))))

print("원본 : ", golden[9]["question"])
print("stepback : ", stepback.invoke({"query": golden[9]["question"]}, config={"callbacks": [usage]}))

원본 :  PSD 가이드파일이 공유되고 수정 가능한 항목이 이미지, 소구포인트, 상품명, 가격, 상품코드, 간편번호로 안내된 형식과, 레이아웃이 자유형식이지만 제작 전 이미지 내 기재 텍스트 내용을 사전협의해야 하는 형식의 공통 파일포맷과 소재전달일은 무엇인가?
stepback :  일반적인 질문: 서로 다른 두 작업 형식에서 공통으로 적용되는 파일 포맷과 소재 전달일은 어떻게 정의되는가?

In [244]:
# 쿼리 확장
expand = ChatPromptTemplate.from_template(
    """
너는 홈쇼핑 협력사용 매뉴얼 검색을 위한 질의 확장기다.

사용자 질의의 원문은 한 글자도 수정하지 말고 그대로 유지한다.
원문 뒤에 홈쇼핑 협력사 업무와 관련된 동의어 또는 관련 용어를 최대 5개까지 덧붙인다.

관련 용어는 다음 업무 영역을 우선 고려한다.
- 상품 등록/수정/승인/QA
- 방송 편성 및 판매
- 주문/취소/교환/반품
- 정산/수수료/세금계산서
- 광고/프로모션할인/쿠폰
- 협력사 시스템/입점

매뉴얼에서 사용될 법한 업무 용어를 우선 사용하고,
질의에 없는 상품명/오류 코드/원인을 임의로 만들어내지 않는다.
질의에 대한 답변이나 설명은 작성하지 않는다.
원문과 확장 용어를 한 줄로만 출력한다.

출력 형식:
원문 확장용어1 확장용어2 확장용어3 ...

사용자 질의:
{query}
"""
) | llm | StrOutputParser()

expand_retriever = expand | base_retriever

print("원본 : ", golden[4]["question"])
print("expand : ", expand.invoke({"query": golden[4]["question"]}, config={"callbacks": [usage]}))

원본 :  신상품 제안서 심사 결과 확인까지 영업일 기준으로 어느 정도 소요됩니까?
expand :  신상품 제안서 심사 결과 확인까지 영업일 기준으로 어느 정도 소요됩니까? 상품등록 승인 QA 입점심사 상품심사

In [246]:
# 메타데이터 라우팅 : 추가 확인 필요

기법 확인

In [261]:
TECHNIQUES = {"rewrite": rewrite_retriever, "multi_query": multi_retriever, "hyde": hyde_retriever,
              "step_back": stepback_retriever, "expand": expand_retriever}
chunks = create_chunks(chunk_size=BASE["chunk_size"], chunk_overlap=BASE["chunk_overlap"])

for name, retriever in TECHNIQUES.items():
    config = {**BASE, "name": name}
    golden, chunks, rows = run(config, chunks, retriever=retriever)
    frames[name] = grade(golden, chunks, rows)
    results.append(summarize(frames[name], config))
    print(name, "완료")

manual/1. 협력사 운영 통합 안내서 (p.23).pdf
manual/2. Hmall 소개서 (p.30).pdf
manual/4. 광고 상품 소개서 (p.24).pdf
manual/6. 신규 협력사 입점 절차 안내 (p.21).pdf
manual/7. 데이터 영역 광고 제안서 (p.8).pdf
manual/8. QA가이드 (p.21).pdf
rewrite 완료
multi_query 완료
hyde 완료
step_back 완료
expand 완료

In [262]:
board = pd.DataFrame(results).set_index("run").round(3)
board[["hit", "recall", "mrr", "ndcg", "오기권", "지연", "USD"]].sort_values("mrr", ascending=False)

               hit  recall    mrr   ndcg    오기권     지연    USD
run
step_back    1.000   0.306  0.678  0.351  0.000  1.086  0.029
rewrite      0.941   0.282  0.646  0.331  0.118  0.946  0.027
multi_query  0.824   0.259  0.642  0.313  0.235  1.089  0.028
expand       0.941   0.282  0.624  0.316  0.176  1.024  0.028
hyde         0.941   0.294  0.595  0.321  0.118  1.134  0.029
base         0.765   0.482  0.529  0.478  0.059  1.038  0.026

In [263]:
def regression(other, metric="mrr"):
    a = frames["base"].set_index("id")[metric]
    b = frames[other].set_index("id")[metric]
    diff = (b - a).dropna()
    return {"기법": other, "평균차": round(diff.mean(), 3),
            "좋아짐": int((diff > 0).sum()), "나빠짐": int((diff < 0).sum())}

pd.DataFrame([regression(n) for n in TECHNIQUES]).set_index("기법")

               평균차  좋아짐  나빠짐
기법
rewrite      0.117    7    0
multi_query  0.113    6    3
hyde         0.066    8    3
step_back    0.149    9    0
expand       0.094    8    2

In [264]:
by_type = pd.DataFrame([{"기법": n, **frames[n].groupby("type")["mrr"].mean().round(3).to_dict()}
                        for n in ["base", *TECHNIQUES]]).set_index("기법")
by_type

               단일홉    멀티홉  무답변    절차     조건     집계
기법
base         0.867  0.250  NaN  0.20  0.200  0.667
rewrite      0.917  0.508  NaN  0.50  0.225  0.667
multi_query  1.000  0.479  NaN  0.25  0.000  0.833
hyde         0.806  0.425  NaN  0.25  0.625  0.611
step_back    0.917  0.446  NaN  0.50  0.500  0.750
expand       0.833  0.488  NaN  0.35  0.625  0.567

결론
- rewrite : hit, mrr 개선 + 지연 감소 + 비용 비슷 => 정답근거를 높은 순위로 가져올 수 있음 (단, recall은 하락하여 폭넓게 가져오는 건 약해짐)
- step-back : hit, mrr nDCG 개선 => 검색 성능 극대화에 가장 좋음 BUT 지연 증가는 있음

</br>
=> 최종적으로 4개의 후보 비교 예정
① Base
② Rewrite
③ Step-back
④ Rewrite → Step-back

<h3>5. retrieval 패턴 적용</h3>

- 직접 구현 hybrid (rrf = 역순위융합 = 여러 검색기가 낸 순위 목록을 하나로 합치는 방법)
- EnsembleRetriever
- parent-document
- sentence-window
- auto-merging
- 다중 인덱스

In [271]:
# hybrid rrf
from langchain_community.retrievers import BM25Retriever
from langchain_core.runnables import RunnableLambda

bm25 = BM25Retriever.from_documents(chunks)
bm25.k = 10
dense = store.as_retriever(search_kwargs={"k": 10})

def rrf(rankings, k=60, top=BASE["k"]):
    scores, keep = {}, {}
    for docs in rankings:
        for rank, d in enumerate(docs):
            scores[d.page_content] = scores.get(d.page_content, 0) + 1 / (k + rank + 1)
            keep[d.page_content] = d
    best = sorted(scores, key=scores.get, reverse=True)[:top]
    return [keep[c] for c in best]

hybrid = RunnableLambda(lambda q: rrf([dense.invoke(q), bm25.invoke(q)]))

print([d.metadata["page"] for d in base_retriever.invoke(golden[2]["question"])])
print([d.metadata["page"] for d in hybrid.invoke(golden[2]["question"])])

[18, 19, 21, 1, 29]
[9, 1, 18, 19, 21]

In [274]:
# EnsembleRetriever
from langchain_classic.retrievers import EnsembleRetriever

ensemble = EnsembleRetriever(retrievers=[dense, bm25], weights=[0.5, 0.5])
q = golden[2]["question"]
print("직접 구현  ", [d.metadata["page"] for d in hybrid.invoke(q)])
print("Ensemble  ", [d.metadata["page"] for d in ensemble.invoke(q)][:BASE["k"]])

ensemble_top = RunnableLambda(lambda x: ensemble.invoke(x)[:BASE["k"]])

직접 구현   [9, 1, 18, 19, 21]
Ensemble   [9, 1, 18, 19, 21]

In [278]:
# parent-documnet
parents = RecursiveCharacterTextSplitter(chunk_size=1500, chunk_overlap=0).split_documents(docs)
children = []
for pid, parent in enumerate(parents):
    for child in RecursiveCharacterTextSplitter(chunk_size=250, chunk_overlap=40).split_documents([parent]):
        child.metadata["parent_id"] = pid
        children.append(child)

child_store = FAISS.from_documents(children, embeddings)
print(len(parents), "부모", len(children), "자식")

def small_to_big(q, k=BASE["k"]):
    hits = child_store.similarity_search(q, k=k * 2)
    ids, out = [], []
    for h in hits:
        pid = h.metadata["parent_id"]
        if pid not in ids:
            ids.append(pid)
            out.append(parents[pid])
    return out[:k]

q = golden[2]["question"]
print([d.metadata["page"] for d in small_to_big(q)])

61 부모 263 자식
[34, 6, 0, 3, 9]

In [284]:
# sentence-window
import re

from langchain_core.documents import Document

sentences = []
for page in docs:
    parts = [s.strip() for s in re.split(r"(?<=다[.!?])\s+", page.page_content) if len(s.strip()) > 15]
    for i, s in enumerate(parts):
        sentences.append(Document(page_content=s, metadata={**page.metadata, "pos": i, "page_key": page.metadata["page"]}))
print(len(sentences), "문장")

sentence_store = FAISS.from_documents(sentences, embeddings)
by_page = {}
for s in sentences:
    by_page.setdefault(s.metadata["page_key"], []).append(s)

def sentence_window(q, k=BASE["k"], window=2):
    out = []
    for hit in sentence_store.similarity_search(q, k=k):
        siblings = by_page[hit.metadata["page_key"]]
        lo = max(0, hit.metadata["pos"] - window)
        text = " ".join(s.page_content for s in siblings[lo:hit.metadata["pos"] + window + 1])
        out.append(Document(page_content=text, metadata=hit.metadata))
    return out    

q = golden[1]["question"]
print(sentence_window(q)[0].page_content)

84 문장
해외제조사방문품질점검지원
상품군
협약기관
식품
한국식품과학연구원
이미용
뷰로베리타스
현대홈쇼핑품질연구소협력사주요지원제도
해외제조사방문품질점검지원· 전문기관연계제조사품질관리컨설팅지원
전문기관연계제조사품질관리컨설팅지원
• 대
상
- 대물량패션상품운영중소협력사
- 해외제조사품질점검희망협력사
• 지원내용
- 당사현장전담직원출장지원
- 현지전문기관연계검사지원(협약기관: KATRI 시험연구원, FITI 시험연구원)
• 대
상
• 지원내용
- 전문기관연계하여제조현장품질관리
- Process 개선컨설팅진행
- 고위험상품군(식품, 이미용품등) 운영중소협력사


|상품군|협약기관|
|---|---|

In [287]:
# auto-merging
from collections import Counter


def auto_merge(q, k=BASE["k"], threshold=2):
    hits = child_store.similarity_search(q, k=k * 3)
    counts = Counter(h.metadata["parent_id"] for h in hits)
    out, used = [], set()
    for h in hits:
        pid = h.metadata["parent_id"]
        if pid in used:
            continue
        used.add(pid)
        out.append(parents[pid] if counts[pid] >= threshold else h)
    return out[:k]

q = golden[0]["question"]
merged = auto_merge(q)
print([len(d.page_content) for d in merged], "자")

[212, 191, 249, 1488, 1450] 자

In [ ]:
# 메타데이터 필터링 & 다중 인덱스 : 적절한 조건 찾아서 구현해보기

최종 비교

In [289]:
PATTERNS = {"hybrid_rrf": hybrid,
            "ensemble": ensemble_top,
            "parent_doc": RunnableLambda(small_to_big),
            "sentence_window": RunnableLambda(sentence_window),
            "auto_merge": RunnableLambda(auto_merge)}

In [300]:
retrieval_results = [summarize(frames["base"], BASE)]
for name, retriever in PATTERNS.items():
    config = {**BASE, "name": name}
    golden, chunks, rows = run(config, chunks, retriever=retriever)
    frames[name] = grade(golden, chunks, rows)
    retrieval_results.append(summarize(frames[name], config))
    print(name, "완료")

hybrid_rrf 완료
ensemble 완료
parent_doc 완료
sentence_window 완료
auto_merge 완료

In [302]:
board = pd.DataFrame(retrieval_results).set_index("run").round(3)
board[["hit", "recall", "mrr", "ndcg", "오기권", "지연", "USD"]].sort_values("mrr", ascending=False)

                   hit  recall    mrr   ndcg    오기권     지연    USD
run
base             0.765   0.482  0.529  0.478  0.059  1.038  0.026
hybrid_rrf       0.824   0.271  0.525  0.291  0.118  1.185  0.028
ensemble         0.824   0.271  0.525  0.291  0.059  1.070  0.025
parent_doc       0.059   0.024  0.059  0.030  0.824  1.154  0.060
sentence_window  0.059   0.012  0.059  0.020  0.882  1.243  0.092
auto_merge       0.059   0.024  0.059  0.030  0.824  1.108  0.046

In [301]:
for name in ["base", "parent_doc", "sentence_window", "auto_merge"]:
    _, _, r = run({**BASE, "name": name}, chunks, retriever=PATTERNS.get(name))
    lens = [sum(len(t) for t in row["contexts"]) for row in r]
    print(f"{name:16} 문항당 컨텍스트 평균 {sum(lens) // len(lens):6,}자")

base             문항당 컨텍스트 평균  1,605자
parent_doc       문항당 컨텍스트 평균  4,313자
sentence_window  문항당 컨텍스트 평균  6,926자
auto_merge       문항당 컨텍스트 평균  2,949자

In [303]:
def regression(other, metric="mrr"):
    a = frames["base"].set_index("id")[metric]
    b = frames[other].set_index("id")[metric]
    diff = (b - a).dropna()
    return {"패턴": other, "평균차": round(diff.mean(), 3),
            "좋아짐": int((diff > 0).sum()), "나빠짐": int((diff < 0).sum())}

pd.DataFrame([regression(n) for n in PATTERNS]).set_index("패턴")

                   평균차  좋아짐  나빠짐
패턴
hybrid_rrf      -0.004    4    2
ensemble        -0.004    4    2
parent_doc      -0.471    0   12
sentence_window -0.471    0   12
auto_merge      -0.471    0   12

결론
- base : hit 제외 다른 지표들이 모두 좋음
- ensemble : hit에서는 좋은 효과. 단, 다른 지표들은 base보다 낮음

</br>
=> 최종적으로 ensemble 추가 확인 후 2개 중 결정
① 좋아진 사례, 나빠진 사례를 비교하여 유형에 따른 ensemble 확인
② ensemble의 가중치에 따른 결과로도 비교

<h3> 6. post-retrieval </h3>

- 크로스 인코더 리랭킹 : 질의와 문서를 붙여 한번에 읽음
- LLM 리랭커 : LLM에게 후보를 주고 순서를 매기게함
- 컨텍스트 압축 : 컨택스트 비용을 줄이고 검색 비용을 늘림
- MMR 중복제거 : 질의와의 유사도와 이미 고른것과의 거리를 함께 봄
- lost-in-the-middle : 정답 근거 하나를 앞, 가운데, 뒤에 두고 답을 받아봄 (가운데를 잘 잃어버리는 경향)

In [23]:
# 크로스 인코더 리랭킹
from sentence_transformers import CrossEncoder

TOP, WIDE = BASE["k"], 10
# 다국어 대안은 BAAI/bge-reranker-base 인데 내려받는 데 몇 분 걸린다
cross = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2", max_length=512)

def rerank_cross(question, top=TOP):
    docs = wide.invoke(question)
    scores = cross.predict([(question, d.page_content) for d in docs])
    order = sorted(range(len(docs)), key=lambda i: -scores[i])
    return [docs[i] for i in order[:top]]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 631.09it/s]

In [25]:
wide = store.as_retriever(search_kwargs = {"k" : WIDE})

q = golden[2]["question"]
w_docs = wide.invoke(q)
scores = cross.predict([(q, d.page_content) for d in w_docs])
print("벡터 순서  ", [d.metadata["page"] for d in w_docs])
print("리랭크 순서", [d.metadata["page"] for d in rerank_cross(q)])
print("점수       ", [round(float(s), 2) for s in scores])

벡터 순서   [18, 19, 21, 1, 29, 21, 5, 2, 5, 16]
리랭크 순서 [5, 18, 16, 21, 1]
점수        [8.94, 7.88, 7.14, 8.23, 7.78, 8.71, 8.95, 7.93, 7.81, 8.86]

Cross-Encoder가 정답 청크에 다소 높은 점수를 부여하지만 분리도는 낮다. (정답청크의 범위가 마이너스까지 내려가는 경우도 있음)
=> 질문별 Hit@K/MRR/nDCG의 리랭킹 전후 변화를 확인해야 한다

In [26]:
hit_scores, miss_scores = [], []
for g in [x for x in golden if x["answerable"]]:
    cands = wide.invoke(g["question"])
    values = cross.predict([(g["question"], d.page_content) for d in cands])
    for d, v in zip(cands, values):
        (hit_scores if is_evidence(d.page_content, g) else miss_scores).append(float(v))
print(len(hit_scores), "정답 청크", len(miss_scores), "오답 청크")

print(f"정답 청크 {len(hit_scores):3d}개  평균 {sum(hit_scores) / len(hit_scores):6.2f}"
      f"  범위 {min(hit_scores):.2f} ~ {max(hit_scores):.2f}")
print(f"오답 청크 {len(miss_scores):3d}개  평균 {sum(miss_scores) / len(miss_scores):6.2f}"
      f"  범위 {min(miss_scores):.2f} ~ {max(miss_scores):.2f}")

29 정답 청크 141 오답 청크
정답 청크  29개  평균   6.17  범위 -1.94 ~ 8.35
오답 청크 141개  평균   5.76  범위 -2.70 ~ 8.95

In [30]:
# LLM 리랭커
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field


class Ranking(BaseModel):
    order: list[int] = Field(description="질문에 도움이 되는 순서대로 나열한 근거 번호")


ranker = ChatPromptTemplate.from_messages([
    ("system", "질문에 답하는 데 도움이 되는 순서대로 근거 번호를 나열한다. 번호만 쓴다."),
    ("human", "질문\n{q}\n\n근거\n{docs}"),
]) | ChatOpenAI(model=LOWER).with_structured_output(Ranking)

def rerank_llm(question, top=TOP):
    docs = wide.invoke(question)
    listing = "\n\n".join(f"[{i}] {d.page_content[:300]}" for i, d in enumerate(docs, 1))
    order = ranker.invoke({"q": question, "docs": listing}, config={"callbacks": [usage]}).order
    picked = [docs[i - 1] for i in order if 1 <= i <= len(docs)]
    return (picked + [d for d in docs if d not in picked])[:top]

print("벡터 순서  ", [d.metadata["page"] for d in w_docs])
print("리랭크 순서", [d.metadata["page"] for d in rerank_llm(q)])

벡터 순서   [18, 19, 21, 1, 29, 21, 5, 2, 5, 16]
리랭크 순서 [19, 18, 21, 1, 29]

In [34]:
# 컨텍스트 압축
from langchain_classic.retrievers import ContextualCompressionRetriever
from langchain_classic.retrievers.document_compressors import EmbeddingsFilter, LLMChainExtractor

# 문서 단위로 잘라냄
embed_filter = ContextualCompressionRetriever(
    base_compressor=EmbeddingsFilter(embeddings=embeddings, similarity_threshold=0.4),# threshold 0.4
    base_retriever=wide)
# 문서 안에서 질문에 관련된 문장만 남김
llm_extract = ContextualCompressionRetriever(
    base_compressor=LLMChainExtractor.from_llm(ChatOpenAI(model=LOWER)),
    base_retriever=store.as_retriever(search_kwargs={"k": TOP}))

print("임베딩 필터", len(embed_filter.invoke(q)), "개 통과")
kept = llm_extract.invoke(q, config={"callbacks": [usage]})
print("LLM 추출  ", len(kept), "개", [len(d.page_content) for d in kept], "자")

임베딩 필터 10 개 통과
LLM 추출   3 개 [22, 31, 52] 자

In [44]:
# MMR 중복제거
mmr = store.as_retriever(search_type="mmr", search_kwargs={"k": TOP, "fetch_k": WIDE * 3, "lambda_mult": 0.5})
print("기본", [(d.metadata["source"], d.metadata["page"]) for d in store.similarity_search(q, k=TOP)])
print("MMR ", [(d.metadata["source"], d.metadata["page"]) for d in mmr.invoke(q)])

기본 [('2. Hmall 소개서 (p.30).pdf', 18), ('2. Hmall 소개서 (p.30).pdf', 19), ('1. 협력사 운영 통합 안내서 (p.23).pdf', 21), ('4. 광고 상품 소개서 (p.24).pdf', 1), ('2. Hmall 소개서 (p.30).pdf', 29)]
MMR  [('2. Hmall 소개서 (p.30).pdf', 18), ('4. 광고 상품 소개서 (p.24).pdf', 1), ('2. Hmall 소개서 (p.30).pdf', 29), ('2. Hmall 소개서 (p.30).pdf', 19), ('1. 협력사 운영 통합 안내서 (p.23).pdf', 1)]

In [55]:
# lost-in-the-middle
import re

CITED = "근거만으로 답한다. 사용한 근거 번호를 반드시 [n] 으로 밝힌다."
answer_at = ChatPromptTemplate.from_messages([("system", CITED),
                                              ("human", "근거\n{context}\n\n질문\n{question}")]) | ChatOpenAI(model=LOWER)

def place(g, position, size=8):
    gold = next(c for c in chunks if is_evidence(c.page_content, g))
    others = [d for d in store.similarity_search(g["question"], k=size * 2)
              if not is_evidence(d.page_content, g)][:size - 1]
    slot = {"앞": 0, "가운데": size // 2, "뒤": size - 1}[position]
    place_docs = others[:slot] + [gold] + others[slot:]
    return place_docs, slot + 1

targets = [g for g in golden if g["answerable"] and any(is_evidence(c.page_content, g) for c in chunks)]
print(len(targets), "문항")

for position in ["앞", "가운데", "뒤"]:
    used = 0
    for g in targets:
        place_docs, number = place(g, position)
        context = "\n\n".join(f"[{i}] {d.page_content}" for i, d in enumerate(place_docs, 1))
        text = answer_at.invoke({"context": context, "question": g["question"]},
                                config={"callbacks": [usage]}).content
        used += str(number) in re.findall(r"\[(\d+)\]", text)
    print(f"정답을 {position:4} 에 두었을 때 그 번호를 인용한 문항 {used}/{len(targets)}")

17 문항
정답을 앞    에 두었을 때 그 번호를 인용한 문항 16/17
정답을 가운데  에 두었을 때 그 번호를 인용한 문항 15/17
정답을 뒤    에 두었을 때 그 번호를 인용한 문항 17/17

In [58]:
from langchain_core.runnables import RunnableLambda

PATTERNS = {"rerank_cross": RunnableLambda(rerank_cross),
            "rerank_llm": RunnableLambda(rerank_llm),
            "compress_embed": embed_filter,
            "compress_llm": llm_extract,
            "mmr_wide": mmr}

post_retrieval_result = []
for name, retriever in PATTERNS.items():
    config = {**BASE, "name": name}
    golden, chunks, rows = run(config, chunks, retriever=retriever)
    frames[name] = grade(golden, chunks, rows)
    post_retrieval_result.append(summarize(frames[name], config))
    print(name, "완료")

board = pd.DataFrame(post_retrieval_result).set_index("run").round(3)
board[["hit", "recall", "mrr", "ndcg", "오기권", "지연", "USD"]].sort_values("mrr", ascending=False) # 적어도 HIT, RECALL은 사용을 꼭 해야!

rerank_cross 완료
rerank_llm 완료
compress_embed 완료
compress_llm 완료
mmr_wide 완료

                  hit  recall    mrr   ndcg    오기권     지연    USD
run
rerank_llm      1.000   0.388  0.912  0.493  0.059  1.550  0.028
compress_embed  1.000   0.365  0.669  0.382  0.059  1.264  0.042
compress_llm    0.824   0.413  0.575  0.413  0.000  1.231  0.014
mmr_wide        0.588   0.149  0.497  0.197  0.353  1.320  0.027
rerank_cross    0.706   0.235  0.479  0.252  0.176  1.293  0.029

In [59]:
def regression(other, metric="mrr"):
    a = frames["base"].set_index("id")[metric]
    b = frames[other].set_index("id")[metric]
    diff = (b - a).dropna()
    return {"패턴": other, "평균차": round(diff.mean(), 3),
            "좋아짐": int((diff > 0).sum()), "나빠짐": int((diff < 0).sum())}

pd.DataFrame([regression(n) for n in PATTERNS]).set_index("패턴")

                  평균차  좋아짐  나빠짐
패턴
rerank_cross   -0.050    5    7
rerank_llm      0.382    9    0
compress_embed  0.139    9    0
compress_llm    0.046    7    2
mmr_wide       -0.032    2    4